### ISSUE TITLE
[bug]setx 会影响zlist的结果 

### ISSUE THREAD

**Issue by xjcloudy** [ideawu/ssdb#1008]
- 先setx一个值。
>setx k1 live 10
- 使用zlist命令
>zlist "" "" 10

- 结果：当setx的值没过期时，zlist返回内容会出错。无论zlist本身有没有值。
```
              key
-----------------
  �����|EXPIRE_LIST|KV
1 result(s) (0.001 sec)
```

`version 1.9.4`

**Comment by ideawu** [comment]
设计上***EXPIRE_LIST|KV是用来保存ttl的, 没有问题.
