### ISSUE TITLE
ssdb-server process does not returns memory. 

### ISSUE THREAD

**Issue by ignung** [ideawu/ssdb#1009]
Hi, I'm testing ssdb-server with Jedis framework.
Its functionality and performance is great !!!
perfect Redis replacement, I love it.

but One problem blocks me from applying to operation.

=> "Physical & virtual memory is only allocated and not released."

The "Demo" application provided has the same problem.
calling ssdb.del() does not free memory.
and setting value to the same key increases memory usage. 

I use Mint linux (almost same as ubuntu) as test platfom.
and didn't changed any option, and I just build and install and run as manual. 

How's the other guys ???
Did I done something wrong or didn't done something essential???

Thanks in advance.

**Comment by ideawu** [comment]
Hi,

First, SSDB does not claim to alloc or free memory every time you operate on it. SSDB will alloc and free memory on its own dicision.

Second, here's the doc desribes some on memory management - http://ssdb.io/docs/config.html . Normally, with the default config file, ssdb-server will use up to 2GB memory, and maybe more when the server is on heavy load, less memory usage maybe applied.

**Comment by muyinliu** [comment]
@ideawu Docs between different languages show different algorithm, please check:

1. http://ssdb.io/docs/zh_cn/config.html says `cache_size + write_buffer_size * 66 + 32`
2. http://ssdb.io/docs/config.html says `cache_size * 2 + write_buffer_size * 66 + 32`

Which one is correct?

**Comment by ideawu** [comment]
`cache_size + write_buffer_size * 66 + 32`

is correct, the doc is updated.

**Comment by muyinliu** [comment]
@ideawu Doc http://ssdb.io/docs/config.html not update yet.

**Comment by muyinliu** [comment]
@ideawu Doc http://ssdb.io/docs/config.html not update yet. Please check:
![qq20161124-0](https://cloud.githubusercontent.com/assets/3318872/20596072/a16e204a-b277-11e6-8b7d-575614ede1ff.jpg)

**Comment by ideawu** [comment]
clean you browser's cache.

**Comment by muyinliu** [comment]
Checked. Thanks.

**Comment by CaledoniaProject** [comment]
所以，默认设置算出来，10 * 64MB * 66 = 40 GB?
