### ISSUE TITLE
新增主/从遇到问题

### ISSUE THREAD

**Issue by wanghengyu** [ideawu/ssdb#1015]
我有一个ssdb实例现在data目录60多G，现在准备将这些数据迁往一台新的ssd服务器上，遇到如下问题：
1.新增从服务之后，从服务状态从copy变成out_of_sync
2.新增主服务之后，新主服务状态也从copy变成out_of_sync，老主服务状态为copy

现在写入每秒将近1000次，我该如何解决这个问题？

**Comment by ideawu** [comment]
你需要找一个空闲的时间来加新节点.

**Comment by ideawu** [comment]
从 1.9.3 版本开始, 可能在配置文件里配置

```
replication:
	binlog: yes
		capacity: 100000000
```
来避免 OUT_OF_SYNC.
