### ISSUE TITLE
双主同步问题

### ISSUE THREAD

**Issue by yemt** [ideawu/ssdb#1018]
您好，我配置了一个双主模式，master1的binlogs.max_seq 和master1的 replication.client.last_seq是相等的，也和master2的 replication.slaveof.last_seq相等，这样我可以认为是master1的命令都同步到master2了，但是为什么master1的binlogs.max_seq不等于master1的 replication.slaveof.last_seq，是不是表示两者有不一致的数据呢？

**Comment by yemt** [comment]
如果是的话该怎么避免呢？

**Comment by catlittlechen** [comment]
@yemt  可以先看下这个issue 
https://github.com/ideawu/ssdb/issues/711

**Comment by yemt** [comment]
3q
