### ISSUE TITLE
数据迁移方案相关问题

### ISSUE THREAD

**Issue by will835559313** [ideawu/ssdb#1027]
我想把A机器上的SSDB实例中的数据通过内网迁移到B机器的SSB实例中，并且不能删除B中实例的数据，可以覆盖部分key一致的数据。请问以下哪个方案最快
1. 备份 SSDB 数据(导出/导入) export import
2. 主从复制迁移数据
3. 使用ssdb-dump

**Comment by will835559313** [comment]
@ideawu  麻烦解答下我的疑问

**Comment by ideawu** [comment]
根据你的需求, 1是三者之中唯一可行的.

**Comment by will835559313** [comment]
主从复制也可做数据迁移吧 。   如果B配置为A的从，这样A的数据不就可以迁移到B上了吗 ？
B上原来的数据不会被完全清空吧。 还是会保留B上原来的数据吧  前提条件是这两个实例上的key完全不同
@ideawu

**Comment by ideawu** [comment]
在以前的某些版本, 主从配置起来后, 从库会先删除自己的全部数据. 如果你使用的是目前主干上的, 你所说的方法应该是可行的.

**Comment by will835559313** [comment]
1.9.2会有这个问题吗

**Comment by will835559313** [comment]
控制同步速度的参数 可以设置小数吗
比如 sync_speed: 0.1

**Comment by will835559313** [comment]
1.9.2之后的版本不会删除原来的数据，不包括1.9.2版本
