### ISSUE TITLE
如何编辑脚本自动执行`export -i filename` 命令？

### ISSUE THREAD

**Issue by linjunzhu** [ideawu/ssdb#1031]
目前需求是这样的：

在某个时间点我需要导出某些 key 值。

正常导出为：

```
$ ssdb-cli
$ export -i backup filename
$ key 区间范围
```

但是我需要用脚本自动执行。

```
echo "export -i filename" | ssdb-cli
```

但是要如何输入 key 的区间范围呢？  export 并不支持直接附带参数

**Comment by JeahamChain** [comment]
试一下写个expect脚本,可以把你需要的逻辑和参数写进去,可以执行export -i 的时候判断ssdb-cli的输出,并自动输入你想输入的参数。

**Comment by linjunzhu** [comment]
@JeahamChain  Thx,  我尝试下，之前是直接修改了 export 脚本完成的
