### ISSUE TITLE
大约上亿的key吧，flushdb极慢

### ISSUE THREAD

**Issue by markqiu** [ideawu/ssdb#1035]
好几天都没完成，只能重启，重启后从phpadmin去访问就总是timeout

**Comment by cuixin** [comment]
看下代码吧，flushdb是while直到key删除的，要是删除这么大的数据库，建议直接停掉进程删除目录即可。

**Comment by markqiu** [comment]
既然提供此功能，总要保证质量吧，目前是执行后好像永远执行不完了。

**Comment by johndb2016** [comment]
@markqiu 自己修改一下代码，把flushdb改成批量操作，上亿级别的db单个删除效率太低。。。

**Comment by markqiu** [comment]
@johndb2016  好的哈，我试试

**Comment by chu8129** [comment]
刚刚遇到这个问题，数据量就几w，等了好久还在执行状态。。。

**Comment by ideawu** [comment]
是的，会有这个问题。

如果可以，建议stop server，然后shell删除 data meta 两个目录。
