### ISSUE TITLE
queue 中如何删除指定 queue 中的 指定name

### ISSUE THREAD

**Issue by DevilH** [ideawu/ssdb#1040]
例如,只想删除mesage queue 中 msgid_123456 有没有相对应的命令

**Comment by bigpyer** [comment]
qtrim_front name size

**Comment by DevilH** [comment]
这个命令是从头部删除多个元素~~~不是我说的在队列中删除指定的value

**Comment by DevilH** [comment]
有没有类似redis 的 lRem, lRemove 的命令

**Comment by bigpyer** [comment]
ssdb并没有提供删除list中指定元素的命令

**Comment by ideawu** [comment]
@DevilH http://ssdb.io/docs/zh_cn/commands/qtrim_front.html
