### ISSUE TITLE
import tool bug: lost some data.

### ISSUE THREAD

**Issue by cuixin** [ideawu/ssdb#1063]
in importer.cpy's bug.

if the lines have space or \t, the data will be interrupt truncation.

Version: ssdb.1.9.3

**Comment by cuixin** [comment]
in importer.cpy's bug.

if the lines have space or \t, the data will be interrupt truncation.

**Comment by cuixin** [comment]
the importer.cpy line:24

changed line.strip() to line.rstrip('\n') the problem has be solved.

**Comment by ideawu** [comment]
Hi, can you provide some code the prove it?

**Comment by ideawu** [comment]
Thank you, I will fix it.

**Comment by ideawu** [comment]
fixed.
