### ISSUE TITLE
ssdb-cli 密码验证问题

### ISSUE THREAD

**Issue by isoleo** [ideawu/ssdb#1067]
Usage:
	ssdb-cli [-h] [HOST] [-p] [PORT]

Options:
	-h 127.0.0.1
		ssdb server hostname/ip address
	-p 8888
		ssdb server port
	-v --help
		show this message
	-n [info, dbsize, replication, write_read]
		choose nagios probe
	-w INT
		set nagios WARN level
	-c INT
		set nagios CRITICAL level

Examples:
	ssdb-cli
	ssdb-cli 8888
	ssdb-cli 127.0.0.1 8888
	ssdb-cli -h 127.0.0.1 -p 8888
	ssdb-cli -h 127.0.0.1 -p 8888 -n dbsize -w 500000 -c 600000
	ssdb-cli -h 127.0.0.1 -p 8888 -n replication
	ssdb-cli -h 127.0.0.1 -p 8888 -n write_read
	ssdb-cli -n info

以上帮助并没有说明哪个参数是密码验证的？麻烦告诉一下，谢谢

**Comment by ideawu** [comment]
已经 fix.

**Comment by ideawu** [comment]
在启动 ssdb-cli 连接后, 执行 `auth xxxxx`.
