### ISSUE TITLE
There may be a bug about the limit of compaction speed in leveldb...

### ISSUE THREAD

**Issue by johndb2016** [ideawu/ssdb#1070]
@ideawu 
Your code:
int pause = 1000 * 1000 / count;
Log(options_.info_log, "compaction_speed: %d MB, pause: %d us",options_.compaction_speed, pause);
env_->SleepForMicroseconds(pause);

Problem:
If 'count' equals 1, it will sleep 1000 secs，that is terrible... u may divide 'pause' by 1000, right?

**Comment by ideawu** [comment]
1 second = 1 x 1000 x 1000 micro seconds, micro second is not milli second.

Many people(me used to) think micro second is `ms`, actually it is `us`.

**Comment by johndb2016** [comment]
Got it, thanks, by the way, i am curious about the 'max_open_files' of leveldb, if ssdb set to 500 or 1000 by default, don't u worried about the whole mem consumed by the compact thread? It may open 500 or 1000 sstable files(32MB), that means about 16GB or 32GB mem, right?

**Comment by johndb2016** [comment]
@ideawu Got it, thanks, by the way, i am curious about the 'max_open_files' of leveldb, if ssdb set to 500 or 1000 by default, don't u worried about the whole mem consumed by the compact thread? It may open 500 or 1000 sstable files(32MB), that means about 16GB or 32GB mem, right?
