### ISSUE TITLE
主从结构中，master删除数据后，slave上仍然占用大量硬盘空间

### ISSUE THREAD

**Issue by LoveEachDay** [ideawu/ssdb#1080]
我们有两台ssdb 服务器配置了主从结构， 现在master 上删除了大量数据 (数据从500G减少到100多G), 但是slave 上仍然占用400+G的硬盘空间。

这是master 上info 命令返回结果：
```
version
	1.9.2
links
	387
total_calls
	19086459114
dbsize
	79522319634
binlogs
	    capacity : 20000000
	    min_seq  : 4781279531
	    max_seq  : 4801288309
replication
	client *.*.*.*:36298
	    type     : sync
	    status   : SYNC
	    last_seq : 4801288302
```

slave 上 info 命令返回结果：
```
version
	1.9.2
links
	3
total_calls
	31
dbsize
	417862469767
binlogs
	    capacity : 20000000
	    min_seq  : 2247105001
	    max_seq  : 2267113680
replication
	slaveof master.internal:8765
	    id         : master.internal|8765
	    type       : sync
	    status     : SYNC
	    last_seq   : 4801290377
	    copy_count : 498679783
	    sync_count : 1766108946
```
根据master 上的 info命令，显示master-slave 同步状态是sync, 但是两个服务器的dbsize 相差很大。能解释一下这是为什么吗？

**Comment by ideawu** [comment]
http://ssdb.io/docs/zh_cn/faq.html

>     问: 我把一个, 两个, 或者所有的 key 都删除了, 为什么 SSDB 占用的内存和磁盘空间并没有释放?
> 
>     答: SSDB 有自己策略来决定何时释放或者是否释放内存和硬盘占用, 你不能要求 SSDB 立即或者在未来某个时间, 或者基于某个条件 释放这些空间. 而且, 即使数据库清空了, SSDB 仍然会保留一些信息, 因此仍然占用部分硬盘空间. 你不应该关心这个问题.

另外，SSDB不保证同样的数据在不同的机器或者实例上的硬盘存储结构是一模一样的。

**Comment by LoveEachDay** [comment]
谢谢回复。
在slave 上执行compact 命令，占用硬盘空间显著减少。
