### ISSUE TITLE
Hash map 个数是否有限制？

### ISSUE THREAD

**Issue by slw2011** [ideawu/ssdb#1081]
请问，ssdb hash map的格数是否有限制，而不是当个hash map 中 key的数量限制，这个页面http://ssdb.io/docs/zh_cn/limit.html 只有当个hash map 中key的数量，没有提到整个库中 hash map的个数限制

**Comment by ideawu** [comment]
无限制。

**Comment by slw2011** [comment]
OK, Thanks.
