### ISSUE TITLE
ssdb-dump 导入数据缺失

### ISSUE THREAD

**Issue by gglinux** [ideawu/ssdb#1086]
重现步骤：
1. 在一台机器A上使用 ssdb-dump 导出 全部数据
2. 另一台机器B上更改work_dir 指向上一步的目录（参照文档）

结果：
1. 使用phpssdbmyadmin 和 info能看到数据已经写入
level：3      file：578     size：9153 
2. 在phpssdbmyadmin queue一栏能看到导入的值，但其他的数据类型(kv,hash)为空

版本：A SSDB:1.9.0
          B SSDB:1.9.4

**Comment by ideawu** [comment]
这很奇怪。你再确认一下，情况是否是：
1. 原来的db有kv,hash等数据，非常确定有？
2. 同时，恢复的数据里完全没有kv,hash数据，非常确定没有？

**Comment by gglinux** [comment]
1. 确定原来是有数据的
2. 确定恢复后没有数据
A机器
version
	1.9.0
links
	6
total_calls
	391506633
dbsize
	9366979881
binlogs
	    capacity : 10000000
	    min_seq  : 18002380
	    max_seq  : 28740540
serv_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
data_key_range
	    kv  : "ALBUM_100" - "user_download_times__0"
	    hash: "android_count_data" - "user_collections"
	    zset: "app_sort_by_gift" - "user_mine_app_76160008"
	    list: "ALBUM_100" - "test_soft_apps"
leveldb.stats
	                               Compactions
	Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
	--------------------------------------------------
	  0        0        0         0        0         0
	  1        0        0       152        7      2540
	  2       12        6       202     3763      2526
	  3      569     9076      4984   121083    119244

B机器
version
	1.9.4
links
	1
total_calls
	168
dbsize
	9453752912
binlogs
	    capacity : 20000000
	    min_seq  : 16002342
	    max_seq  : 26892722
serv_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
data_key_range
	    kv  : "test123" - "test123"
	    hash: "" - ""
	    zset: "" - ""
	    list: "board_bestgame" - "board_mustplay"
leveldb.stats
	                               Compactions
	Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
	--------------------------------------------------
	  0        2        4         0        0         0
	  2       10        0         0        0         0
	  3      578     9153         0        0         0

17 result(s) (0.003 sec)

test123 是后面写入进去的

**Comment by ideawu** [comment]
你现在重新备份还是有同样的问题吗？

**Comment by gglinux** [comment]
是的，不知道什么原因

**Comment by gglinux** [comment]
数据总共有8个多G

**Comment by ideawu** [comment]
麻烦把 A 的 log 贴上来看看。你可以 grep backend_dump.cpp

**Comment by ideawu** [comment]
另外，你最好确认一下路径是否正确。

**Comment by ideawu** [comment]
你肯定把路径弄错了。

```
binlogs
	    capacity : 20000000
	    min_seq  : 16002342
	    max_seq  : 26892722
```

一个新的 slave 怎么可能有 binlog？

**Comment by gglinux** [comment]
兄弟，打扰到你了。抱歉

线上机器我没权限，是运维操作的。他弄错了，把data文件夹直接打包给我了，不是用的ssdb-dump

**Comment by ideawu** [comment]
哈哈.
