### ISSUE TITLE
ssdb的info是否可以优化下

### ISSUE THREAD

**Issue by wenskys** [ideawu/ssdb#1095]
最近想要将多个ssdb做聚合监控分析，发现取值不太方便，想问下如何去做ssdb的监控呢？是否可以将info的输出转化成redis那样key:value对应的数据，方便对info数据进行分析？

**Comment by ideawu** [comment]
抱歉，ssdb-cli不会做此更改。你可以使用php/python等语言的api来执行这个命令，返回的结果就是kv结构，不需要文本分析。
