### ISSUE TITLE
zset 部分数据已删除  执行了zclear  但是 zsize  显示还有数据

### ISSUE THREAD

**Issue by Entropy03** [ideawu/ssdb#1096]
版本 1.9.2 

![default](https://cloud.githubusercontent.com/assets/9947011/26624414/5cf431a8-4623-11e7-836f-bf8686f0ab40.jpg)

只有个别数据 这个样子 请问这个是什么原因

**Comment by Entropy03** [comment]
执行了 修复和 compact都不行

**Comment by ideawu** [comment]
你好，你用 zfix 命令修复一下。

```
zfix zname
```

**Comment by Entropy03** [comment]
@ideawu  好用了 ，非常感谢 ，还有我想知道导致这个问题的会是哪些原因呢？  我好以后避免出现类似问题 谢谢

**Comment by ideawu** [comment]
有可能是系统异常关机，或者你曾经 kill -9 杀过 ssdb-server 进程。
