### ISSUE TITLE
SSDB 双主 删除 key 的时候，有时候并删除不掉

### ISSUE THREAD

**Issue by winjeg** [ideawu/ssdb#1097]
实例是新搭建的实例， 基本没负载， 所以可以排除负载问题。
而且双主搭建好之后同步是对的。
表现是有时候可以删掉， 有时候删除了之后 去 get 还有，请问这个是什么可能的原因导致的？

```
10.1.8.132:6379> del a
(integer) 1
10.1.8.132:6379> get a
"12"
10.1.8.132:6379> get a
"12"
10.1.8.132:6379> del a
(integer) 1
10.1.8.132:6379> get a
(nil)
10.1.8.132:6379> 


```

**Comment by ideawu** [comment]
应该没配置对。请严格完全按文档进行配置测试。

**Comment by winjeg** [comment]
我把我的配置贴出来，麻烦帮看一下：
服务器信息：
`             total       used       free     shared    buffers     cached
Mem:          7984       1730       6254          6        149       1214
-/+ buffers/cache:        365       7618
Swap:         1019          0       1019`

**Comment by winjeg** [comment]
有查到其他地方说应该用mirror 的同步方式做双主， 讲明了为什么。
暂时换成用mirror 的方式没发现大的问题。
