### ISSUE TITLE
这配置合理吗？

### ISSUE THREAD

**Issue by ming20130** [ideawu/ssdb#1098]
服务器配置：CPU E3-1230 内存32G  硬盘1TB SSD 
```
leveldb:
	# in MB
	cache_size: 16000
	# in MB
	write_buffer_size: 128
	# in MB/s
	compaction_speed: 1000
	# yes|no
	compression: yes
```
请问leveldb的配置合理吗？@ideawu

**Comment by ming20130** [comment]
这样的配置会占用多少内存，这个计算方式是怎么样的？@ideawu

**Comment by fengjiajie** [comment]
http://ssdb.io/docs/zh_cn/config.html
这个文档下面有内存计算公式

**Comment by ming20130** [comment]
如果 compression: yes, 计算公式是:
cache_size + 10 * write_buffer_size * 66 + 32
16000+10*128*66+32=100512MB  
100512÷1024=98.15625
这样计算不是用了98G内存？@fengjiajie @ideawu

**Comment by ideawu** [comment]
请务必仔细，认真，重复地看文档。
