### ISSUE TITLE
IO磁盘使用突然变高, 是否Compaction引起?

### ISSUE THREAD

**Issue by Cavinlz** [ideawu/ssdb#1100]
今天服务器io某个时间段突然io剧增， util 100% 导致客户端响应变慢(ssdb关闭了compression功能)，持续大概1个小时， 请问是Compaction导致的么?  

日志中只看到有警告
[WARN ] server.cpp(319): long loop time: 2.333

**Comment by ideawu** [comment]
这个报警的出现，一般是在ssdb-server极端频繁的情况，或者服务器上其它进程极端繁忙相互影响导致io资源紧张导致的。
