### ISSUE TITLE
Mac OS 上关闭ssdb报错

### ISSUE THREAD

**Issue by youmisun** [ideawu/ssdb#1102]
在/usr/local/ssdb目录下使用./ssdb-server ssdb.conf -s stop这条命令关闭ssdb出现以下错误：

could not read pidfile: ./var/ssdb.pid(No such file or directory)

**Comment by ideawu** [comment]
可能服务没有启动，或者之前启动时pid在别的地方。你可以通过ps命令找出真实的pid，然后自己执行 kill xxx，注意，不要执行 kill -9.
