### ISSUE TITLE
cp: cannot stat ‘ssdb-server’: No such file or directory make: *** [install] Error 1

### ISSUE THREAD

**Issue by shinebay** [ideawu/ssdb#1106]
设置了sudo make install PREFIX=/home/ssdb，最后报错：
mkdir -p /home/ssdb
mkdir -p /home/ssdb/_cpy_
mkdir -p /home/ssdb/deps
mkdir -p /home/ssdb/var
mkdir -p /home/ssdb/var_slave
cp -f ssdb-server ssdb.conf ssdb_slave.conf /home/ssdb
cp: cannot stat ‘ssdb-server’: No such file or directory
make: *** [install] Error 1
请问这个怎么解决，谢谢

**Comment by fengjiajie** [comment]
install 前没有 make ？或者编失败了？

**Comment by shinebay** [comment]
@fengjiajie 不是先执行sudo make install PREFIX=/home/ssdb再make install么，我先执行sudo make install PREFIX=/home/ssdb时就报这个错了，网上搜了下，也有人同样出现这个问题： [www.04007.cn/article/327.html](www.04007.cn/article/327.html)  貌似ssdb不能更改PREFIX？？？我就想直接在Makefile里面更改PREFIX=home/ssdb行不行？

**Comment by fengjiajie** [comment]
先执行：
make
然后再执行：
sudo make install PREFIX=/home/ssdb

我理解的是不用再执行 make install 了

**Comment by shinebay** [comment]
@fengjiajie 好吧，我眼花了，搞错了，谢谢
