### ISSUE TITLE
ssdb 重启超慢

### ISSUE THREAD

**Issue by cuihuan** [ideawu/ssdb#1108]
./ssdb-server ssdb.conf -s restart  直接重启，超慢

杀死进程，删除pid，直接启动很快，数据也不会丢失？

为什么按照重启指令这么慢？

**Comment by ideawu** [comment]
请不使用 kill -9

**Comment by cuihuan** [comment]
不适用kill -9 的话，我试了下，大概56亿的数据，一个小时都没有反应，kill start后很快，是应为ssdb在进行某方面的操作吗？
