### ISSUE TITLE
php通过redis扩展操作ssdb时， 如何删除指定的hash数据。

### ISSUE THREAD

**Issue by WriteHappy** [ideawu/ssdb#1111]
【背景】
我搭建了两个ssdb，它们的前端用twemproxy做代理。SSDB.php的方式貌似不能连接调用twemproxy，但是好在twemproxy支持redis协议，所以目前是php通过redis扩展来和twemproxy进行交互。
【问题】
存储结构用到了hash，我知道用hclear在命令的模式下可以删除整个hash。但是如果php通过redis扩展，该如何删除hash呢？del是不好使的， 尽管返回的结果是1。

**Comment by WriteHappy** [comment]
ssdb支持redis协议， 但是也不是100%支持。 可是现在已经比较骑虎难下了。
自己还是想php通过redis扩展删除hash数据。

**Comment by ideawu** [comment]
对于这个问题我也很抱歉，我认为原因还是在于phpredis扩展的开发者鼠目寸光，不考虑可扩展性。它应该支持执行_任意命令_，而不论这个命令是否是redis支持的。可惜，phpredis的开发者眼界比较窄。

**Comment by WriteHappy** [comment]
不管怎么样， 还是谢谢开发者及时的回复了。

**Comment by ideawu** [comment]
更新，经过我对phpredis的重新了解，发现phpredis最新版本是支持 rawcommand() 发送任意命令的。

**Comment by jerry-yuan** [comment]
phpredis即使使用rawcommand也无法将hclear穿过twemproxy送达ssdb
