### ISSUE TITLE
Is there a limit regarding the number of hashmaps in ssdb?

### ISSUE THREAD

**Issue by bvqbao** [ideawu/ssdb#1113]
Hi,

Since set data structure (sadd, smembers,...) is not supported in ssdb, I use hashmap (hset, hkeys,...) as a set. My application requires the use of a lots of sets/hashmaps. So I wonder if is there a limit regarding the number of hashmaps in ssdb?

Thanks,
Bao Bui

**Comment by ideawu** [comment]
There is no limitation of number of hashmaps.

See this for the limitation of number of elements in a hashmap  http://ssdb.io/docs/limit.html

**Comment by bvqbao** [comment]
Thank!
