### ISSUE TITLE
关闭rotate的情况下，如果mv log.txt log.txt.时间戳，日志内容会打到新的log.txt.时间戳文件里面

### ISSUE THREAD

**Issue by WriteHappy** [ideawu/ssdb#1114]
【ssdb版本】1.9.4
【相关配置】logger 里面rotate都被注释掉
【操作】启动服务后，将log.txt mv成别的文件，比如  mv   log.txt   log.txt.2017
【期望】在mv操作之后，有全新的log.txt文件生成，新的日志都打印到log.txt里面
【当前现象】没有log.txt生成，这之后的日志内容都打印到了log.txt.2017文件里面

我知道ssdb有logrotate的功能， 但是不巧的是因为后缀时间格式的问题，我用不上。
所以我只能关闭ssdb自身的logrotate功能，希望它能一直写日志到一个固定文件里面。

**Comment by WriteHappy** [comment]
粗略的看源码是Logger::logv方法里面用到的成员变量 this->fd是具体的文件句柄， write(this->fd, buf, len);
如果手动mv了log.txt文件但是文件句柄并没有变化， 所以依旧会写log，但是却写到了mv之后的新文件中。 是这样理解吗？

**Comment by ideawu** [comment]
没错。你的期望无法达到。

**Comment by WriteHappy** [comment]
可以的啊， 简单的修改的话，需要改源码，重新对文件句柄赋值就好了。
this->fd = ::open(this->filename, O_CREAT | O_WRONLY | O_APPEND, 0644);
write(this->fd, buf, len);

**Comment by ideawu** [comment]
基于性能考虑，当然不会那么做。
