### ISSUE TITLE
ssdb完全兼容Redis API

### ISSUE THREAD

**Issue by panjunyong** [ideawu/ssdb#1119]
Redis的最大问题是现在是Windows版本各种不稳定，完全不可用，而且微软已经放弃了这个项目。

所以，我想起SSDB。试了一下，似乎API和redis并不相同，具体：

1. 没有select多个数据库(这个可以忍，我们可以用一个数据库)
2. 我执行一个简单的KEYS命令，就报告wrong number of arguments

所以，我希望能够完全兼容Redis API，这样将是ssdb推广的重要途径。

不知道项目是否有这方面的计划

**Comment by ideawu** [comment]
”完全兼容Redis“过去不是SSDB的特性，未来也不会是。SSDB的特性是尽量兼容Redis。这是各方面综合考虑的结果。

KEYS命令很显然不是生产环境使用的，SSDB提供了更优的不同解。一般来说，SSDB的用户知道SSDB并非*完全*等同Redis，并且认可这种不同造成的成本是可接受的。

**Comment by ideawu** [comment]
补充：SSDB的Windows版本是供用户开发和测试用的，并非生产环境使用，你需要注意。

**Comment by changquanyou** [comment]
对于关于并发的问题；因为changeTable操作是显示的；那么在多线程下；需要对任何 changeTable的上下文进行加锁；保证可靠性；或者changeTable能封装在底层；上层应用传入对应的参数；锁的控制由底层控制。
