### ISSUE TITLE
ssdb-cli cannot display some data(using string_escape)

### ISSUE THREAD

**Issue by cuixin** [ideawu/ssdb#1124]
Some hex data cannot display in ssdb-cli.

I recommend that using string_escape in ssdb_cli to translate the data for display, it's could be better for copy and manipulation.

Replaced the **api/python/SSDB.py** 's 437 line:

 **ret.append(data.encode("string_escape"))**

**Comment by ideawu** [comment]
Hi, you can submit a pull request to make the change, and provide the test data as well.

**Comment by cuixin** [comment]
#1125 my PR, you can set some binary data to test it.
