### ISSUE TITLE
Python内置官方客户端中multi_hget的key参数不支持数组类型

### ISSUE THREAD

**Issue by fanrong33** [ideawu/ssdb#1128]
帮助文档中命令描述为

> multi_hget name key1 key2 ...
批量获取 hashmap 中多个 key 对应的权重值.

在Python中使用代码如下：
```python
result = ssdb.request('multi_hget', ['books', keys])
print(result)
````
其中keys是已经获取到的 key 数组。但是打印result是空数组。
也就是说不支持数组类型的参数，但是keys是动态的，不可能一个一个传入😂

望大神告知解决方案，万分感谢

**Comment by ideawu** [comment]
Hi, 用法有些问题。正确的用法是：

```
result = ssdb.request('multi_hget', ['books', k1, k2, k3...])
```

也就是说，keys 要展开，和 'books' 放在一个数组里。

**Comment by fanrong33** [comment]
感谢大神的回复哈，因为我只是简单入门 Python，能否请教下如何将zscan获取的动态 keys 列表展开为 k1, k2, k3 传入呢？
