### ISSUE TITLE
长期运行的ssdb服务重启时间超长问题

### ISSUE THREAD

**Issue by hunterli** [ideawu/ssdb#1130]
ssdb-server 1.9.2长期运行，MANIFEST增加到2.2GB，重启后需要几个小时才能提供服务。发现leveldb有报告bug：[https://github.com/google/leveldb/issues/380](https://github.com/google/leveldb/issues/380)
不知道ssdb什么时候可以升级到leveldb v1.19？

**Comment by ideawu** [comment]
近期将升级到 leveldb v2.0，谢谢你的反馈。

**Comment by ideawu** [comment]
dev 分支已经升级到了 leveldb 1.20，相信你的问题已经解决。 https://github.com/ideawu/ssdb/tree/dev
