### ISSUE TITLE
【主从同步】slave的last_seq已经小于master的min_seq，并且状态是OUT_OF_SYNC，如何能强制进行同步？

### ISSUE THREAD

**Issue by WriteHappy** [ideawu/ssdb#1135]
slave的last_seq已经小于master的min_seq，并且状态是OUT_OF_SYNC，如何能强制进行同步？

在master上，min_seq和 max_seq分别是700  900。
而slave上，last_seq是300， 并且当前状态是OUT_OF_SYNC。
如何操作能恢复成sync的状态呢？

**Comment by ideawu** [comment]
你好，需要停止 slave，删除slave的 meta data 两个目录，然后重启 slave。
