### ISSUE TITLE
ssdb协议的疑问

### ISSUE THREAD

**Issue by seefan** [ideawu/ssdb#1136]
报文
Packet := Block+ '\n'
Block  := Size '\n' Data '\n'
Size   := literal_integer
Data   := size_bytes_of_data

----官方驱动
while(len > 0){
	char *data = (char *)memchr(ptr, '\n', len);
	if(data == NULL){
		break;
	}
	data += 1;
	int num = data - ptr;
	if(num == 1 || (num == 2 && ptr[0] == '\r')){
		// Packet received.
		return OK;
	}
	// Size received
	int size = (int)strtol(ptr, NULL, 10);

	len -= num + size;
	ptr += num + size;
	if(len >= 1 && ptr[0] = '\n'){
		len -= 1;
		ptr += 1;
	}else if(len >= 2 && ptr[0] == '\r' && ptr[1] == '\n'){
		len -= 2;
		ptr += 2;
	}else{
		break;
	}
	// Data received
}

驱动里关于\r的处理部分是为了兼容以\r\n结尾的数据格式么？

**Comment by ideawu** [comment]
是的。一般实现上习惯会兼容"\r\n"和"\n"。

**Comment by seefan** [comment]
明白了
