### ISSUE TITLE
Was 1.9.4 retagged?

### ISSUE THREAD

**Issue by ilovezfs** [ideawu/ssdb#1139]
Currently the SHA-256 checksum for https://github.com/ideawu/ssdb/archive/1.9.4.tar.gz is 6a24efcc906faf07c02c69975861368c1aa8e4adb3770f4bcd3dd610cdcce537.

Originally it was f95005f5284c09b696ef4aee75088679969c9174a0f5506b742ca8ad6f6bb45e. See https://github.com/Homebrew/homebrew-core/pull/11419.

Was 1.9.4 retagged at some point?

**Comment by ideawu** [comment]
Yes, it wa retagged.

**Comment by ilovezfs** [comment]
@ideawu Thanks! Do you recall the reason?

**Comment by ideawu** [comment]
ssdb-cli bug fixed. maybe I should not retagged.

**Comment by ilovezfs** [comment]
@ideawu Thanks for the help! Yes, it would be good to avoid retagging in the future.
