### ISSUE TITLE
能使用Go语言的redis driver 直接取代 ssdb的 driver 吗

### ISSUE THREAD

**Issue by slw2011** [ideawu/ssdb#1146]
根据你的文档"SSDB 支持 Redis 协议和客户端, 所以你可以使用 Redis 的客户端来连接 SSDB 进行操作。"然后官方的Go 语言的ssdb driver是单连接的，能否使用garyburd/redigo/redis 的driver 完全取代 你的gossdb 呢？ 取代之后是否存在一些性能问题呢？ 比如读写没有使用ssdb driver 那么快等？期待您的回答.

**Comment by slw2011** [comment]
看你的blog “终于, SSDB 支持 Redis 协议了! 这表示, 你可以用目前所有成熟的 Redis 客户端来连接 SSDB 服务器, 包括 hiredis, phpredis, redigo 等等.” 说是可以支持，请问读写性能方面没有什么影响吧？

**Comment by ideawu** [comment]
不会有性能的不良影响。

**Comment by slw2011** [comment]
OK，Thanks
