### ISSUE TITLE
Do you have a plan to offer a .net connector

### ISSUE THREAD

**Issue by mrtylerzhou** [ideawu/ssdb#1154]
I'm a .net developer and also want to try ssdb out

**Comment by ideawu** [comment]
Hi, there is a C#.net connector http://ssdb.io/docs/zh_cn/clients.html#cpy

**Comment by mrtylerzhou** [comment]
Thank you so much for your reply,I'll check it out.BTW,please also closed solved issues.Seeing so many opening issues scared users
