### ISSUE TITLE
zremrangebyrank does not handle negative star/end parameter properly

### ISSUE THREAD

**Issue by yurongliao** [ideawu/ssdb#1168]
According to redis doc, -1 means the member with highest score, -2 means member with the second highest score and so forth.

However in ssdb implementation, a negative start/end parameter is converted to an UINT64 interger, which will cause improper consequence.

For example:
```
zadd myzset 1 a 2 b 3 c 4 d 5 e
zremrangebyrank 0 -2 
```
it is expected myzset has only 1 member left.

However, in ssdb myzset becomes empty beucase -1 is converted to a very large UINT64 integer.

**Comment by ideawu** [comment]
Thanks, now it is fixed on dev branch.

**Comment by yurongliao** [comment]
Thanks for your quick reply.
