### ISSUE TITLE
flushdb 的时候 卡住[数据库才开始用,接近于空数据库]

### ISSUE THREAD

**Issue by vmvz** [ideawu/ssdb#1173]
环境 `debian7 x64` + `ssdb 1.9.4` (系统没有跑别的了)

用cli 进行 flushdb的时候, 会卡住. 看log.txt 没有任何错误. 

如图所示, 我应该如何解决这个问题?

- 目前的解决办法只有 重启系统. (重启系统以后, ssdb 可以 restart)
- 只要操作执行 flushdb, ssdb就不可以 stop restart 了

![cli](https://ws1.sinaimg.cn/large/ead4e8c1gy1fmgkujoitzj20er0bv40n.jpg)

![log](https://ws1.sinaimg.cn/large/ead4e8c1gy1fmgl12k4j3j20mh0azq4e.jpg)

**Comment by ideawu** [comment]
在某个版本有flushdb bug，你升级到最新版本吧。

**Comment by vmvz** [comment]
@ideawu 是最新版 1.9.4

**Comment by ideawu** [comment]
1.9.5

**Comment by vmvz** [comment]
@ideawu 我一般看 releases.  1.9.4 [发现没更新]

有了你的提醒,我看了 ChangeLog, 发现 1.9.6 了

(PS 官网 ssdb.io 显示1.9.3)

**Comment by ideawu** [comment]
我更新下官网。

**Comment by vmvz** [comment]
以后我自己多注意 ChangeLog. 

谢谢您
