### ISSUE TITLE
SSDB不支持队列删除指定元素

### ISSUE THREAD

**Issue by lovegnep** [ideawu/ssdb#1178]
从redis迁移到ssdb，但发现不兼容redis的删除列表指定元素这种操作。请问以后会支持吗？

**Comment by ideawu** [comment]
由于ssdb的key命令以类型为命名空间，所以，只给定一个key名字，ssdb无法知道此key对应的数据类型。所以，操作key时，必须指定其类型。

你提到的问题，应使用qclear命令删除列表类型的数据，无法使用del命令。此特性未来不会改变。
