### ISSUE TITLE
奇怪的hash_name

### ISSUE THREAD

**Issue by vmvz** [ideawu/ssdb#1205]
大家有遇到过一个奇怪的 hash_name 吗?
`db.hset('met_sc', '1', '1')`    没有任何错误提示, 但是数据库不会存这个.

(met_sc 有什么特别的吗?)

**Comment by vmvz** [comment]
日志中找到问题了

**Comment by ideawu** [comment]
@vmvz 可以同大家分享一下问题原因和解决方法。

**Comment by vmvz** [comment]
其实问题简单, 就是排查过程有点曲折.

原因: ssdb服务器端不小心开启了自动清空数据库的任务

日志中发现了这个规律(情况)
