### ISSUE TITLE
macOS上有一个宏定义冲突的问题

### ISSUE THREAD

**Issue by cissusnar** [ideawu/ssdb#1208]
想在我的MacOS应用中使用NetworkServer, 本地建立一个server, 而不仅仅使用libssdb, 在Xcode引用头文件的时候, 发现Fdevents中的一个函数定义: 
![image](https://user-images.githubusercontent.com/2087003/38233403-0b69cf34-374d-11e8-8937-3f962106e43c.png)
bool isset(int fd, int flag);
与系统param.h中的宏定义冲突, 而无法编译成功. 
![image](https://user-images.githubusercontent.com/2087003/38233447-2e30eb74-374d-11e8-96a1-20f165f4995b.png)
目前需要修改头文件并加入第一张图中的undefine. 
但这样修改就有悖于直接引用的初衷.

**Comment by ideawu** [comment]
你的修改很好，我不觉得违反了什么规则。

**Comment by cissusnar** [comment]
目前是把ssdb作为submodule来使用, 如果修改ssdb文件的话每次submodule init就需要手动操作, 是否能在主线简单做一下处理, 谢过先
