### ISSUE TITLE
SSDB进程在运行中，但连接时显示Connection closed

### ISSUE THREAD

**Issue by wukainf** [ideawu/ssdb#1209]
一次hget了60000个值，执行完就报错，Connection closed

**Comment by ideawu** [comment]
hget一次只能获取一个值，你用的是hscan吗？

hscan的用法是分段遍历，一次获取合理数量的数据。如果60000个太多，建议一次1000个，或者更少。

**Comment by wukainf** [comment]
hget了60000次，发现问题了，内存不足导致的：）

**Comment by ideawu** [comment]
那么需要根据服务器的实际情况，修改ssdb.conf配置文件里的参数。

**Comment by wukainf** [comment]
好的，我去好好研究一下，谢谢大神的耐心解答：）
