### ISSUE TITLE
Trying to write redis-compatible connector "pipelining"

### ISSUE THREAD

**Issue by unisqu** [ideawu/ssdb#1233]
I'm trying to keep ssdb as redis-compatible as possible with my client side code:
```
$ssdb->batch();
$ssdb->set('a', 1);
$ssdb->get('a');
$ret = $ssdb->exec();
```

I'm using redigo, which is 
```
         c.Send("MULTI")
         c.Send("HSET", "1", "2", "3")
         c.Send("qclear","1") //i have written a function to replace this part to be compatible with redis
         c.Do("EXEC")
```

I know MULTI and EXEC is not recognized by ssdb... so can I assume these line will work as pipelining...

```
//         c.Send("MULTI")
         c.Send("HSET", "1", "2", "3")
         c.Do("qclear","1") //i have written a function to replace this part to be compatible with redis
//         c.Do("EXEC")
```

Will this work? Do you have other creative solution to using redigo to achieve this? Otherwise I'll need to be changing too much code as I've already written a lot of logic to handle Redis->SSDB conversion.

**Comment by ideawu** [comment]
Hi, I will recommend you modify redigo's source code.

We both know MULTI/EXEC is not recognized by ssdb, so modify redigo to handle MULTI/EXEC. When you call redigo(MULTI), create a command buffer, after which, buffer all commands before calling EXEC.

When calling EXEC, send all commands in command buffer, then receive corresponding responses.

**Comment by unisqu** [comment]
Ok thanks!
