### ISSUE TITLE
Do these ram size optimization apply to ssdb?

### ISSUE THREAD

**Issue by streetlist** [ideawu/ssdb#1251]
Came across the following, using hash this way will save memory in redis. Does it work the same with ssdb?
https://redis.io/topics/memory-optimization#using-hashes-to-abstract-a-very-memory-efficient-plain-key-value-store-on-top-of-redis

https://instagram-engineering.com/storing-hundreds-of-millions-of-simple-key-value-pairs-in-redis-1091ae80f74c

**Comment by ideawu** [comment]
ssdb store data on disk, ssdb is already ram optimized.
