### ISSUE TITLE
Embedding SSDB?

### ISSUE THREAD

**Issue by Xeoncross** [ideawu/ssdb#1257]
Is it possible to use SSDB as an in-process / embedded database like SQLite, LedisDB, LevelDB, etc..? I would love to be able to use it inside Go applications. 

Is there any documentation about this? I saw a quick mention about using it on iOS.

**Comment by Xeoncross** [comment]
Doing some more searching I found a partial rewrite of SSDB in Go for embedding (https://github.com/neverlee/emssdb).

**Comment by ideawu** [comment]
Yes, see https://github.com/ideawu/ssdb-ios for a demo. Sorry, no official demo for embedding ssdb in Go.
