### ISSUE TITLE
为什么不支持hash(map) 过期机制

### ISSUE THREAD

**Issue by Trree** [ideawu/ssdb#1263]
- 影响
这样会造成内存和硬盘占用不断增加，需要手动删除数据。

1.  为什么hash(map) 不支持过期机制？
- 是因为正在实现中？
- hash 与KV结构的过期机制在实现上有什么不同吗？
- 查询是否需要更新过期时间？
- 增删改是否需要更新过期时间？

2. 应用层实现的方法？
- 在插入数据的时候增加一个field: expire timestamp，保存过期时间，然后应用层在空闲的时候遍历删除过期的key？

**Comment by alanhamlett** [comment]
Duplicate of #579.
