### ISSUE TITLE
编译失败 t_hash.cpp:288: error: ‘UINT64_MAX’ was not declared in this scope

### ISSUE THREAD

**Issue by lpf4254302** [ideawu/ssdb#1288]
编译失败 t_hash.cpp:288: error: ‘UINT64_MAX’ was not declared in this scope
系统版本
Linux version 2.6.32-696.10.1.el6.x86_64 (mockbuild@c1bl.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Tue Aug 22 18:51:35 UTC 2017

**Comment by lpf4254302** [comment]
#ifndef UINT64_MAX
#define UINT64_MAX (18446744073709551615ULL)
#endif

**Comment by tanjiancheng** [comment]
t_hash.cpp: 在成员函数‘virtual int64_t SSDBImpl::hfix(const Bytes&)’中:
t_hash.cpp:288:44: 错误：‘UINT64_MAX’在此作用域中尚未声明
  HIterator *it = this->hscan(name, "", "", UINT64_MAX);

**Comment by lpf4254302** [comment]
> 怎么解决呢？
在报错的文件中加入
#ifndef UINT64_MAX
#define UINT64_MAX (18446744073709551615ULL)
#endif

**Comment by abellq** [comment]
谢谢，我已经解决了！

**Comment by ideawu** [comment]
fixed.
