### ISSUE TITLE
这个项目应该交给开源社区, 或者Apache这些社团

### ISSUE THREAD

**Issue by Linvas** [ideawu/ssdb#1292]
设计很好, 可是用的人不多, 成不了业界标准. 英文文档支持不够好. 建议可以联系一下Apache这些开源社区, 把项目交过去共同维护

**Comment by abersheeran** [comment]
什么时候业界标准由开发的社区决定了？中国人的开源项目就该受歧视？

**Comment by ideawu** [comment]
这个建议不错. 我会关注其它项目交给Apache社区等开源社区的例子. 目前, 因为ssdb的开源协议和开放源码, 所以它仍然是非常开放的, 欢迎所有人贡献.
