### ISSUE TITLE
Is there any eviction policy at SSDB

### ISSUE THREAD

**Issue by Yahook** [ideawu/ssdb#1305]
Hi,

I want to start using SSDB, but I can't find an answer to this question in your documentation.

What will happen if a free space will be finished? Is there any eviction policy for keys? (LRU, LFU etc.) Can I change it in settings?

Thanks

**Comment by ideawu** [comment]
SSDB store data persistent on storage device(usually hard disk), SSDB will not automatically delete any data unless you invoke *del* command or set expiration on it.

**Comment by douzzi** [comment]
@ideawu when is the deletion of expired data triggered?
