### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by geert-hendrickx-be** [ideawu/ssdb#1306]
Hi,

Would you consider adding IPv6 support to SSDB?
(we prefer to run IPv6-only inside the datacenter.)

#717 suggests having code for this.

**Comment by geert-hendrickx-be** [comment]
Hi again

What would be required to add IPv6 support to SSDB ?

**Comment by ideawu** [comment]
Try https://github.com/ideawu/ssdb/tree/ipv6, this branch is now under development.

**Comment by geert-hendrickx-be** [comment]
Thanks!  Evaluating this.  A few first findings:

- ssdb-cli does not yet support ipv6
- replication only runs over ipv6 if we set an ipv6 address, it does not yet resolve hostnames to ipv6
- like ipv4, allow/deny statements must use a prefix notation (unusual for ipv6), instead of CIDR notation.

These are just minor, the main protocol over IPv6 works.  (We are using Zimbra with SSDB to store session tokens, and this is working over IPv6.)  We'll test further.

**Comment by ideawu** [comment]
Thanks for the feedback. ssdb-cli now supports ipv6.

**Comment by geert-hendrickx-be** [comment]
Nice, thanks!  We can run SSDB in an ipv6-only environment now.
