### ISSUE TITLE
为什么增加一个setx命令，而不是和redis一样 使用 setex命令？ 

### ISSUE THREAD

**Issue by Junjunya1995** [ideawu/ssdb#1307]
ssdb为什么增加一个setx命令，而不是和redis一样 使用 setex命令？ 
setex命令还是比较常用的， 好奇为什么这么设计，会不方便代码层面直接从redis 迁移到ssdb

**Comment by ideawu** [comment]
如果使用 redis 的客户端的话, 仍然是支持 setex 的.
