### ISSUE TITLE
1.9.7 更新到  releases

### ISSUE THREAD

**Issue by vmvz** [ideawu/ssdb#1316]
为了方便检测更新，希望能更新 releases页面

https://github.com/ideawu/ssdb/releases

**Comment by xiuzhifu** [comment]
不是你说，我还以为ssdb只是改bug，还没到能更新发版本的时候，原来版本都写在changelog，打个tag也好呢

**Comment by ideawu** [comment]
谢谢反馈. 以后会尽量和github的版本管理机制统一.
