### ISSUE TITLE
Name conflict with strings.h

### ISSUE THREAD

**Issue by MatthewScholefield** [ideawu/ssdb#1323]
`strings.h` is a standard library header in my system. Since it is such a common name, I think `src/util/strings.h` should be renamed to something more specific like `string_utils.h`. Doing that fixes the compilation for me.

Compiler error:
```
In file included from /usr/include/c++/9/bits/stringfwd.h:40,
                 from /usr/include/c++/9/string:39,
                 from ./strings.h:16,
                 from /usr/include/string.h:431,
                 from log.h:17,
                 from log.cpp:6:
/usr/include/c++/9/bits/memoryfwd.h:63:3: error: template with C linkage
   63 |   template<typename>
      |   ^~~~~~~~
In file included from /usr/include/features.h:450,
                 from /usr/include/inttypes.h:25,
                 from log.h:9,
                 from log.cpp:6:
/usr/include/string.h:28:1: note: ‘extern "C"’ linkage started here
   28 | __BEGIN_DECLS
      | ^~~~~~~~~~~~~
...
```

**Comment by ideawu** [comment]
I don't see any error message related to `strings.h`, will you pasted more detailed compile error message here?

**Comment by MatthewScholefield** [comment]
@ideawu This error doesn't look related, but it is. Here's what happens:

 - ssdb/src/util/**log.h**:14: `#include <string.h>`
 - **/usr/include/string.h**:431: `#include <strings.h>`

Now, the standard library is expecting `#include <strings.h>` to include `/usr/include/strings.h` (which is included within `extern "C" { ...`), but instead it includes the local `./strings.h` file from the `util` folder. Understandably, this causes strange compiler errors.

I have verified that renaming all references of `src/util/strings.h` to some other name like `src/util/string_utils.h` fixes compilation.

**Comment by ideawu** [comment]
ok, I will fix it by renaming `strings.h`

**Comment by ideawu** [comment]
fixed and merged https://github.com/ideawu/ssdb/pull/1324

**Comment by MatthewScholefield** [comment]
Thanks!
