### ISSUE TITLE
deps 里 jemalloc包 导入的 版本不对

### ISSUE THREAD

**Issue by earl86** [ideawu/ssdb#1328]
jemalloc-4.1.0.tar.bz2
应该导入 这个tar.bz2 后缀的包里的文件 编译才不会报错。
现在ssdb导入的是.zip或者tar.gz的 source code包，导致按照文档编译会报错。

**Comment by ideawu** [comment]
多谢反馈, 能否把你的出错信息发出来?

**Comment by earl86** [comment]
编译系统:
[root@vhost1 ssdb]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

编译时报以下错误
##### building jemalloc... #####
autoconf
autoconf: error: no input file
Error 0 in autoconf
build.sh: line 95: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
##### building jemalloc finished #####

t/ssdb-master/deps/snappy-1.1.0/.libs/libsnappy.a" "/root/ssdb-master/deps/jemalloc-4.1.0/lib/libjemalloc.a" -pthread -lrt client/SSDB_impl.o
g++: error: /root/ssdb-master/deps/jemalloc-4.1.0/lib/libjemalloc.a: No such file or directory
make[1]: *** [all] Error 1
make[1]: Leaving directory `/root/ssdb-master/src'
make: *** [all] Error 2
[root@vhost1 ssdb-master]# 

按照文档直接 进入 jemalloc-4.1.0包 编译 报下面的 错.
[root@vhost1 jemalloc-4.1.0]# pwd
/root/ssdb-master/deps/jemalloc-4.1.0
[root@vhost1 jemalloc-4.1.0]# autoreconf --force --install
autoreconf: 'configure.ac' or 'configure.in' is required
[root@vhost1 jemalloc-4.1.0]# 
[root@vhost1 jemalloc-4.1.0]# ./autogen.sh 
autoconf
autoconf: error: no input file
Error 0 in autoconf


把 依赖包替换为 https://github.com/jemalloc/jemalloc/releases/download/4.5.0/jemalloc-4.5.0.tar.bz2 或 https://github.com/jemalloc/jemalloc/releases/download/4.1.0/jemalloc-4.1.0.tar.bz2
这几个  tar.bz2后缀的文件 解压文件后 就可以 正常编译了

[root@vhost1 jemalloc-4.5.0]# ls
autogen.sh  bin  build-aux  ChangeLog  config.stamp.in  configure  configure.ac  COPYING  coverage.sh  doc  include  INSTALL  jemalloc.pc.in  Makefile.in  msvc  README  scripts  src  test  VERSION
[root@vhost1 jemalloc-4.1.0]# ls
autogen.sh  bin  ChangeLog  COPYING  include  INSTALL  jemalloc.pc.in  Makefile.in  msvc  README  src  test
多了 configure  configure.ac 等几个文件

**Comment by earl86** [comment]
jemalloc-4.5.0的包我试了也可以 编译成功不过要修改下 文件夹名为jemalloc-4.1.0 或者 改下编译的配置文件。

**Comment by earl86** [comment]
找到 问题了，我在windows下下载的包，zip里的文件不全，包不完整。在linux下解压 未报错。
