### ISSUE TITLE
multivalued password to allow rolling password migrations

### ISSUE THREAD

**Issue by geert-hendrickx-be** [ideawu/ssdb#1342]
Hi

Currently a single password can optionally be set in the server.  If you ever want to change this password, it needs to be changed on the server and all clients at the same time, causing downtime of the complete application using ssdb even if it is high-available, because there can only be a single password.

Would it be possible to make the `server.auth` config field multi-valued (like `server.allow` and `server.deny`), so we can set multiple passwords, "old" and "new", to allow for rolling password updates?  Authentication would succeed when any of these passwords match.

**Comment by ideawu** [comment]
Hi, multiple auth password config is now supported on master branch.

**Comment by geert-hendrickx-be** [comment]
Excellent, thanks!
