### ISSUE TITLE
SSDB数据导出问题

### ISSUE THREAD

**Issue by pengjianbo** [ideawu/ssdb#1352]
你好，请问有什么办法可以将ssdb的ldb文件数据直接读取出来（不通过ssdb client，因为生产环境上ssdb数据量过大如果通过client将数据全部导出的话效率太低了）。最近看到可以通过[ldbdump](https://github.com/golang/leveldb/tree/master/cmd/ldbdump)方式将单ldb文件dump出来，但是zset的name和key没有找到分割的规则算法。请大佬指教。

**Comment by ideawu** [comment]
有一种运维手段导出数据会比较快, 需要停止服务:

1. 停止 ssdb-server 进程
2. 拷贝 data 目录
