### ISSUE TITLE
ssdb dbsize and actual size on drive

### ISSUE THREAD

**Issue by jurepetrovic** [ideawu/ssdb#1363]
Hello Gentlemen, 

we have reported dbsize around 11G, whereas the space on the drive being used is around 90G. 
What do you suggest doing in this case? Can we reduce this to actual db size? 

Thanks, 
Jure

**Comment by ideawu** [comment]
invoke `compact` through ssdb-cli when server is not busy would help reduce disk usage.

**Comment by jurepetrovic** [comment]
Ok, thanks, will try this and let you know.
