### ISSUE TITLE
hashmap中name有最大个数限制吗？

### ISSUE THREAD

**Issue by wo4zhuzi** [ideawu/ssdb#1383]
您好 @ideawu ,我在文档中看到单个hash 中元素的数量为 9,223,372,036,854,775,807

![image](https://user-images.githubusercontent.com/20334885/97108469-b2179800-1708-11eb-9790-64157ad4b9e0.png)

但我想知道hashmap中的name有没有数量限制？如果有，最大存储数量是多少？

**Comment by ideawu** [comment]
没有限制.

**Comment by wo4zhuzi** [comment]
> 没有限制.

好的，感谢解答。
