### ISSUE TITLE
主从模式/主主模式

### ISSUE THREAD

**Issue by carr123** [ideawu/ssdb#1384]
您好，请问2台服务器主从模式同步和主主模式同步有什么区别 ?
各自用在什么样的场景， 有什么优劣,  如何选择 ?
谢谢!

**Comment by ideawu** [comment]
一般来说, 用主从模式简单一些, 大部分场景都是用主从模式. 主主模式的优点的是两台机器都可以写入, 但需要用户自己做 key 路由(hash), 不要在两台机器上写同一个 key.

**Comment by carr123** [comment]
您好，我想用2台服务器做主主模式相互同步。 前面放个twemproxy, 这样twemproxy可以把同一个key 映射到固定的某一台机器上去，就不存在两台机器上写同一个 key的时候了。
但是twemproxy 为了提高访问性能，对多个客户端的请求进行了合并，形成pipline后发给后端的 redis/ssdb， 
我貌似没看到ssdb支持pipeline访问。请问还能用twemproxy挡在ssdb前面做key分片么 ？
