### ISSUE TITLE
功能相关：请问是否可能新增类似redis的randomkey随机返回一个key/name的功能？

### ISSUE THREAD

**Issue by lgs3137** [ideawu/ssdb#1387]
请问是否可能新增类似redis的randomkey随机返回一个key/name的功能？
或者该如何实现从hash表中随机返回一个name呢？
目前hashname规则是32位guid

**Comment by lgs3137** [comment]
如果只能放业务中实现的话，是不是得自己随机生成32位以内的字符串作为起始name，然后用hlist命令返回1条，为空就继续？感觉这样好傻。。。
`
hlist('05255', '', 1)
`

**Comment by ideawu** [comment]
你所想到的方案就是最好的方案.

**Comment by lgs3137** [comment]
好的~
感谢~
