### ISSUE TITLE
compact相关问题

### ISSUE THREAD

**Issue by Qiancj0605** [ideawu/ssdb#1388]
@ideawu  你好，请教一下：
1、这种使用场景(线下提前把数据准备好，然后直接放到线上SSDB加载，之后SSDB只提供读服务)是否会执行compact？如果执行的话什么场景会执行？
2、compact机制可以简单介绍一下吗？

**Comment by ideawu** [comment]
对于你这种场景, 推荐在线上部署完毕后, 通过 ssdb-cli 手动执行 `compact` 命令.

对于只有读操作没有写操作的场景, 依然有可能触发 ssdb 所使用的 leveldb 库的 compaction 机制, 这方面网上有不少分析文章, 你可以找来看看.

**Comment by Qiancj0605** [comment]
对于第1种描述，我是线下写完SSDB，然后dump，之后直接线上加载的。应该线下dump过程中，已经compact了吧，线上加载完应该不需要compact了吧？

**Comment by Qiancj0605** [comment]
@ideawu 有个compact相关的问题再请教一下：
场景：我自己写了一个脚本，通过requst发布compact的命令。当SSDB服务正在执行compact时，突然通过“-s restart”重启服务，这时候SSDB服务几乎打满所有cpu，请问这是什么原因？多谢
