### ISSUE TITLE
性能咨询

### ISSUE THREAD

**Issue by Qiancj0605** [ideawu/ssdb#1391]
环境：
1、大约3千万条数据，几乎不存在局部热点数据；
2、cache_size和write_buffer_size配置最小值，目的就是减少内存，尽可能访问SSDB（硬盘是SSD的）
3、都是访问本地SSDB
问题：
一次请求大约会有200次访问SSDB，最开始方案是这200次请求是串行访问SSDB，发现耗时会出现几百毫秒的情况；后来使用multi_get(每次key的个数试过10，30，50，70等)，发现耗时依然会有几百毫秒的情况。后来发现multi_get的源码如截图，是串行访问SSDB的，这样的话使用multi_get优化肯定是有限的。请问multi_get会考虑并行化吗？像我这种场景有合适的解决方案吗？（期望这200次请求访问SSDB的耗时在20ms左右）
@ideawu  麻烦解答一下，非常感谢。
![image](https://user-images.githubusercontent.com/34846384/102708216-5159a580-42dc-11eb-94a8-ceaed0c44e27.png)

**Comment by ideawu** [comment]
SSDB 内部执行一个命令(包含带多个参数的 multi_xxx 类命令), 只使用一个线程. 执行多个命令可能使用多个线程. 所以, 

1. 如果你关注延迟, 那边需要在客户端自己并发的请求, 每一个并发只请求一个 key. 一般可以并发 100 个连接(每个连接使用一个线程, 或者编程语言支持协程).
2. 如果关注总体吞吐量的话, 正常并发使用, 每一个并发(线程或者协程)使用单独的连接.

**Comment by Qiancj0605** [comment]
好的，多谢
