### ISSUE TITLE
Max key length

### ISSUE THREAD

**Issue by rock59** [ideawu/ssdb#1393]
Is it possible to increase Max key length and how to do it safely?

**Comment by ideawu** [comment]
There is no way to increase max key length, you may convert your key to md5sum, and use md5sum instead of the original key.

**Comment by rock59** [comment]
There is no key length limit in LevelDB. Keys are arbitrary byte arrays of any length. Why ssdb enforce 200 bytes max key length?  Underlying network layer is the problem ?
