### ISSUE TITLE
请问目前SSDB对标的redis的版本号是多少?

### ISSUE THREAD

**Issue by ayanmw** [ideawu/ssdb#1398]
当前ssdb版本: 1.9.9
代码参考的redis版本应该是多少: ????   (目前最新redis版本号 6.0.6)

如果设计上是不再兼容redis, 或许问题就是这样的

问 ssdb 是基于 redis 那个版本的?
答 ssdb 和 redis 没有任何关系, 仅仅是在设计上参考了部分设计.

**Comment by ideawu** [comment]
1. ssdb 支持大部分 redis 命令(有部分不支持) http://ssdb.io/docs/zh_cn/redis-to-ssdb.html
2. ssdb 新加了部分 redis 没有的命令 http://ssdb.io/docs/zh_cn/commands/index.html

因为 redis 命令的版本差异比较罕见, 所以 ssdb 在兼容 redis 时, 不限定特定版本.
