### ISSUE TITLE
集群问题

### ISSUE THREAD

**Issue by carr123** [ideawu/ssdb#1401]
有没有计划做分布式，高可用，负载均衡的ssdb 集群哈？

**Comment by ideawu** [comment]
分布式系统除了拥有大量优点, 其缺点也比较明显, 如使用门坎高, 简单问题复杂化, 要求使用者积极配合(换用新的SDK, 新的接口, 系统重构等), 使用者必须付出大量思想和金钱成本等等, 因此, 分布式数据库系统的发展方向主要是服务化, 专属化. ssdb 有计划开发分布式功能.

你可以在这里和大家分享一下你所遇到的问题, 也许能得到低成本的高效解决方案.

**Comment by carr123** [comment]
我想要能持久化存储，读写性能可以扩展的redis变种。在客户端眼里，最好是当作单机版redis使用。
而且最好是一致性的，有次查询在一个ssdb节点写key,立即在另一个主-主同步节点读，没读到数据，后来就改成只在一个节点读写了。但是这样对单个节点的读写压力太大。  在应用层分片又比较麻烦。
其实我对单机读写的性能要求不是非常高，比redis慢一点只要延迟不太大就达到缓存的目的了，只要能横向扩展性能问题也就不是事了。

**Comment by ideawu** [comment]
你的需求和一些ssdb的用户的需求类似, 他们使用 twemproxy 作为多个 ssdb 实例的接入层, 客户端连接的是 twemproxy. twemproxy 在某种程度上可以看作是"单机redis节点".

**Comment by carr123** [comment]
谢谢给的建议。 祝你早日开发出宇宙最强ssdb, good luck !
