### ISSUE TITLE
Is it a good idea to use ssdb as file storage?

### ISSUE THREAD

**Issue by link89** [ideawu/ssdb#1424]
I just work on a legacy project which use ssdb as file storage. I am not sure if ssdb is designed for such use case. Is there any potential risk to use it this way?

**Comment by alanhamlett** [comment]
Files are the same as any other data, but you should know the ssdb data files have [been known to become corrupted](https://github.com/ideawu/ssdb/issues?q=corrupted) so you should only store cache data in ssdb. Never store data in ssdb that you can't reproduce.
