### ISSUE TITLE
ssdb仍然使用了大量的内存而不是限制在设置的cache_size?

### ISSUE THREAD

**Issue by zhenchuan** [ideawu/ssdb#230]
测试了3kw的数据,发现内存占用很多, 这是执行**_[get]**_操作时的内存占用情况
(执行set操作时虚拟内存的大小约等于实际ldb文件的大小,但是内存没有增加太多)
配置使用的是默认配置,

想了解为何会占用这么多的内存?而不是配置的cache_size?

默认配置:
leveldb:
        # in MB
        cache_size: 500
        # in KB
        block_size: 32
        # in MB
        write_buffer_size: 64
        # in MB
        compaction_speed: 1000
        # yes|no
        compression: no

这是执行[get]操作时的内存占用情况
top:
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  DATA COMMAND  
19380 root      25   0 4652m 3.4g 3.3g R 100.2 10.7  39:17.44 ssdb-server  
19402 root      15   0 7757m 7.5g 1092 R 59.7 24.0  13:44.90 ssdb-bench

**Comment by ErenNo1** [comment]
The sorted table generated from a log file is placed in a special young level (also called level-0). When the number of young files exceeds a certain threshold (currently four), all of the young files are merged together 

http://htmlpreview.github.io/?https://raw.githubusercontent.com/google/leveldb/master/doc/impl.html


@ideawu level-0的文件最多是64个有问题吧! 上面文章提到levle-0 文件个数通常是大于4个就会触发compaction

疑惑,求解~

**Comment by hongliuliao** [comment]
> The sorted table generated from a log file is placed in a special young level (also called level-0). When the number of young files exceeds a certain threshold (currently four), all of the young files are merged together
> 
> http://htmlpreview.github.io/?https://raw.githubusercontent.com/google/leveldb/master/doc/impl.html
> 
> @ideawu level-0的文件最多是64个有问题吧! 上面文章提到levle-0 文件个数通常是大于4个就会触发compaction
> 
> 疑惑,求解~

是4个触发compaction, 但是如果写入量比较大的话, 会出现compaction速度小于写入速度的情况, 这个时候Leveldb会先尝试写限速,如果还是限制不住, 就会触发停写, 触发停写的标准是64个L0
