### ISSUE TITLE
/usr/local/ssdb/log.txt，时间乱序排列？

### ISSUE THREAD

**Issue by doxpix** [ideawu/ssdb#324]
/usr/local/ssdb/log.txt，这个日志文件不是按时间往后追加的吗？看起来时间怎么是乱序的。。。

**Comment by YongMan** [comment]
多个线程写日志如果没有加锁，是否会导致某一条日志没写完又插入另一条，导致日志格式不合法？

**Comment by ideawu** [comment]
@YongMan 有加锁, 只有产生乱序的可能, 不会出现两条log混合的问题.
