### ISSUE TITLE
可以提供集合的交集，并集操作吗？与redis一样的

### ISSUE THREAD

**Issue by gqkang** [ideawu/ssdb#494]

**Comment by Donghui0** [comment]
zkeys A '' '' '' 100    列出 A 集合的所有元素 ,看代码的处理方式是迭代去比较查找. 数据量很大的情况下应该hold不住吧... 否则取交集这个功能很好实现. 您也是考虑到这点 所以不提供吧? @ideawu

**Comment by ideawu** [comment]
数据量大, 在服务器端做这些操作照样hold不住.

2015-03-02 18:34 GMT+08:00 Donghui0 <notifications@github.com>:
