### ISSUE TITLE
about size limitation...

### ISSUE THREAD

**Issue by mcarbonneaux** [ideawu/ssdb#519]
you indicate limitation in http://ssdb.io/docs/limit.html
they are limited by leveldb lib or you network server implementation ?

the limit that blocking me is the max value size....

**Comment by cronacronis** [comment]
What about 
```
Max value length 	31MB
Max request/response size 	31MB
```
Where I can change them? I would like to store bigger keys sometime. Is there a way?

**Comment by ideawu** [comment]
It is here: https://github.com/ideawu/ssdb/blob/master/src/net/link.cpp#L16

For some version of ssdb, the limit is 128MB, the link.cpp defines it.

**Comment by cronacronis** [comment]
@ideawu would you mind to mention which versions?

**Comment by ideawu** [comment]
@cronacronis see the changelog https://github.com/ideawu/ssdb/blob/master/ChangeLog#L12
