### ISSUE TITLE
Can you make it <SSDB.h> for cpp as a shared dynamic module or something?

### ISSUE THREAD

**Issue by ghost** [ideawu/ssdb#580]
can you "make install" so can use SSDB as a cpp system module so can just add <SSDB.h>

I'm new to cpp so i'm asking for this requirement.

**Comment by hwongcom** [comment]
i am getting this error below

/usr/bin/ld: libssdb-client.a(link.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
libssdb-client.a: could not read symbols: Bad value

trying to run inside cpoll_cppsp

**Comment by hwongcom** [comment]
i did recompile with fPIC but still doesn't work. can you provide some redhat rpm to ssdb so can implement inside c++ program?

**Comment by hwongcom** [comment]
i'm trying to enroll ssdb backend into techempower public benchmark
