### ISSUE TITLE
经常 Connection Lost，扛不住高并发？

### ISSUE THREAD

**Issue by CaledoniaProject** [ideawu/ssdb#587]
请教一下。。这个是啥原因。。特别频繁，并发还不到100就这样了。。

PHP message: PHP Fatal error:  Uncaught exception 'SSDBException' with message 'Connection lost' in /srv/XXX/SSDB.php:714
Stack trace:
#0 /srv/XXX/SSDB.php(521): SSDB->recv()
#1 /srv/XXX/SSDB.php(161): SSDB->recv_resp('get')
#2 /srv/XXX/SSDB.php(303): SSDB->__call('get', Array)
#3 /srv/XXX/xxxx.php(14): SSDB->get('XXXX...')
#4 {main}
  thrown in /srv/XXXX/SSDB.php on line 714" while reading response header from upstream,

**Comment by ideawu** [comment]
把超时时间调大一点.

**Comment by 6api** [comment]
生产环境中运行了几十天，出现N次这种情况
TIMEOUT调大也无效
改用REDIS CLIENT，暂时解决

**Comment by sunyc** [comment]
ulimit 的open files 调高点

**Comment by CaledoniaProject** [comment]
已放弃。。为了避免别人发邮件问我，关闭这个issue

**Comment by ideawu** [comment]
最近 ssdb 修复了一个 log 相关的 bug, 这个 bug 会导致服务阻塞数秒. 如果你的日志级别是 debug, 有可能是此 bug 导致. 可以升级 ssdb 到最新.
