### ISSUE TITLE
ssdb cpp client 没有处理SIGPIPE

### ISSUE THREAD

**Issue by ErenNo1** [ideawu/ssdb#598]
服务器关闭时，client会直接崩溃（不是必然，偶尔会status not
 ok），SIGPIPE的处理应该在哪处理比较好？是在client 构造函数，还是在应用 ssdb client的启动代码里处理？

**Comment by ideawu** [comment]
谢谢反馈, ssdb cpp client 将会处理 SIGPIPE.

**Comment by ideawu** [comment]
你好, 已经更新代码. 你可以重新运行一下你的测试用例.

**Comment by ErenNo1** [comment]
ok了
