### ISSUE TITLE
ssdb native protocol parser

### ISSUE THREAD

**Issue by hit9** [ideawu/ssdb#601]
Hi, I have created ssdb protocol parser for python and node.js, they are very fast.

- Python port: https://github.com/hit9/spp_py
- Nodejs port: https://github.com/hit9/spp_node

Just like [hiredis-node](https://github.com/redis/hiredis-node) to redis and [hiredis-py](https://github.com/redis/hiredis-py) to redis.

Could you add them somewhere in ssdb's docs?

**Comment by ideawu** [comment]
Hi, can you add some demo that actually interact with a ssdb-server instance?

**Comment by hit9** [comment]
They are just protocol parsers, used in ssdb client libs: [ssdb.py](https://github.com/hit9/ssdb.py) and (node-ssdb)(https://github.com/eleme/node-ssdb). They can be demos (at some point.. :)).

**Comment by ideawu** [comment]
Hi, since spp_py is the base of ssdb.py project, I think you should describe spp_py in detail in [ssdb.py](https://github.com/hit9/ssdb.py) project, and give a more meaningful description about ssdb.py in http://ssdb.io/docs/clients.html#python

**Comment by hit9** [comment]
@ideawu Ok. Thanks.
