### ISSUE TITLE
php-pecl-redis: "link parse error, delete link" fills up logs

### ISSUE THREAD

**Issue by neverloop** [ideawu/ssdb#608]
I've got lots of lines like this in the ssdb.log:

`2015-02-21 13:47:03.696 [WARN ] server.cpp(245): fd: 19, link parse error, delete link`

Even a very simple session (from `php-pecl-redis` tcpdump) produces this error:

```
telnet server 8888
Trying x.x.x.x...
Connected to x.x.x.x.
Escape character is '^]'.
*2
$3
GET
$3
FOO
$-1
QUIT
Connection closed by foreign host.
```

After searching the code (`src/net/link.cpp`) I figured out that the `QUIT` command (used by `php-pecl-redis 2.2.5-1.el7`) produces this error. I'm not a programmer so I'm not able to fix this issue (from `link.cpp` it seems that there is no designated way to handle the QUIT command or to close the link without an error).

**Comment by neverloop** [comment]
ok, I've patched php-pecl-redis to only use the newer RESP protocol for the QUIT-cmd as well. Now ssdb does not produce any errors anymore.

```
--- redis-2.2.5/library.c.orig	2014-03-19 16:41:37.000000000 +0100
+++ redis-2.2.5/library.c	2015-02-21 20:58:30.453621088 +0100
@@ -1232,7 +1232,7 @@
     redis_sock->dbNumber = 0;
     if (redis_sock->stream != NULL) {
 			if (!redis_sock->persistent) {
-				redis_sock_write(redis_sock, "QUIT" _NL, sizeof("QUIT" _NL) - 1 TSRMLS_CC);
+				redis_sock_write(redis_sock, "*1" _NL "$4" _NL "QUIT" _NL, sizeof("*1" _NL "$4" _NL "QUIT" _NL) - 1 TSRMLS_CC);
 			}
 
 			redis_sock->status = REDIS_SOCK_STATUS_DISCONNECTED;
```

**Comment by ideawu** [comment]
Hi, @neverloop, yes, ssdb ONLY support the newer redis protocol. You are doing the right thing to patch php-pecl-redis!
