### ISSUE TITLE
每隔一段时间读写异常高

### ISSUE THREAD

**Issue by alexzZhe** [ideawu/ssdb#611]
单实例，正常情况下，读是十多M/S，写是几百K/S，每隔一段时间读写就会达到三四十M/S

**Comment by ideawu** [comment]
你好, 因为 leveldb 的 Log Structured Merge Tree, leveldb 会隔一段时间进行 merge(compaction) 操作, 这时会有大量的磁盘 io. 这是预期中的现象.

**Comment by ErenNo1** [comment]
配置文件可以配置compact的速度，以及是否开启compact，
是否能够配置让compact在固定时间进行，或者避开访问高峰期？

**Comment by ideawu** [comment]
你好, 无法控制 compact 的时间.

**Comment by alexzZhe** [comment]
数据量几十G上百G的情况，使用rocksdb 引擎性能会不会更佳。

**Comment by ideawu** [comment]
你可以试试 https://github.com/ideawu/ssdb-rocks
