### ISSUE TITLE
ssdb-cli export超出100%

### ISSUE THREAD

**Issue by size-of-world** [ideawu/ssdb#613]
在ssdb-cli中，使用export命令，导出的进度会超出100%，不知道什么时候终止，不知道数据是否已经导出完毕

**Comment by ideawu** [comment]
导出过程有导出的数据量输出, 导出完毕后会有明确提示.

2015-03-02 17:35 GMT+08:00 Wang Xinming <notifications@github.com>:

**Comment by size-of-world** [comment]
我这边在使用时，碰到导出进度多于100%，到达105%，然后再往上增加

**Comment by size-of-world** [comment]
使用小规模数据测试了下，确实会正常导出，但是显示的百分比跟真正的进度无关

**Comment by ideawu** [comment]
补充说明, ssdb-cli 的 export 导出, 这个进度数只做参考, 受压缩的影响比较大, 即使不压缩, 也受数据的组织方式的影响.
