### ISSUE TITLE
clear后data下还有数据

### ISSUE THREAD

**Issue by 6api** [ideawu/ssdb#620]
测试加了一些HASH和LIST，然后HCLEAR+QCLEAR
可是ssdb的data目录下还有些文件

只有FLUSHDB才能把这些清了，有什么命令可以清除？

total 36M
-rw-r--r-- 1 root root  17M 2015-03-07 10:02 000306.ldb
-rw-r--r-- 1 root root 4.0M 2015-03-07 10:04 000307.log
-rw-r--r-- 1 root root  15M 2015-03-07 10:04 000308.ldb
-rw-r--r-- 1 root root   16 2015-03-07 06:09 CURRENT
-rw-r--r-- 1 root root    0 2015-03-07 04:10 LOCK
-rw-r--r-- 1 root root  69K 2015-03-07 10:04 LOG
-rw-r--r-- 1 root root  419 2015-03-07 06:08 LOG.old
-rw-r--r-- 1 root root  64K 2015-03-07 10:04 MANIFEST-000012

**Comment by ideawu** [comment]
除了数据本身, 还有一些meta数据, 所以, del/hcear/zclear/qclear 清除所有数据后, 硬盘上还会有一些数据. 设计如此, 正常的.

如果你比较在意, 或者确实想删除所有数据, 请 kill 掉进程后, rm -rf data 目录即可.
