### ISSUE TITLE
请问SSDB 1.6.8.8 使用hscan 出来的数据并不是有序的是吧,详情见内文

### ISSUE THREAD

**Issue by zc19860419** [ideawu/ssdb#622]
在使用Golang 对SSDB 1.6.8.8 进行使用的时候,在代码中采取了分页获取hashmap 数据的方法,也即使用上一次迭代中的最末尾键作为下一次迭代的 起始键 startkey: 
func Hscan(hashname string) ([]string, error) {
	cnt, _ := db.HSize(hashname)\
        ...
	for ind < cnt {
		resp, err := db.HScan(hashname, startkey, "", size)
                ...
		startkey = k
	}
	return list, err
}
但是发现每次得到的结果都不一致,后来打印发现得到的keys 集合其实是完全无序的,无论是数字还是字符串排序. 请问是否存在这样的问题?

**Comment by 6api** [comment]
hlist吧

**Comment by ideawu** [comment]
你好, 是有序的, 是按 strcmp 来排序.

**Comment by zc19860419** [comment]
@ideawu  恩 从控制台输出看都是有序的,有可能是我们自己的go写的问题或者驱动问题,目前只有hscan是无序的,hlist是有序的

**Comment by ideawu** [comment]
提醒一句, go 的 map 数据结构是无序的.
