### ISSUE TITLE
SSDB logo

### ISSUE THREAD

**Issue by topilski** [ideawu/ssdb#623]
Please create logo icon for SSDB database.

**Comment by ideawu** [comment]
Thanks for your advice!

**Comment by topilski** [comment]
Also, if you have some free time please review [FastoRedis](https://github.com/fasto/fastoredis), we implemented SSDB support. But may be you have some interesting features for SSDB and FastoRedis solutions.

**Comment by topilski** [comment]
ping

**Comment by ideawu** [comment]
Hi, I just added SSDB logo: https://raw.githubusercontent.com/ideawu/ssdb/master/docs/logo.png

**Comment by topilski** [comment]
Done
