### ISSUE TITLE
可否真正区分qrange和qslice？

### ISSUE THREAD

**Issue by cuixin** [ideawu/ssdb#630]
目前在使用过程中感觉qrange和qslice几乎一样，没什么区别，建议将qslice直接返回数据并且删除数据。

或者重新增加一个指令，或者叫qclean？

需要有这样的场景，就是直接把数据删除并返回结果的，可否加个todo?

**Comment by ideawu** [comment]
你好, 对于特定的简单的技术问题, 请不要太重感觉, 你甚至不需要感觉. 它们的区别在文档中已经非常明确.
