### ISSUE TITLE
support redis 3.0 protocol?

### ISSUE THREAD

**Issue by hubply** [ideawu/ssdb#636]
I have some question, Redis 3.0 will release stable version on end of March 2015 in addition new "cluster" feature  ,SSDB will develop and suppot on Redis 3.0 on future for long term?

**Comment by ideawu** [comment]
Hi, "cluster" is far more than network protocol. SSDB will develop its own cluster feature.

**Comment by hubply** [comment]
thank you for reply answer,keeping forward ideawu
