### ISSUE TITLE
关于 write_buffer_size 的问题

### ISSUE THREAD

**Issue by 1Feng** [ideawu/ssdb#641]
假如一条请求A被放进了write_buffer里, write_buffer_size未满,之后如果有一条针对A记录的读请求进来,是否会先读取write_buffer?  如果不读取write_buffer,是否就出现了数据延迟的情况呢?
目前使用中遇到了数据延迟的情况,怀疑和这个有关,不知对不对?
如果是的话,write_buffer_size设置为0即可?

**Comment by ideawu** [comment]
你可以找来 leveldb 的原理文章看看, 这里有一篇 http://www.cnblogs.com/haippy/archive/2011/12/04/2276064.html

**Comment by ErenNo1** [comment]
write_buffer其实就是Memtable的话,理应不会有延迟发生啊~
我是在写操作返回之后再读的, 不知道为什么会有数据延迟. 很奇怪.

**Comment by fajin** [comment]
同问类似问题，也看了levedb的原理，增大write_buffer_size         的设置是否能有效的提升读性能？比如加大到1024？ @ideawu

**Comment by ideawu** [comment]
write_buffer_size 直接影响写性能, 不直接影响读性能. 加大 cache_size 一般可以提高读性能.
