### ISSUE TITLE
SSDB是否支持前缀查询？

### ISSUE THREAD

**Issue by shinebay** [ideawu/ssdb#654]
业务中一个最普通的案例就是用户在论坛中发表了哪些帖子，用SSDB将用户uid和对应的帖子id存下来：
user3_15,
user3_21,
user8_43,
user8_48,
user8_55,
user9_27,
user9_34
现在我想得到user8发表的所有帖子，是否支持$ssdb->get(' user8_* ')这样的通配符查询，这样就将user8_前缀的值全部get出来？如果不行，该怎样解决这种业务场景？

**Comment by ideawu** [comment]
支持, 请查看 scan 命令的文档和示例.

你可以在 ssdb-cli 执行下面的命令试试:

```
scan user8_ "" 10
```

**Comment by tomener** [comment]
不错
