### ISSUE TITLE
运行php使用示例时出错

### ISSUE THREAD

**Issue by MarginC** [ideawu/ssdb#668]
require_once('SSDB.php');
$ssdb = new SimpleSSDB('127.0.0.1', 8888);
$resp = $ssdb->set('key', '123');
$resp = $ssdb->get('key');
echo $resp;

错误提示：
Fatal error: Uncaught exception 'SSDBException' with message '13: Permission denied' in /usr/local/ssdb/api/php/SSDB.php:78

$this->sock = @stream_socket_client("$host:$port", $errno, $errstr, $timeout_f);
socket连接失败了。

但是服务是跑起来的：
root@ ssdb]#netstat -anp | grep ssdb
tcp        0      0 127.0.0.1:8888              0.0.0.0:*                   LISTEN      8553/
./ssdb-server  tcp        0      0 127.0.0.1:8888              127.0.0.1:49154             ESTABLISHED 8553/
./ssdb-server

**Comment by ideawu** [comment]
应该是你的服务器设置问题. 你可以用 root 账号来跑 php 示例.

**Comment by VenDevel** [comment]
朋友。你这个问题有没有解决了。我也遇到这个问题

**Comment by ideawu** [comment]
见: https://github.com/ideawu/ssdb/issues/1011

```
setsebool httpd_can_network_connect=1
```
