### ISSUE TITLE
数据持久化策略

### ISSUE THREAD

**Issue by lzn993** [ideawu/ssdb#670]
您好，请问SSDB把内存数据持久化到数据库是怎样的策略，例如：是实时写入到磁盘，还是定期写入磁盘（时间间隔是多少）。

**Comment by ideawu** [comment]
你需要了解 leveldb 引擎的原理, 可以在网上找文章, 或者阅读 leveldb 的源码, 这里的一篇文章推荐 http://www.ideawu.net/blog/archives/688.html
