### ISSUE TITLE
使用ssdb进行文本倒排索引存储

### ISSUE THREAD

**Issue by ErenNo1** [ideawu/ssdb#682]
Hi,
之前在使用ssdb进行文本处理的倒排表的存储, 目前写入和读取的性能都非常不乐观.
倒排存储方式:

```
word1 : doc_id1, doc_id2, .....do_idN
word2: ......
```

在ssdb中每个word都是一个hashtable,然后将doc_id 以及word在文章中的权重作为key,value进行存放

word 的大概偶200W-400W个, 倒排索引的长度(hashtable的size)主要集中在百,千量级别

爬虫每抓取一篇doc,在分词之后,都会更新倒排表,将doc_id插入相应倒排索引(hash_table)
同时会有请求查询doc的倒排索引,每组查询都会有几十到上百次的倒排索引查询(hgetall)

目前ssdb里存储了60w左右的doc

目前的情况是, 磁盘经常变的读写异常缓慢,磁盘IO达到瓶颈( 2cpu + 4G RAM + SSD)

iostat -x 显示如下

    Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await      svctm  %util
    xvdf              0.00     0.00  144.00   12.00  2568.00   488.00    39.18    16.64  108.41  106.89  126.67   6.41 100.00
    Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
    xvdf              0.00     0.00  134.00   22.00  3816.00   968.00    61.33    43.19  111.46  106.90  139.27   6.41 100.00

         avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.50    0.00    0.00   82.00    0.50   17.00

    Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
    xvdf              0.00     0.00   12.00  137.00   196.00  6028.00    83.54   142.10  653.13  298.00  684.23   6.71 100.00

         avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.50    0.00    1.00   87.56    0.00   10.95

    Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
    xvdf              0.00     0.00   21.00  129.00   440.00  5640.00    81.07   141.76  924.08  300.19 1025.64   6.67 100.00

目前怀疑的原因是倒排索引数据太碎,写入频率过高频繁触发compact,到时磁盘写放大,写入阻塞, leveldb cache频繁失效

请教下,对于这种结构的数据,以及这种规模的数据,是否适合ssdb, 出现这种情况是否正常,还是我使用上有什么问题?

**Comment by ideawu** [comment]
你的配置文件能否贴上来?

**Comment by ideawu** [comment]
我分析, 你的操作主要是:

保存word=>doc_id: hset word doc_id weight
保存doc_id=>word: hset doc_id word weight

hgetall 查询对应的业务是什么? 是 hgetall word, 还是 hgetall doc_id?

**Comment by ErenNo1** [comment]
保存word=>doc_id: hset word doc_id weight是这样的，
但是保存doc_id=>word: hset doc_id word weight，并非如此，因为文章有多少词，weight是多少，都是固定的，以后只会读取，不会修改，所以直接以doc_id 为 key， （word1 ： weight1， word2：weight2.....）以json格式的方式整体做为value存放的。

针对word的hgetall操作主要是为了查询当前这个词都在哪些文章中出现过，类似与搜索引擎单个键关词搜索；
一般我会针对某个文章，根据doc_id 做一次get操作，获取它所有的word，然后几乎每个word都进行一次hgetall，获取这些词分别都出现在那些文章中，这样再做些其他计算就能查到当前这篇doc的相关，相似，重复的文章了。

**Comment by ErenNo1** [comment]
conf文件如下：
  logger:
        level: warn
        output: log.txt
        rotate:
                size: 1000000000

  leveldb:
        # in MB
        cache_size: 1000
        # in KB
        block_size: 32
        # in MB
        write_buffer_size: 64
        # in MB
        compaction_speed: 1000
        # yes|no
        compression: yes

**Comment by ErenNo1** [comment]
info 信息的话，等我捕捉下异常缓慢的情况再发，并不是一直很慢，只是很频繁

**Comment by ErenNo1** [comment]
version
    1.8.0
  links
    11
  total_calls
    45507670
  dbsize
    9702876276
  binlogs
        capacity : 10000000
        min_seq  : 479768063
        max_seq  : 490277411
  key_range.kv
    "doc_count" - "doc_count
  key_range.hash
    "term_inverted_index_1" - "term_inverted_index_999999"
  key_range.zset
    "entity_df" - "term_df"
  key_range.list
    "" - ""
  leveldb.stats
                                   Compactions
    Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
    --------------------------------------------------
      0        0        0        14        0       224
      1        0        0        88      224      1272
      2       12      311      4355    36331     36204
      3      302     9562     82260   594374    593616
    
  21 result(s) (0.026 sec)


  version
    1.8.0
  links
    11
  total_calls
    45517102
  dbsize
    9702876276
  binlogs
        capacity : 10000000
        min_seq  : 479768063
        max_seq  : 490282287
  key_range.kv
    "doc_count" - "doc_count"
  key_range.hash
    "term_inverted_index_1" - "term_inverted_index_999999"
  key_range.zset
    "entity_df" - "term_df"
  key_range.list
    "" - ""
  leveldb.stats
                                   Compactions
    Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
    --------------------------------------------------
      0        0        0        14        0       224
      1        0        0        88      224      1272
      2       12      311      4355    36331     36204
      3      302     9562     82260   594374    593616
    
  21 result(s) (0.001 sec)

**Comment by ErenNo1** [comment]
version
        1.8.0
    links
        11
    total_calls
        45517629
    dbsize
        9702876276
    binlogs
            capacity : 10000000
            min_seq  : 479768063
            max_seq  : 490282513
    cmd.zincr
        calls: 6093551      time_wait: 11957235    time_proc: 2043238
    cmd.sync140
        calls: 0    time_wait: 0    time_proc: 0
    cmd.ttl
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qfix
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qtrim_front
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qget
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qrlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.get
        calls: 63102    time_wait: 51   time_proc: 674
    cmd.auth
        calls: 0    time_wait: 0    time_proc: 0
    cmd.getbit
        calls: 0    time_wait: 0    time_proc: 0
    cmd.getset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qtrim_back
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zdel
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.dbsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hkeys
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_exists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hdecr
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrrange
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_get
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hvals
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hget
        calls: 279075   time_wait: 7295 time_proc: 73653470
    cmd.zrank
        calls: 0    time_wait: 0    time_proc: 0
    cmd.key_range
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zdel
        calls: 0    time_wait: 0    time_proc: 0
    cmd.compact
        calls: 0    time_wait: 0    time_proc: 0
    cmd.set_key_range
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zclear
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zavg
        calls: 0    time_wait: 0    time_proc: 0
    cmd.getrange
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpush_front
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpush
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qrange
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hget
        calls: 12047506 time_wait: 5839 time_proc: 5669673
    cmd.qlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpop
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpop_back
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.setx
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hexists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hincr
        calls: 47731    time_wait: 418644   time_proc: 4789
    cmd.strlen
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpop_front
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zremrangebyscore
        calls: 0    time_wait: 0    time_proc: 0
    cmd.setbit
        calls: 0    time_wait: 0    time_proc: 0
    cmd.keys
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zcount
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.clear_binlog
        calls: 0    time_wait: 0    time_proc: 0
    cmd.get_key_range
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zget
        calls: 0    time_wait: 0    time_proc: 0
    cmd.setnx
        calls: 0    time_wait: 0    time_proc: 0
    cmd.decr
        calls: 0    time_wait: 0    time_proc: 0
    cmd.set
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zsum
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hclear
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.del
        calls: 0    time_wait: 0    time_proc: 0
    cmd.scan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hexists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qback
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zkeys
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zget
        calls: 5017122  time_wait: 100316   time_proc: 54326
    cmd.qslice
        calls: 0    time_wait: 0    time_proc: 0
    cmd.rscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hrlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrange
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zdecr
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_set
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qfront
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zexists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpush_back
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hgetall
        calls: 5528688  time_wait: 143549   time_proc: 29929139
    cmd.dump
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_del
        calls: 0    time_wait: 0    time_proc: 0
    cmd.ping
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hdel
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.incr
        calls: 31619    time_wait: 276248   time_proc: 21149
    cmd.exists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.countbit
        calls: 0    time_wait: 0    time_proc: 0
    cmd.expire
        calls: 0    time_wait: 0    time_proc: 0
    cmd.substr
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zremrangebyrank
        calls: 0    time_wait: 0    time_proc: 0
    cmd.redis_bitcount
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hrscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hset
        calls: 16409224 time_wait: 18770862 time_proc: 50990189
    cmd.info
        calls: 11   time_wait: 0    time_proc: 537
    cmd.qsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qclear
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrrank
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hdel
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zexists
        calls: 0    time_wait: 0    time_proc: 0
215 result(s) (0.004 sec)




    version
        1.8.0
    links
        11
    total_calls
        45520347
    dbsize
        9702876276
    binlogs
            capacity : 10000000
            min_seq  : 479768063
            max_seq  : 490283808
    cmd.zincr
        calls: 6093935  time_wait: 11957241 time_proc: 2043367
    cmd.sync140
        calls: 0    time_wait: 0    time_proc: 0
    cmd.ttl
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qfix
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qtrim_front
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qget
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qrlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.get
        calls: 63104    time_wait: 51   time_proc: 674
    cmd.auth
        calls: 0    time_wait: 0    time_proc: 0
    cmd.getbit
        calls: 0    time_wait: 0    time_proc: 0
    cmd.getset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qtrim_back
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zdel
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.dbsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hkeys
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_exists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hdecr
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrrange
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_get
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hvals
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hget
        calls: 279094   time_wait: 7296 time_proc: 73683743
    cmd.zrank
        calls: 0    time_wait: 0    time_proc: 0
    cmd.key_range
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zdel
        calls: 0    time_wait: 0    time_proc: 0
    cmd.compact
        calls: 0    time_wait: 0    time_proc: 0
    cmd.set_key_range
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zclear
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zavg
        calls: 0    time_wait: 0    time_proc: 0
    cmd.getrange
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpush_front
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpush
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qrange
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hget
        calls: 12048171 time_wait: 5839 time_proc: 5671206
    cmd.qlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpop
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpop_back
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.setx
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hexists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hincr
        calls: 47734    time_wait: 418644   time_proc: 4789
    cmd.strlen
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpop_front
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zremrangebyscore
        calls: 0    time_wait: 0    time_proc: 0
    cmd.setbit
        calls: 0    time_wait: 0    time_proc: 0
    cmd.keys
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zcount
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.clear_binlog
        calls: 0    time_wait: 0    time_proc: 0
    cmd.get_key_range
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zget
        calls: 0    time_wait: 0    time_proc: 0
    cmd.setnx
        calls: 0    time_wait: 0    time_proc: 0
    cmd.decr
        calls: 0    time_wait: 0    time_proc: 0
    cmd.set
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zsum
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hclear
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.del
        calls: 0    time_wait: 0    time_proc: 0
    cmd.scan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hexists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qback
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zkeys
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zget
        calls: 5017438  time_wait: 100321   time_proc: 54329
    cmd.qslice
        calls: 0    time_wait: 0    time_proc: 0
    cmd.rscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hrlist
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrange
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zdecr
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_set
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hset
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qfront
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_zexists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qpush_back
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hgetall
        calls: 5529030  time_wait: 143559   time_proc: 29935822
    cmd.dump
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_del
        calls: 0    time_wait: 0    time_proc: 0
    cmd.ping
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hdel
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.incr
        calls: 31620    time_wait: 276248   time_proc: 21149
    cmd.exists
        calls: 0    time_wait: 0    time_proc: 0
    cmd.countbit
        calls: 0    time_wait: 0    time_proc: 0
    cmd.expire
        calls: 0    time_wait: 0    time_proc: 0
    cmd.substr
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zremrangebyrank
        calls: 0    time_wait: 0    time_proc: 0
    cmd.redis_bitcount
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hrscan
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hset
        calls: 16410209 time_wait: 18770877 time_proc: 51009153
    cmd.info
        calls: 12   time_wait: 0    time_proc: 537
    cmd.qsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.multi_hsize
        calls: 0    time_wait: 0    time_proc: 0
    cmd.qclear
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zrrank
        calls: 0    time_wait: 0    time_proc: 0
    cmd.hdel
        calls: 0    time_wait: 0    time_proc: 0
    cmd.zexists
        calls: 0    time_wait: 0    time_proc: 0
215 result(s) (0.001 sec)

**Comment by ErenNo1** [comment]
@ideawu 麻烦您有时间帮忙分析下, 想知道是存储设计有问题,还是机器性能不足,亦或者是kv型存储本就不适合倒排表?

**Comment by ideawu** [comment]
从你给的数据来看, 所有的请求平均处理时间都非常快, 除了

```
cmd.multi_hget
    calls: 279075   time_wait: 7295 time_proc: 73653470
```

如果你一次 multi_hget 非常多的 key, 如 100 个, 是有可能处理超过 10ms~100ms 的.

你给的 iostat 也没有异常.

你可以参考 http://ssdb.io/docs/zh_cn/logs.html 找出慢请求.

另外, 你能否再介绍下你观察到慢的情况, 以及对你的业务的影响? 我看能不能根据业务特点进行调整.

**Comment by ErenNo1** [comment]
因为关闭日志会又性能改善,所以前几天把日志设置成warning级别了, 之前的日志里能查到,如下:

    2015-05-20 02:30:29.134 [DEBUG] worker.cpp(35): w:0.006,p:115.946, req: hset bow_inverted_index_6944 823819 0.012359, resp: ok 0
    2015-05-20 02:30:29.503 [DEBUG] worker.cpp(35): w:0.013,p:714.687, req: multi_hget keyword_index 240481 242634 242705 [1158 more...], resp: ok 376767 [628] 377389 [1012] [2200 more...]
    2015-05-20 02:30:30.623 [DEBUG] worker.cpp(35): w:0.008,p:835.934, req: multi_hget keyword_index 240302 240670 241026 [1189 more...], resp: ok 376572 [4314] 378933 [3852] [2142 more...]
    2015-05-20 02:30:31.682 [DEBUG] worker.cpp(35): w:0.037,p:190.600, req: multi_hget keyword_index 240011 240021 240168 [1270 more...], resp: ok 376210 [1374] 379340 [2832] [2362 more...]
    2015-05-20 02:30:35.582 [DEBUG] worker.cpp(35): w:0.007,p:154.028, req: multi_hget keyword_index 242400 242811 243125 [1496 more...], resp: ok 375886 [310] 375935 [988] [2760 more...]
    2015-05-20 02:30:40.548 [DEBUG] worker.cpp(35): w:0.005,p:709.798, req: multi_hget keyword_index 240246 240655 241169 [1319 more...], resp: ok 376228 [8397] 376938 [1744] [2374 more...]
    2015-05-20 02:30:42.144 [DEBUG] worker.cpp(35): w:0.014,p:121.576, req: hset bow_inverted_index_547 823845 0.035210, resp: ok 0
    2015-05-20 02:30:42.325 [DEBUG] worker.cpp(35): w:0.007,p:112.784, req: hset bow_inverted_index_1035 823845 0.057179, resp: ok 0
    2015-05-20 02:30:45.464 [DEBUG] worker.cpp(35): w:0.024,p:113.017, req: hset term_inverted_index_6685 623447 0.003367, resp: ok 1
    2015-05-20 02:30:45.976 [DEBUG] worker.cpp(35): w:0.006,p:282.339, req: multi_hget keyword_index 240502 241000 241787 [924 more...], resp: ok 375922 [943] 376194 [3477] [1704 more...]
    2015-05-20 02:30:46.158 [DEBUG] worker.cpp(35): w:0.015,p:2423.951, req: multi_hget keyword_index 340125 340143 340194 [1723 more...], resp: ok 340125 [1550] 340143 [541] [3448 more...]
    2015-05-20 02:30:58.217 [DEBUG] worker.cpp(35): w:0.015,p:109.398, req: hset term_inverted_index_15471 823839 0.001912, resp: ok 0
    2015-05-20 02:30:58.353 [DEBUG] worker.cpp(35): w:0.015,p:136.054, req: hset term_inverted_index_15600 823839 0.001912, resp: ok 0
    2015-05-20 02:31:02.840 [DEBUG] worker.cpp(35): w:0.006,p:969.059, req: multi_hget keyword_index 240120 240260 240843 [1147 more...], resp: ok 375816 [794] 377741 [2229] [2152 more...]
    2015-05-20 02:31:03.880 [DEBUG] worker.cpp(35): w:0.007,p:488.768, req: multi_hget keyword_index 240758 241924 242982 [1144 more...], resp: ok 375966 [1414] 376062 [1501] [2114 more...]


类似这种日志非常多,尤其在iostat  util = 100% 时, 因为每篇文章要分别执行几十上百(每篇文章有几十上百个词)次hset, zincr, 很多时候累计时间超过10秒, 只能放弃后续的操作. 不然后边的请求会发生阻塞排队 

用的最便宜的EC2 ssd磁盘(50G), 使用time dd if=/dev/zero bs=1M count=2048 of=direct_2G 磁盘写入速度只有 90M/S, 开发机器普通硬盘 180M/s, 开发机真实ssd硬盘 450M/s

不知道是dd这种方式不科学,还是ec2 的ebs太坑~~

**Comment by ideawu** [comment]
有不少人反映 amazon 的主机性能很差. 你可以换机器测试对比一下.
