### ISSUE TITLE
ssdb内存使用估算问题

### ISSUE THREAD

**Issue by Masterlvng** [ideawu/ssdb#685]
你好，
ssdb的文档上说,
```
一个 ssdb-server 实例占用的内存最高达到(MB):
cache_size + write_buffer_size * 66 + 32
```
本人对这个“66”有疑惑。
翻看以前的issue，有说到是因为compact的时候会有最多64个sst文件读进内存。
可是翻看leveldb代码, DoCompactionWork并没这样实现，能看到的是最多只有两个memtable。

leveldb中write_buffer_size的解释
```
  // Amount of data to build up in memory (backed by an unsorted log
  // on disk) before converting to a sorted on-disk file.
  //
  // Larger values increase performance, especially during bulk loads.
  // Up to two write buffers may be held in memory at the same time,
  // so you may wish to adjust this parameter to control memory usage.
  // Also, a larger write buffer will result in a longer recovery time
  // the next time the database is opened.
  //
```
上面也说到最多只会同时有俩个write buffer。

在64bit server下， randomaccessfile 是通过mmap支持的，这样是会占用虚拟内存。但是也想不到跟“66”的关联。

请问，“66”是从何来呢？ 望指教。

**Comment by ErenNo1** [comment]
https://github.com/ideawu/ssdb/wiki/Changes-Made-to-LevelDB

--- db/dbformat.h.bk 2013-05-02 10:24:46.000000000 +0800
+++ db/dbformat.h   2013-05-03 17:13:49.000000000 +0800
@@ -25,10 +25,10 @@ static const int kNumLevels = 7;
static const int kL0_CompactionTrigger = 4;

// Soft limit on number of level-0 files.  We slow down writes at this point.
-static const int kL0_SlowdownWritesTrigger = 8;
+static const int kL0_SlowdownWritesTrigger = 16;

// Maximum number of level-0 files.  We stop writes at this point.
-static const int kL0_StopWritesTrigger = 12;
+static const int kL0_StopWritesTrigger = 64;


64 + 2( memtable + immutable) = 66 
66 并非常驻,而是L0 触发compact的时候的内存消耗

**Comment by ideawu** [comment]
没错, 所以文档中的最高内存占用, 不是持续内存占用.

**Comment by ideawu** [comment]
@ErenNo1 Hi, 文档中做了补充, 加上"瞬时"修饰, 表示瞬时内存最高占用.

**Comment by Masterlvng** [comment]
leveldb缓存(tablecache)了很多randomaccessfile， 按照这个逻辑，数值应该是比66还要多才对呀。
