### ISSUE TITLE
get不会抛出connection. lost

### ISSUE THREAD

**Issue by gqkang** [ideawu/ssdb#688]
get循环获取数据，当Ssdb服务器挂了，get不会抛出 connection. lost

**Comment by ideawu** [comment]
会抛出 connection lost, 如果你没看到, 请告诉你看到了什么? 反映问题一定要有现象和你的预期, 或者是逻辑推理, 不能光说没有依据的空洞结论.

**Comment by ideawu** [comment]
谢谢反馈! 已经 fix: https://github.com/ideawu/ssdb/issues/690
