### ISSUE TITLE
新增 zookeeper 模块

### ISSUE THREAD

**Issue by liangjie** [ideawu/ssdb#691]
最近把 zk client 集成到 ssdb 里面

主要是解决：1. 配置问题；2. 集群化管理

**Comment by ideawu** [comment]
不错, 欢迎把代码和解决方案开源出来. 考虑到ssdb轻量级的定位考虑, 这个方案应该是独立于 ssdb 项目的.

**Comment by liangjie** [comment]
可以的，而且现有的 java api 存在BUG和有优化的地方。后面等我把手头上项目结束，会把代码贡献出来。
