### ISSUE TITLE
数据快照

### ISSUE THREAD

**Issue by lzn993** [ideawu/ssdb#693]
您好！请问一下SSDB有没有基于整个数据库的快照功能？（使用备份命令可能太耗时了，因此想使用快照）

**Comment by lzn993** [comment]
我的应用场景是这样的：除了主从之外，想再单独做一个冷备，解决由于程序错误导致的数据回滚问题。如果直接使用SSDB的导出功能，可能会比较耗时，期间也会严重影响了SSDB的运行。因此我们想找一个快速的、尽量对SSDB影响较小的备份方案：如直接文件级别的copy（不知道这样copy的文件是否是安全的），或其他高效的快照功能。

**Comment by lzn993** [comment]
您好！ssdb的数据库备份：ssdb-dump和export都是可以做到的，请问他们有什么区别？如果数据库数据比较多，备份时间可能会比较长，这时SSDB对外的其他服务（数据读写）会被阻塞吗？

**Comment by ideawu** [comment]
备份会对正常服务有影响, 建议在空闲时间进行. ssdb-dump 性能会好一些, 而 ssdb-cli 下 export  命令能导出类似 sql 文件类似的人可阅读的文件.

**Comment by ideawu** [comment]
可以直接 copy 文件备份, 但备份时, 必须正确地将 ssdb-server 停止.

```
./ssdb-server /path/ssdb.conf -s stop
```
