### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by sundy-li** [ideawu/ssdb#695]
[root@master ssdb]# sudo make install
sudo：ldap_sasl_bind_s(): Can't contact LDAP server
mkdir -p /usr/local/ssdb
mkdir -p /usr/local/ssdb/_cpy_
mkdir -p /usr/local/ssdb/deps
mkdir -p /usr/local/ssdb/var
mkdir -p /usr/local/ssdb/var_slave
cp ssdb-server ssdb.conf ssdb_slave.conf /usr/local/ssdb
cp: "ssdb-server" 与"/usr/local/ssdb/ssdb-server" 为同一文件
cp: "ssdb.conf" 与"/usr/local/ssdb/ssdb.conf" 为同一文件
cp: "ssdb_slave.conf" 与"/usr/local/ssdb/ssdb_slave.conf" 为同一文件
make: *** [install] 错误 1

但是可以启动 ssdb-server和client, 这个错误会有什么影响吗? 另外问下ssdb 分布式的稳定性如何, 我打算新的服务用ssdb, 可能有1kw一天的写入

**Comment by ideawu** [comment]
关于 make install, 你可以手动修改 Makefile, 给 cp 命令加上 `-f` 选项, 或者请重新更新下代码.

ssdb 是稳定的. 但分布式功能还在试验阶段.

**Comment by sundy-li** [comment]
I see..
