### ISSUE TITLE
请问下 首页的并发测试是在什么机器环境下得出 和redis的对比图的?

### ISSUE THREAD

**Issue by sundy-li** [ideawu/ssdb#697]
如题
我用go客户端,写了一个set代码的测试, 在24核, 64G内存的机器下
跑10个并发, 10* 50000 个kv set, qps只有33333 多,是leveldb参数要做什么调整才能发挥最大性能吗?

```
[root@master ssdb]# go run ssdbmark.go  -p=10 -n=50000
2015/06/05 15:59:37 /data/www/go/src/t/ssdb/ssdbmark.go:39: [DEBUG] concurrent qps is 33333 in set 500000 kvs, in 15 seconds
```

**Comment by sundy-li** [comment]
另外我用同样的测试用例 测试goleveldb和ssdb ,  发现 ssdb的性能和 leveldb的性能还是有很大差距, 请问性能方面主要是哪方面有很大损耗?

**Comment by ideawu** [comment]
goleveldb 是一个库, ssdb 的一个网络服务器. 无法简单地进行数字对比, 你自己好好想想.
