### ISSUE TITLE
ssdb 日志文件

### ISSUE THREAD

**Issue by lzn993** [ideawu/ssdb#698]
您好，请问SSDB根目录下的日志文件log.txt有哪些作用，该日志文件除了记录程序的运行信息，对数据库的数据恢复有帮助吗？数据库恢复数据时，是不是需要使用到这个问题，希望能详细解释一下。
（我的应用场景是这样的，数据库不大，只有10GB左右，但是每天的数据读写操作非常频繁，平均下来，达到每秒2000--3000次，这种场景下，日常文件非常大，占用较多磁盘空间，且影响了磁盘IO）

**Comment by lzn993** [comment]
这个日志文件数量有哪些限制，在哪里可以配置？

**Comment by ideawu** [comment]
除了 log.txt, log.txt-20* 这样名字的你可以删除. 如果想减少 log.txt 的日志量, 可以修改 ssdb.conf, 将日志级别改为 error:

```
logger:
    level: error
```
