### ISSUE TITLE
ssdb-server out of memery 被kill掉

### ISSUE THREAD

**Issue by ErenNo1** [ideawu/ssdb#699]
Jun  6 06:51:05 ip-172-31-8-224 kernel: [187067.994047] Out of memory: Kill process 6381 (ssdb-server) score 911 or sacrifice child
    Jun  6 06:51:05 ip-172-31-8-224 kernel: [187067.999000] Killed process 6381 (ssdb-server) total-vm:6647376kB, anon-rss:3618228kB, file-rss:0kB

  机器内存：3766M  

leveldb:
        # in MB
        cache_size: 3000
        # in KB
        block_size: 64
        # in MB
        write_buffer_size: 128
        # in MB
        compaction_speed: 50
        # yes|no
        compression: yes

请教下，是我配置的cache太大了，还是算是ssdb的一个bug？

目前已经将cache调整为1500， 增加了2g swap 这样是否可以解决呢？
如果compact的时候最大需要64个 write buffer，是不是还是会出现这种问题？

**Comment by ideawu** [comment]
因为你的机器只有 3766, 大概会被系统用去 1G 左右, 所以, 需要根据自己的实际情况, 减少 cache_size. 根据你的情况, 建议:

```
cache_size: 1000
write_buffer_size: 32
compaction_speed: 200
```
