### ISSUE TITLE
log.txt日志文件对数据恢复的影响

### ISSUE THREAD

**Issue by lzn993** [ideawu/ssdb#700]
请问ssdb的数据恢复，是否依赖log.txt日志文件，以及各个日志级别对数据恢复的影响？例如，日志级别为error时，日志内容就非常少了，这时ssdb是否就不具备恢复能力了？

**Comment by ErenNo1** [comment]
依赖的是binlog 跟这个无关

**Comment by ideawu** [comment]
log.txt 是日志, 你需要理解 log 的含义, 和数据本身没有依赖关系.
