### ISSUE TITLE
ssdb有时无法重启

### ISSUE THREAD

**Issue by lzn993** [ideawu/ssdb#701]
有一定概率无法重启，情况有两种
1. 手动重启
 [root@ip-172-31-22-176 ssdb]# ./ssdb-ins.sh restart ssdb.conf 
ssdb instance: ssdb.conf
ssdb-server 1.9.0
Copyright (c) 2012-2015 ssdb.io

Fatal error!
Pidfile /ssdb_data/var/ssdb.pid already exists!
Kill the running process before you run this command,
or use '-s restart' option to restart the server.

2.配置了随系统开机自动启动，错误信息和1是一样的

我做的操作：修改了存储数据的目录。

**Comment by lzn993** [comment]
通过查看进程，发现restart的时候，没有成功把进程退出，导致start失败

**Comment by ErenNo1** [comment]
我猜测你的ssdb.conf 里面 pidfile的路径写的有问题, 不能写绝对路径,要写相对的
例如:
    # relative to path of this file, directory must exists
    work_dir = /data/ssdb/var
    pidfile = ./ssdb.pid

**Comment by lzn993** [comment]
确实是这个问题，换为相对路径，就好了。thank you。

**Comment by ideawu** [comment]
ssdb-in.sh 在未来的版本不再推荐使用了, 请用 ssdb-server 代替, 用法如下:

```
./ssdb-server /path/to/ssdb.conf -s start
./ssdb-server /path/to/ssdb.conf -s stop
./ssdb-server /path/to/ssdb.conf -s restart
```

**Comment by lzn993** [comment]
好的，thank you!
