### ISSUE TITLE
Python 600线程下，SSDB挂了，大量“Write error!”

### ISSUE THREAD

**Issue by pengqi** [ideawu/ssdb#704]
Ubuntu 14.04 64位
客户端：pyssdb
问题：
600线程情况下，SSDB挂了，一直提示“[ERROR] t_queue.cpp(312): Write error!”错误。
重启SSDB，并将线程数调整到300，工作正常了。

请问这是什么原因？怎么解决？如果提供更多详情，请告知。

**Comment by ideawu** [comment]
这个报错一般是因为硬盘io错误, 原因很多, 例如硬盘满. 如果你方便修改源码的话, 请将t_queue.cpp 312行修改为:

```
		log_error("Write error! %s", s.ToString().c_str());
```

**Comment by pengqi** [comment]
磁盘还空闲90%，可以排除这个。

**Comment by pengqi** [comment]
运行一段时间后很容易出现“Write error!”。我修改了你说的代码，现在完整的错误信息是这样的：
2913027 2015-06-23 17:22:18.565 [ERROR] t_queue.cpp(313): Write error! IO error: ./var/data/089145.ldb: Too many open files

怎么破？

**Comment by ErenNo1** [comment]
一定要记得修改你的 Linux 内核参数, 关于 max open files(最大文件描述符数)的内容, 请参考 [1]. 否则, 你会在 log.txt 看到 Too many open files 类似的错误, 或者在客户端看到 Connection reset by peer 错误.

http://ssdb.io/docs/zh_cn/config.html

**Comment by ideawu** [comment]
@pengqi 确实如 @ErenNo1 所说, 需要修改系统配置. 另外, 我更新了代码, 把错误信息也打印出来了.
