### ISSUE TITLE
ssdb 如何正确停止

### ISSUE THREAD

**Issue by lzn993** [ideawu/ssdb#706]
您好，请问应该如何正确停止运行中的ssdb，以确保内存中的数据正确持久化到磁盘。
./ssdb-ins.sh stop ssdb.conf
这个命令，我研究了一下ssdb-ins.sh脚本，发现脚本是直接kill进程的。请问SSDB对这个信号量有哪些处理，如何确保进程退出前，持久化内存中的数据

**Comment by ideawu** [comment]
不加参数的 kill, 或者 ./ssdb-server ssdb.conf -s stop, 都是正确的停止服务的方法.
