### ISSUE TITLE
ssdb cpu使用率较高

### ISSUE THREAD

**Issue by lzn993** [ideawu/ssdb#707]
您好，我这边在游戏发布使用一段时间后，出现CPU使用率高的现场，麻烦帮忙分析一下。
我采用的是主从架构，目前数据库180MB，读写总量每秒钟约600次。（注：slave机器除了在凌晨5点做备份，不负责其他任何工作）
master硬件配置：
亚马逊EC2实例：
r3.large	 Intel Xeon E5-2670 v2（分配双核）	16G内存	100G固态硬盘（300IOPS）
SSDB 配置分配6GB内存，日志级别为error

slave硬件配置
t2.medium	 Intel Xeon 处理器，频率3.3GHz（分配虚双核）	4G内存	60G固态硬盘（180IOPS）
SSDB 配置分配2GB内存，日志级别为error

在使用中，发现SSDB的CPU平均使用率分别为30%（master），1%（slave）
我们数据读写量与SSDB的性能值差距还非常大，照理CPU使用率不应该这么高。

请问SSDB每秒钟5万多次读写性能，这个次数是怎么计算的，即怎样才算1次。
我程序结构中，绝大部分都是采用hashmap表结构的，假设我一个hashmap表有50个字段，
我调用1次 hgetall命令，是算1次，还是算50次？

**Comment by ideawu** [comment]
你好, 计算 qps 的方法是, 两次执行(间隔10秒)

```
info
```

然后根据返回的 `total_calls`的差额, 除以时间间隔, 即是 qps. hgetall 命令统计上算一次查询, 但 hgetall 会根据数据量的多与少, 和相应的io成本成正比.

请把你的 ssdb.conf 发上来看看.

**Comment by lzn993** [comment]
# ssdb-server config
# MUST indent by TAB!

# relative to path of this file, directory must exists
work_dir = /ssdb_data/var
pidfile = ./ssdb.pid

server:
        ip: 172.31.22.176
        port: 32800
        # bind to public ip
        #ip: 0.0.0.0
        # format: allow|deny: all|ip_prefix
        # multiple allows or denys is supported
        #deny: all
        #allow: 127.0.0.1
        #allow: 192.168
        # auth password must be at least 32 characters
        auth: d8a4c0d566518ec5890aaec9546dce85

replication:
        binlog: yes
        # Limit sync speed to *MB/s, -1: no limit
        sync_speed: -1
        slaveof:
                # to identify a master even if it moved(ip, port changed)
                # if set to empty or not defined, ip:port will be used.
                #id: svc_2
                # sync|mirror, default is sync
				#type: sync
                #ip: 127.0.0.1
                #port: 8889

logger:
        level:error
        output: log.txt
        rotate:
                size: 1000000000

leveldb:
        # in MB
        cache_size: 6144
        # in KB
        block_size: 32
        # in MB
        write_buffer_size: 64
        # in MB
        compaction_speed: 1000
        # yes|no
        compression: yes

**Comment by lzn993** [comment]
这个是master的，slave的是正常的，且除了定期凌晨5点备份，没有其他使用，应该不需要吧。

**Comment by lzn993** [comment]
查看过我们的IO使用情况了，master的配置是300IOPS，平均只使用了6IOPS，因此IO性能还是非常充足的。

**Comment by lzn993** [comment]
使用info命令查看了一下，10秒内3588次，即每秒钟359次

**Comment by lzn993** [comment]
我的使用场景大概是80%写，20%读。

**Comment by ideawu** [comment]
CPU 占用是通过 top 命令查看的吗?

**Comment by lzn993** [comment]
通过3种方法查看的：
1. top 查看单CPU使用率
2. top 1 查看每个CPU的使用率
3. 使用亚马逊平台的CPU监控工具

这3种方法得出的数据基本是一致的： 平均30%CPU使用率

**Comment by lzn993** [comment]
# in MB
compaction_speed: 1000
 # yes|no
 compression: yes
这2个属性会cpu影响大吗。 我把compression属性关闭了，但是提升不明显

**Comment by ideawu** [comment]
这两个选项影响非常小. 不确定是否和 amazon 的虚拟机有关. 如果可以的话, 建议你和 redis 做一个对比, 把结果发上来. 非常感谢!

**Comment by lzn993** [comment]
我已经找到原因，并成功解决了这个cpu负载高的问题，在这里和大家分享，希望对SSDB的提升和改进有所帮助。
改进前的情况：平均秒1500个call，8核CPU，16G内存，SSDB配置6G，以CPU满负荷800%计算，SSDB占用的CPU为350%。
由于游戏排名需要，使用ssdb的排行榜功能zset，由于SSDB api有说明，在数量大时，获取排名相关的接口会比较慢，因此排行榜的数据量都设计得非常小。共2张表，分别为 100名，10000名。
目前的使用场景是这样的：100名的排行榜，每5秒钟全量更新1次数据（1个call）；10000名的排行榜每15秒全量更新1次（1个call）。由于玩家较多，估计每秒钟约有30次调用获取排名的接口（PHP的redis接口 zRevRange），获取前30名、获取指定玩家的排名。
经我们测试，全量更新排行榜数据的操作，对ssdb负载影响不大。
---------------改进-----------------------
接着我们采用自己排序，然后把排好序的数据放到ssdb的hashmap存储，读取排名时，也是直接从hashmap读取。
经测试，SSDB的CPU占用情况平均为7%（即负载降低了50倍）。
---------------总结---------------------------
猜想ssdb与排名相关的功能，写入时可能是不计算的，每次读取时都会计算，造成大量的重复计算。（纯粹猜想，没任何根据）

**Comment by ideawu** [comment]
Hi, ssdb的zset排名函数 `zrank` 确实是查询时算的, 而且是遍历数据来算, 所以接口文档中说明这个方法会非常慢.

你的这个改进应该是非常赞的, 确实换一种方式, 可以达到很好的效果.
