### ISSUE TITLE
ssdb的kv失效时间会出现负数？

### ISSUE THREAD

**Issue by xsen123** [ideawu/ssdb#709]
将session值存放在ssdb中，设置了一个失效时间。但其中一条数据一直未自动删除，用ttl查看该节点的失效时间，显示为负数。

**Comment by ideawu** [comment]
以前某个版本确实有个bug, 如果有升级的话, 只能重启. 建议升级到最新版本.

**Comment by xsen123** [comment]
升级到1.9.0版本后，原失效时间为负值的变成了20几天。 至少能够自动删除了。
