### ISSUE TITLE
双主同步以及info信息的几个问题？

### ISSUE THREAD

**Issue by bandaotiehewen** [ideawu/ssdb#711]
群主你好，主从模式实验了很长时间没有问题，最近想保证高可用性，想使用双主，在测试的过程中有以下几个问题：
这个是我实验压测后的两个双主的info信息（上面为93和下面为94）
![93](https://cloud.githubusercontent.com/assets/10446544/8303751/a15206ce-19d2-11e5-943a-dd18dd1dd1b3.png)
![94](https://cloud.githubusercontent.com/assets/10446544/8303761/b1a5bf02-19d2-11e5-9340-b98b57c5ba2c.png)

1.怎样判定双主的数据是否都同步完毕？最开始正常非压力测试，发现93和94中的binlogs中的max_seq，replication client中的last_seq以及replication slaveof中的last_seq总是相等，从而认为是93和94上面的这几个数字都相同才是数据同步的？请问是这样么？
2.当后来压测的时候，客户端测试程序50个线程不停的往93上面hset，一共10亿次，由于同步94的数据太慢，在压测过程中，93上面replication client的status变为copy从头开始同步，最后94同步完毕后双方的info信息如上面图所示，93中的max_seq变为了100000108，而94上面的mas_seq为100000113，所以想问这样是否能判断双主同步完毕了的？

**Comment by ideawu** [comment]
根据图中的信息, 双主的同步已经达到"完毕"的状态, 这个状态表示在其中一台上面进行更新, 另一台能在极短的延时内同步. 判断的依据如文档所未: http://ssdb.io/docs/zh_cn/replication.html

注意, 双主的 max_seq 不是全部相等的, 而是分别判断2个独立的 master-slave.

**Comment by bandaotiehewen** [comment]
1理解判断主从同步的标志是：判断 binlogs.max_seq 和 replication.client.last_seq 是否相等，所有从这个上面看93中binlog的max_seq跟client的last_seq相同（同理94）可以判定双方都同步完毕么？
2.那么如果双主的max_seq不是全部相等，是由于什么原因或者说在什么情况下造成的呢？
3.还有就是94上的copy_count的值196951491，而定义slaveof.copy_count: 在全量同步时, 已经复制的 key 的数量，93的bin_log一共才100000000，那么为什么copy_count多出了块将近两倍的数据，最多不是100000000么？是不是有可能是因为出现了两次copy的状态导致的么？
谢谢群主

**Comment by ideawu** [comment]
1. 是的
2. 看第3条
3. binlog 会有淘汰机制, 只保留最新的 `capacity` 条. copy_count 表示复制的基准数据的条数, 不是binlog的条数.

**Comment by bandaotiehewen** [comment]
理解binlog只保留最新的capacity条数据，copy_count表示复制的数据的条数。但在上面的info显示，94中的replication slaveof的copy_count都达到了快2亿次，但实际上最多只有1一亿次的数据在93上面的写入，所以才会疑问，是不是94同步了两次造成的？

**Comment by ideawu** [comment]
是的, 中间中断过一次同步, slave会从头再次 copy.
