### ISSUE TITLE
VMware Workstation CentOS release 6.6  32 位环境中，ssdb setx命令有问题

### ISSUE THREAD

**Issue by laochen** [ideawu/ssdb#714]
重现步骤：
1. 在win7 64系统中安装VMware Workstation，具体安装的版本信息见图
![image](https://cloud.githubusercontent.com/assets/3325188/8345689/7182aecc-1b25-11e5-8a5d-6c46b04b62f9.png)
2.在虚拟机中安装 32位 centos 6.6
Linux SSDB 2.6.32-504.el6.i686 #1 SMP Wed Oct 15 03:02:07 UTC 2014 i686 i686 i386 GNU/Linux
CentOS release 6.6 (Final)
3. centos 中安装 SSDB 1.9版本
wget https://github.com/ideawu/ssdb/archive/master.zip
unzip master.zip
make
make install
4. 安装php
5. 启动ssdb 
   /usr/local/ssdb/ssdb-server -d ssdb.conf
6. 编写php 测试程序 test.php
代码如下：
<?php
include_once('SSDB.php');
try{
        $ssdb = new SimpleSSDB('127.0.0.1', 8888);
}catch(SSDBException $e){
        die(__LINE__ . ' ' . $e->getMessage());
}
        $key = 'yanzhengma_' . date('Y-m-d_H:i:s', time());
        $ssdb->setx($key, '100', 10);
        $sdata = $ssdb->scan("yanzhengma_0", 'yanzhengma_~', 100);
        var_dump($sdata);
?>
7. 重复执行 php test.php
可见到最老的6个key一直存在，其他的key,在超过时限以后自动消失

**Comment by ideawu** [comment]
如何重现法?
