### ISSUE TITLE
什么时候能在android app里使用呢～

### ISSUE THREAD

**Issue by KingHanWen** [ideawu/ssdb#718]
如题～

**Comment by ideawu** [comment]
已经支持! https://github.com/ideawu/ssdb/blob/master/ChangeLog#L66

**Comment by KingHanWen** [comment]
我是说集成到android app里面～

**Comment by ideawu** [comment]
里面有 .a 静态库.

**Comment by KingHanWen** [comment]
又没有例子或者用法 ，我看了这篇http://wendal.net/2014/05/13.html
但是这并没有集成进app

**Comment by ideawu** [comment]
Hi, 我没有安卓的环境, 不熟悉. 你可以继续关注 wendal.net, 看看他的进展.
