### ISSUE TITLE
php 版的ssdb客户端 同一个连接多次发送数据  出现接收数据重叠现象

### ISSUE THREAD

**Issue by huangjialin** [ideawu/ssdb#721]
如题：

多次请求不同的 hash  name  出现多次叠加为一次返回的情况 导致 某些值返回值出现在不应该出现的结果中

如：请求  name:james_info 和  name:tom_info  前者的结果会返回给后者  
还请作者验证是否有此问题

**Comment by ideawu** [comment]
验证没有此问题. 一定是你使用的姿势不对.

**Comment by huangjialin** [comment]
多谢ideawu 
我再描述一下我的应用场景：
1.服务器启动时候 ，new 一个全局的  ssdb client对像，不关闭（一直没有做close操作）
2.每秒上千次请求 一个api地址  从ssdb拿数据
3.api  服务启用10个进程来处理请求
4.今天再次验证在会出现 数据叠加的情况～ 

看了ssdb.php 的源码，每次 通过这个 sock 写数据和读数据 都没有做加锁 之类的操作。不知道是否多进程时候资源争抢导致

**Comment by ideawu** [comment]
多进程之间是隔离的, 与 ssdb.php 是否加锁无关. 你需要分析一下, 你的这个10个进程是否做了符合业务逻辑的调度. 为了更好更快地解决问题, 同时在你没有提供可重现的代码的前提下, 请你务必转变观念, 把所有的怀疑都放在自己的代码上面, 注意, 完全排队ssdb的问题之后, 有助于缩小排查范围. 再次重申, 请把所有的精力放在自己的代码上面!
