### ISSUE TITLE
关于 redis 迁移问题

### ISSUE THREAD

**Issue by JohnHwee** [ideawu/ssdb#729]
怎么将 多台 redis 数据库迁移至 ssdb 呢？

**Comment by ideawu** [comment]
你好, 使用 `tools/redis-import.php` 脚本, 一次迁移一个 redis 实例, 依次进行, 走到把所有的 redis 实例都迁移完毕.

注意, ssdb 不支持多 db. 相关文档请留意__官方网站__: http://ssdb.io/docs/redis-to-ssdb.html

**Comment by henry-zhuang** [comment]
@ideawu 你好，我试着运行 redis-import.php 得到这个错误。

```
PHP Fatal error:  Class 'Redis' not found in /root/ssdb/tools/redis-import.php on line 39
```

请问这个问题要如何解决呢？

**Comment by ideawu** [comment]
你们使用的 redis 是修改过的? 如果官方的 redis 客户端都连接不上的话, redis-import.php 也连接不上. 只能你参考 redis-import.php 的源码, 自己写脚本迁移数据了.

**Comment by henry-zhuang** [comment]
@ideawu 我导出了 rdb 文件，请问有没有什么办法让 ssdb 导入 rdb 吗？

**Comment by ideawu** [comment]
让 redis-server 以这个 rdb 文件作为数据启动(具体方法你去搜索一下).

**Comment by henry-zhuang** [comment]
你的意思是用 redis-server 启动这个 rdb 文件，再用 redis-import.php 导数据吗？

可是有一个问题，官方的 redis-server 也是启动不了这个 rdb 的。

**Comment by ideawu** [comment]
那你参考  redis-import.php 的源码, 自己写迁移脚本吧.
