### ISSUE TITLE
读性能严重下降

### ISSUE THREAD

**Issue by cugb1004101218** [ideawu/ssdb#737]
python client 数据量2000W左右，读取会超时，很长时间都没结果，但是在ssdb上用ssdb-cli可以查到这个数据。
求问解决方案，或者如何设置超时时间？

**Comment by cugb1004101218** [comment]
server.cpp(245): fd: 2451, link parse error, delete link  
会有这样的错误

**Comment by ideawu** [comment]
是不是用了python多线程?

**Comment by cugb1004101218** [comment]
是的

**Comment by ideawu** [comment]
请做好线程安全. 建议每一个线程创建一个 ssdb 连接实例.

**Comment by cugb1004101218** [comment]
如果1个线程在写，10线程读呢？会有影响吗？

**Comment by ideawu** [comment]
也有影响

**Comment by ideawu** [comment]
记住, 所有的编程语言和库, 如果没有明确说明, 默认都是线程不安全的. 切记!

**Comment by cugb1004101218** [comment]
如果B作为A的slave，然后1个线程写A，10个线程读B呢

**Comment by ideawu** [comment]
(重复我前面的回答).

**Comment by cugb1004101218** [comment]
谢谢！
