### ISSUE TITLE
Mac App下使用ssdb，setbit宏定义冲突

### ISSUE THREAD

**Issue by mysteriouss** [ideawu/ssdb#738]
编译参数 ios，生成.a,  在Mac App中使用

OS X 10.10/usr/include/sys/param.h:200
#define	setbit(a,i)	(((char *)(a))[(i)/NBBY] |= 1<<((i)%NBBY))

iOS没有此问题

**Comment by mysteriouss** [comment]
#if TARGET_OS_MAC
#undef setbit
#endif

**Comment by ideawu** [comment]
Hi 为什么把这个 issue 关闭了?

**Comment by mysteriouss** [comment]
把setbit的宏定义undef就可以了，编译通过了。

但是现在发现不能在本地保存数据
