### ISSUE TITLE
redis数据迁移到ssdb时报“Failed to AUTH connection”错误

### ISSUE THREAD

**Issue by palfeline** [ideawu/ssdb#748]
大牛好~最近在将项目的redis数据迁移到ssdb时报“Failed to AUTH connection”错误
迁移语句如下
```
cd /usr/src/ssdb-master/tools
php redis-import.php 127.0.0.1 6379 master 127.0.0.1 8888
```
问是否继续后点击Y就出现了如下报错
```
PHP Fatal error:  Uncaught exception 'RedisException' with message 'Failed to AUTH connection' in /usr/src/ssdb-master/tools/redis-import.php:136
Stack trace:
#0 /usr/src/ssdb-master/tools/redis-import.php(136): Redis->info()
#1 /usr/src/ssdb-master/tools/redis-import.php(56): scan_command_available()
#2 {main}
  thrown in /usr/src/ssdb-master/tools/redis-import.php on line 136
```
感觉问题应该出在redis设置了密码但ssdb未设置密码上，后来通过AUTH命令给SSDB也设置了密码，还是报这个错误。。。
还是新手。。。自行谷歌以及翻阅所有issues都没发现有这个问题的解决方案，如果太过简单，还请各位表嘲笑我~~~
多谢~

**Comment by ideawu** [comment]
Hi, 你能临时先把 redis 的 auth 去掉吗? redis-import 暂时不支持 AUTH

**Comment by palfeline** [comment]
多谢，去掉密码后，确实可以了

**Comment by palfeline** [comment]
您好，有关redis迁移到ssdb的问题，因为从redis迁移过去需要把密码暂时去掉，所以没法长期自动化去迁移，只能在目前我们的代码体系中所以使用redis的地方再加上数据写入ssdb的代码（因为某些复杂原因，没法把数据全部迁移至ssdb，只能两者并用，目前的想法是使用ssdb配合redis做冷热数据分离），然后就发现了一个问题：

我使用迁移脚本导入ssdb的数据格式和redis中仍旧是一样的，

比方说会有这样的一个hash数据：key是“reset_time”，value是“i:1437980400;"是个时间戳，

而我如果在代码中用ssdb的hset方法写入ssdb的数据，保存的key依旧是"reset_time"，但是value就是"1437980400"了，格式跟迁移脚本导进去的完全没法兼容。。。

而且我用ssdb的hget方法分别取了一下这两种数据，发现两者取出来的格式也是不一样的，

请问这种情况下有什么方式能规避一下吗？或者说我取数据的时候只能做一下判断或者先把迁移脚本写进去的数据做一下处理才能和普通写入ssdb的数据一起用呢？

多谢

2015-08-03 17:13 GMT+08:00 ideawu <notifications@github.com>:

**Comment by ideawu** [comment]
你好, 关于密码的问题, 你可以修改 redis-import.php 文件, 这个代码比较容易看懂, 试试吧.

关于value的那个问题, 我没弄明白你的意思. 而且, 这种奇怪的问题很容易得到验证, 你自己验证一下吧, 我分析是你弄错了.

ps, 你的母语不是中文?

**Comment by ideawu** [comment]
我再仔细看了下, 你是用 var_export 来打印 value 吧?

`i:1437980400`

是整数类型.

`1437980400`

是字符串类型.

对于 ssdb 或者 redis, value 都是字符串类型, 之所以出现整数类型, 是你的代码中做了类型转换. 请你务必再检查下自己的代码. 如果还有不明白的地方, 一定抽丝剥茧, 把业务相关的代码剥离, 使用极简的几行代码来验证下自己的想法.

**Comment by ideawu** [comment]
刚才说错, 不是 var_export(), 是 serialize().

__最重要的, 一定要简化问题, 然后自己去验证, 这样, 所以解答几乎所有的问题 - 掌握了这种简洁有效的学习方法, 有助于你.__

**Comment by palfeline** [comment]
好的，多谢~因为现在的项目是从外国人手里接过来的。。。代码还在熟悉中。。。我去尝试一下
P.S. 我是天朝土鳖，长这么大去过最远的地方是香港。。。抱歉表达有点不清楚让你误会了哈~

在 2015年8月6日 上午12:29，ideawu <notifications@github.com>写道：

**Comment by palfeline** [comment]
感谢ideawu提醒，决定放弃重新写数据到SSDB的做法，通过修改redis-import.php差不多第55行后位置的代码，添加$redis->auth('foobared');其中foobared是redis的密码，通过给redis授权，实现有密码情况下redis数据导入到SSDB中，这样可以通过定时脚本实现数据的实时导入。

**Comment by ideawu** [comment]
好的. 另外, value 的那个问题, 就是 serialize() 的原因, 你可以搜索代码中哪里调用了这个函数.
