### ISSUE TITLE
redis 客户端zadd问题

### ISSUE THREAD

**Issue by ylywyn** [ideawu/ssdb#751]
使用redis客户端jedis zadd时（数据带双引号），会有10%的几率，返回错误。
进一步测试，使用redis自带的redis-cli 连接ssdb：zadd key 10 123"1   (只要出现双引号，就出现参数错误)。 什么原因？

**Comment by ideawu** [comment]
你好, `Invalid argument(s)` 这个错误是 redis-cli 自己报的, 和 ssdb 没有关系. 如果你想在 redis-cli 里执行带双引号的命令和参数, 请使用下面这种方法:

```
127.0.0.1:8888> zadd key 10 '123"1'
(integer) 1
127.0.0.1:8888> 
```

**Comment by ideawu** [comment]
如果 ssdb 不支持双引号, 那么不会是 10% 的机率报错, 而应该是 100%. 所以, 反推得知: __应该是你的姿势不对!__

**Comment by ylywyn** [comment]
Invalid argument(s)确实是客户端自己的，但是它根据的是你返回的 -ERR \r\n出来的。 我试了你提供的JAVA的客户端，也是同样的错误（调试返回的-ERR \r\n）。同样的数据（就是一个json字符串, zadd），redis是不报错的。 是我的姿势不对吗？ 需要特殊配置吗？请测试一下，谢谢

**Comment by ylywyn** [comment]
貌似是姿势不对。 用你的客户端 ssdb.zset(key, member, score); 当member超过255 字节，就返回error. 之前是我的json字符串超过255个字节了。 我哪里设置错了吗？

**Comment by ideawu** [comment]
member 的最大长度是 255, 不能超过.

**Comment by ylywyn** [comment]
原来如此！ 非常感谢回复。实测是255。。
