### ISSUE TITLE
ssdb hashmap 怎么获取所有的key

### ISSUE THREAD

**Issue by syzh** [ideawu/ssdb#754]
hkeys name key_start key_end limit 通过这个命令无法获取hash里面所有的key，再ssdb里面可以获取所有的key吗

**Comment by syzh** [comment]
hkeys hash 'a', 'z', 10 此命令无法获取以z开头的key呢，只能获取a-y开头的key。 不知道是不是ssdb的bug ？

**Comment by ideawu** [comment]
__请务必要多看文档!__ http://ssdb.io/docs/commands/hscan.html

把参数设置为空字符串即可.

**Comment by syzh** [comment]
ssdb 127.0.0.1:8888> hscan hash 'a', 'z', 10
key             value
-------------------------
  kS              : skxx3
  xx0             : 1ds3
2 result(s) (0.001 sec)
ssdb 127.0.0.1:8888> hscan hash '', '', 10
key             value
-------------------------
0 result(s) (0.001 sec)


ssdb 127.0.0.1:8888> hkeys hash '', '', 10
              key
-----------------
0 result(s) (0.000 sec)
ssdb 127.0.0.1:8888> hkeys hash 'a', 'z', 10
              key
-----------------
               kS
              xx0
2 result(s) (0.000 sec)
还是无法获取hash所有的key

**Comment by syzh** [comment]
ssdb version: 1.8.0

**Comment by ideawu** [comment]
`hscan h "" "" 100`

**Comment by ideawu** [comment]
我倒! 谁让你带逗号分隔命令行参数?

**Comment by ideawu** [comment]
`hkeys hash 'a', 'z', 10` 我真是无语了, 谁教你的? 为什么前面不另逗号, 后面就加逗号? 加与不加, 你倒是说出个理由啊? 凭感觉的吗?

**Comment by chu8129** [comment]
遍历有什么技巧么？获取单个hashmap中所有的key需要很长时间；比如：类似游标这种；
