### ISSUE TITLE
cpp客户端多线程是否安全

### ISSUE THREAD

**Issue by grapeisme** [ideawu/ssdb#764]
在cpp中，启用多个线程对ssdb进行操作，是否线程安全。会不会出现类似socket通信数据串了的情况？

**Comment by ideawu** [comment]
是安全的, 前提是你需要为每一个线程创建单独的连接.

**Comment by grapeisme** [comment]
谢谢。
刚刚发现此前错看了客户端连接的建立为单例了
------------------------------------------------------------

Client* Client::connect(const std::string &ip, int port){
	static bool inited = false;
	if(!inited){
		inited = true;
		signal(SIGPIPE, SIG_IGN);
	}
	ClientImpl *client = new ClientImpl();
	client->link = Link::connect(ip.c_str(), port);
	if(client->link == NULL){
		delete client;
		return NULL;
	}
	return client;
}
