### ISSUE TITLE
Xcode 7 iOS-Build Problem

### ISSUE THREAD

**Issue by mysteriouss** [ideawu/ssdb#769]
libleveldb-ios.a(builder.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

libsnappy-ios.a(builder.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

libutil-ios.a(builder.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

libssdb-ios.a(builder.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

Reference:  http://karp.id.au/post/xcode_7_linker_rules/

**Comment by ideawu** [comment]
Thanks, it is ok now!
