### ISSUE TITLE
需求：是否应该增加类似Redis的LTRIM命令。

### ISSUE THREAD

**Issue by JesseBlackman** [ideawu/ssdb#774]
需求：是否应该增加类似Redis的LTRIM命令。
命令：ltrim(name,start,end)
作用：这个命令能够维护list的长度，比如说只需要最新的100条数据，每次插入完数据之后可以用这个命令保持一定的长度。zremrange  qpop 是删除指定区间（个数）的元素，而ltrim是保留指定区间内数据删除其他数据。
附图：（Redis LTRIM命令）
<img width="920" alt="qq20151006-1 2x" src="https://cloud.githubusercontent.com/assets/7440033/10309220/ec780502-6c6d-11e5-89be-e66fa2ccb9f4.png">

**Comment by ideawu** [comment]
已经有了 qtrim_front, qtrim_back  http://ssdb.io/docs/zh_cn/php/content.html#m-qtrim_front 等下一个版本再支持 redis 客户端.

**Comment by ideawu** [comment]
更正, 因为 redis 的 ltrim 参数格式是:

```
 LTRIM key start stop 
```

而 qtrim_* 的格式是:

```
qtrim_front name size
```

__所以, 无法兼容, 以后也不会改变, 这是最终决定.__
