### ISSUE TITLE
iOS EXC_BAD_ACCESS(code=EXC_ARM_DA_ALIGN)

### ISSUE THREAD

**Issue by mysteriouss** [ideawu/ssdb#776]
在 iPod touch 5, iOS 9.0 上调用 hset 出现以上错误，出错位置在 hsize 方法
t_hash.cpp  line 99: 
```
  int64_t ret = *(int64_t *)val.data(); 
```
修改为
```
  int64_t ret; 
  memcpy(&ret,val.data(),sizeof(int64_t));
```
即可

**Comment by mysteriouss** [comment]
qsize和zsize也是同样的问题

**Comment by mysteriouss** [comment]
好像因为这，我自己编译的，
在 32 位的 iOS 上，int64_t ret = *(int64_t *)val.data(); 的调用会出错 crash

@ideawu

**Comment by ideawu** [comment]
谢谢，你这个写兼容性更好，我会更新代码。

**Comment by mysteriouss** [comment]
Fixed https://github.com/ideawu/ssdb/commit/d2e0ba50f3e5f70430a6eb517f18a0ed84094905
