### ISSUE TITLE
Batch set with TTL (multi_setx)

### ISSUE THREAD

**Issue by felixbuenemann** [ideawu/ssdb#778]
There currently does not seem to be a way to set multiple items with expiry, so to do that one either has to do multiple calls to setx or a multi_set followed by multiple expire commands.

So I think it would be great to have a command like multi_setx to achieve this.

**Comment by ideawu** [comment]
Hi, you can use batch-exec provided by some client api(such as PHP). The batch-exec procedure buffers requests on client side, and send them all to the server before start receiving any response. This can reduce network rtt.

**Comment by felixbuenemann** [comment]
Yes, that's what I'm currently doing, pipelining multiple setx requests. So you think there is no real performance gain from having a single command?

**Comment by ideawu** [comment]
No significant performance gain on switching from pipelining multiple requests to a single request.

**Comment by felixbuenemann** [comment]
Thanks!
