### ISSUE TITLE
ssdb的zset的score不支持科学计数法，而jedis目前zadd的score都是用的double

### ISSUE THREAD

**Issue by yidongnan** [ideawu/ssdb#780]
使用jedis客户端zadd的score存在最大值限制？
超过7位数就会出现只保留首位的情况
也就是zadd("auto_reply_list", “20000000”,1);
一旦超过7位，score保存的就只是首位了。

在ssdb中看到的是 

```
key score
-------------
1       2
```

但是直接使用ssdb-cli add能成功
jedis版本2.7.2  ssdb1.8.2

**Comment by ideawu** [comment]
我不确定是否是 jedis 的问题, 你可以观察 ssdb 的 log.txt 看服务器收到的是什么?

**Comment by yidongnan** [comment]
log中是这样的
multi_zset auto_reply_list 9 1.0E8, resp: ok 0

但是我zscan查看到的是1
![image](https://cloud.githubusercontent.com/assets/3163314/10655279/ee1211fc-78a5-11e5-9a24-37254d3db3c1.png)

**Comment by yidongnan** [comment]
ssdbDao.zrangeByScoreWithScores("auto_reply_list", 0, System.currentTimeMillis()/1000, 0, 10)
同样zrangeByScoreWithScores这边调用的max出现指数同样不行了？
而目前jedis的zadd 和 zrangeByScoreWithScores都是传的double，不存在传string的方法。

**Comment by ideawu** [comment]
那就是 jedis 的问题, 它把数转成科学计数形式了:  1.0E8

**Comment by yidongnan** [comment]
@ideawu ssdb有计划支持科学计数法不？

**Comment by ideawu** [comment]
可以支持, 需要等下一个版本.

**Comment by ideawu** [comment]
已经支持了, 你更新下代码即可.
