### ISSUE TITLE
init.d scripts on ubuntu

### ISSUE THREAD

**Issue by ServeR00T** [ideawu/ssdb#791]
on the documentations you write the guide for centos, so ubuntu doesnt have chkconfig tool.

my note is that just add this command to auto startup the server
sudo update-rc.d ssdb.sh defaults
after putting ssdb.sh to /etc/init.d folder

**Comment by ideawu** [comment]
It should work.

**Comment by ServeR00T** [comment]
I know it "will" works but I'm asking you to update the docs
