### ISSUE TITLE
hclear删除了很多hash,为何磁盘空间占用没减少？

### ISSUE THREAD

**Issue by pengqi** [ideawu/ssdb#792]
如题。

**Comment by ideawu** [comment]
ssdb(leveldb)有自己管理磁盘空间的算法和机制, 不一定立即释放硬盘空间.

**Comment by pengqi** [comment]
哦 这点和MongoDB有点像。不能迫使它释放空间吗？ 我记得MongoDB里可以用db.repairDatabase()来释放空间。

**Comment by ideawu** [comment]
不能. 你就放心让 ssdb 来管理硬盘空间吧.

**Comment by larryzhao** [comment]
@ideawu 本地开发环境，删除后过了很多天，ssdb 还是没有释放磁盘空间，这个是为什么？肯定重启过了

**Comment by ideawu** [comment]
请仔细阅读FAQ: http://ssdb.io/docs/zh_cn/faq.html

**Comment by ideawu** [comment]
问: 我把一个, 两个, 或者所有的 key 都删除了, 为什么 SSDB 占用的内存和磁盘空间并没有释放?

答: SSDB 有自己策略来决定何时释放内存和硬盘占用, 你不能要求 SSDB 立即 释放这些空间. 而且, 即使数据库清空了, SSDB 仍然会保留一些信息, 因此仍然占用部分硬盘空间. 你不应该关心这个问题.

**Comment by larryzhao** [comment]
@ideawu 明白，FAQ我看过了，我不是想要他立即释放，是过了非常久，大概半个多月了，还是毫无变化，所以想请教一下。

**Comment by ideawu** [comment]
ssdb/leveldb 自己会决定何时, 如何__(是或者否)__释放硬盘占用, 你不要关心这个问题. 如果leveldb 决定不释放, 即使你等半年也不起作用. 另外, 如果 ssdb/leveldb 不释放硬盘占用, 你也无法要求它释放. 这个表述应该非常清楚了.

**Comment by ideawu** [comment]
如果你认为"额外"占用的空间是一个_问题_, 你需要提供足够的信息来说明, 它确实是一个_问题_. 例如, 它占用了多少, 你认为应该占用多少, 等等更多的足够合理的信息和数据.

**Comment by ideawu** [comment]
我会更新FAQ, 使表述更清晰, 将__立即__表述为__立即或者在某个时间或者基于某个其它条件__

**Comment by larryzhao** [comment]
@ideawu 我完全理解 FAQ 里的意思。也没有认为这是一个问题，在生产环境我是能够看到 SSDB 释放硬盘空间的，只是在本地我发现过了很久都没有变化，正好看到这个 thread 所以询问一下。

**Comment by pengqi** [comment]
我服务器是ssd的硬盘，快被它吃完了，删数据不起作用...

**Comment by ideawu** [comment]
@pengqi 你需要查清楚, 到底是删除的部分数据占的比例大, 还是未删除的部分数据占的比例大? 如果是, 那么是各是多大比例?

我需要非常清晰的指出大家的一个误区, 那就是, 有些同学认为硬盘上的每一个字节的空间都应该是被有效利用的. 这完全是书呆子式的认为. 我需要指出一个实践上的常识, 所有的数据库都会"浪费"内存和硬盘空间. 你只能给出足够的理由指出浪费的数字太大, __而不能指出浪费的数字不为零!__

看大家的反馈, 都是认为一点也别浪费. 看到这句话, 如果你本能地反对, 如果你不是这么认为, 请给出足够的理由和分析. 我在这里完全看到没有人提供一丁点的理由.

**Comment by pengqi** [comment]
删除的数据比例大，磁盘不够用了，导致系统正常工作了。最后不得不删除整个var目录，重装ssdb。

**Comment by ideawu** [comment]
__必须定量讨论!__

请不要在下面这些愚蠢的问题上再纠缠:

* 我删除了量为a的数据, 为什么硬盘空间没有一丁点减少?
* 我在时间点t2删除了量为数据a, 为什么在时间点t2的时候硬盘空间没有一丁点减少?

但是, 下面的问题可以讨论:

* 我删除了量为a的数据, 为什么硬盘空间没有减少b?
* 我在时间点t2删除了数据, 为什么在时间点t2的时候硬盘空间没有减少b?

其中 a 不一定等于 b, 这些问题只能讨论 a 和 b. 所以, 如果定量讨论, 都是愚蠢的.

**Comment by ideawu** [comment]
回 issue 的标题和提问, 答案非常明确:

__hclear删除了很多hash,为何磁盘空间占用不一定减少？__

**Comment by pengqi** [comment]
做人要谦虚

**Comment by ideawu** [comment]
这是做技术的人的智商吗? 

1. 如果你想对一个现象进行解释, 那么我告诉你一个解释.
2. 如果你想了解为什么是这个解释, 那么你就应该谦虚请教, 而不是叫你所请教的人谦虚!

非常明确, 这个issue讨论的是1. 如果还不明白, 简直是做人的智商问题, 而不是技术能力的问题了.

**Comment by ideawu** [comment]
补充一下:

问: hclear删除了很多hash,为何磁盘空间占用没减少？
答: ssdb(leveldb)有自己管理磁盘空间的算法和机制, 不一定释放硬盘空间.

如果接着问: hclear删除了很多hash,为何磁盘空间占用没减少？
那么只能答: 你傻逼! 没完没了地重复一个问题!

如果接着问: 为什么有这些算法和机制? 这些算法和机制的原因是什么?
那么我回答: 为什么不呢? 去读源码!
