### ISSUE TITLE
log输出时可能会有缓冲区溢出

### ISSUE THREAD

**Issue by pingworld** [ideawu/ssdb#798]
看了logv的实现，发现往buf中写log内容时并没有判断总长度，外部打印时可能会出现溢出。。当然，log的buffer已经很大了（4KB），这个问题可能不太容易出现。
![image](https://cloud.githubusercontent.com/assets/10278592/11034350/e9ab815a-8725-11e5-8868-3acb0f12c5a9.png)

**Comment by ideawu** [comment]
logv() 里使用的操作函数是 vsnprintf(), 并且正确判断了长度, 不会出现缓冲区溢出. 你能给出一个 case 吗?

**Comment by pingworld** [comment]
哦，好吧，我看错了，不好意思！
