### ISSUE TITLE
Help...运维不小心删除数据存储文件，请问有读取尚存数据的方法么？

### ISSUE THREAD

**Issue by AnotherGoogleFans** [ideawu/ssdb#804]
运维为了删除部分老旧数据，直接在data文件夹下删除了几个日期比较老旧的文件。
现在整个ssdb都打不开。
那些删除的数据文件根据日期看确实是不需要的数据，现在里面还存在很多的数据文件，请问还有方法可以打开么？
不需要恢复已删除数据，只求能打开现存数据即可。

**Comment by AnotherGoogleFans** [comment]
OK, 修复了一下数据，就可以正常打开了。Close this issue。

**Comment by AnotherGoogleFans** [comment]
根据运维那边的反映，修复完以后，形式上是可以打开了，但其实并没有生成对外访问端口，也不能真正地正常工作，SSDB会一直内存持续膨胀直到被Linux内核给kill掉。。还是请教下作者，看有没有什么方法

**Comment by ideawu** [comment]
我不是很明白你所描述的. 你们可以看看 log.txt.

**Comment by AnotherGoogleFans** [comment]
具体描述一下：
运维管理员为了删除一些老的数据。直接在删除了一些data文件夹下创建日期以及修改日期比较老旧的文件，直接造成了ssdb无法启动。运维找我，我提交了这个issue。
后来运维管理员尝试使用数据修复工具对数据文件进行了修复，ssdb服务可以启动了，以为正常了，于是反馈说ssdb恢复了。于是我关闭了这个issue。
但后来发现，这次其实并不是真正的恢复。ssdb始终无法生成可对外访问的端口。内存会一直暴涨直到系统内存耗尽，进程被linux内核干掉。将修复后的数据文件暂时mv到别处时，同样配置启动ssdb，一切正常。也就是说，问题出在被修复后的数据。
很显然用直接修复的方式是无法恢复ssdb的数据文件的。
现在的问题是，有没有什么办法，可以读取到那些尚未删除的数据文件里所存储的数据。

**Comment by ideawu** [comment]
> 将修复后的数据文件暂时mv到别处时，同样配置启动ssdb，一切正常。
说明修复后的数据是正常的.

"你们可以看看 log.txt, 确认下配置文件等." 我说过的话, 一般不愿意重复. 你必须照着我说的去做. 如果做不对, 那就把 tail log.txt 发出来, 把配置文件发出来.

**Comment by ideawu** [comment]
跟你分享一条经验, 无论你用的是什么软件, 只要出问题, 首先, 看 log.

**Comment by ideawu** [comment]
在你一直不贴出配置文件之前, 我给你的建议是: 请你恢复成默认的配置文件, 不要修改里面的参数. 然后打开终端 tail -f log.tx, 再打开另一个终端 ./ssdb-server ssdb.conf -s restart

**Comment by AnotherGoogleFans** [comment]
![96c9h 23 kf6sat6 fj9gr](https://cloud.githubusercontent.com/assets/6881899/11234679/64fa77cc-8e05-11e5-9f2b-8b0a425291f1.png)
将咱们的数据挂载到默认目录，配置文件使用默认的配置项启动时，就一直到这里，日志不再刷新，而此时，内存一直升，如下图，直到被OOM机制给kill掉
![1 x vimmd5ab j1e28zmsv](https://cloud.githubusercontent.com/assets/6881899/11234668/48ba9d6c-8e05-11e5-8769-2dc008db9f60.jpg)

**Comment by ideawu** [comment]
Hi, 你的问题现在已经大致清楚了. 解决方案:

1. 把修复后的数据拷贝到一台内存大一些的机器
1. 在大内存机器以备份后的数据启动 ssdb-server
1. 停止大内存机器上的 ssdb-server
1. 将大内存机器上的数据文件拷贝回原来的机器启动.

原因:

repair 后的数据内部顺序比较乱, 所以 ssdb 启动时会进行整理, 整理过程占用了太多内存.

**Comment by AnotherGoogleFans** [comment]
OK。Thank U so much。

**Comment by ideawu** [comment]
@AnotherGoogleFans 搞定了?

**Comment by AnotherGoogleFans** [comment]
不是很确定，ssdb的数据库文件比较大，有400多g。运维工程师正在进行迁移。估计明天才知道结果。
但，原因很可能是你所说的。repair以后内存就会一直增加，表现也与你所预测的一致。

**Comment by ideawu** [comment]
如果你们的服务器内存比较小, 建议把配置文件中的数值改小, 避免以后再发生类似的问题:

```
write_buffer_size: 16
```

这个参数调小, 一般使用不会有问题, 但大并发写入可能会有性能下降.

**Comment by AnotherGoogleFans** [comment]
OK ，Thank U。We'll try.
