### ISSUE TITLE
ssdb配置文件中 leveldb:compression选项

### ISSUE THREAD

**Issue by WangRM88** [ideawu/ssdb#814]
你好，请问ssdb配置文件中 leveldb:compression选项，可以选择yes和no， 为了确认它的作用，我在双主节点中，一个配置了yes，一个配置了no，然后发现，使用yes的节点，通过dbsize查看时数值比no的那个节点小。

请问： 这个选项是用来存储落地数据的文件进行压缩吗？ 
这个压缩会不会影响到数据的访问？ 会不会影响ssdb的效率？
一般双主情况下leveldb:compression选项建议是yes还是no ？

**Comment by ideawu** [comment]
是的, 压缩硬盘上的数据文件. 这个选项不会对数据访问性能有不良影响. 默认的配置文件就是推荐的, 所以是yes.

**Comment by WangRM88** [comment]
@ideawu  那会不会比如我每秒能访问100万条数据，结果硬盘数据文件被压缩后，远小于这个值呢？

**Comment by ideawu** [comment]
已经回答过了, 不要重复提问相同的问题.

> @ideawu 那会不会比如我每秒能访问100万条数据，结果硬盘数据文件被压缩后，远小于这个值呢？
