### ISSUE TITLE
ssdb如何实现增删改查中的查呢？

### ISSUE THREAD

**Issue by ijob456** [ideawu/ssdb#816]
ssdb如何实现增删改查中的查呢？

**Comment by ideawu** [comment]
SSDB 入门基础(Chinese).pdf http://ssdb.io/ssdb-get-started.pdf
SSDB 官方网站和文档: http://ssdb.io/

**Comment by LeMoussel** [comment]
Is there such documentation in English?

**Comment by ideawu** [comment]
@LeMoussel sorry, there is not "SSDB 入门基础.pdf" in English, but other docs have en version, in http://ssdb.io/
