### ISSUE TITLE
The Questions about logger.level

### ISSUE THREAD

**Issue by stillicel** [ideawu/ssdb#826]
[文档] (http://ssdb.io/docs/zh_cn/config.html) 说：

> 日志级别
> 支持的日志级别有: debug, warn, error, fatal.
> 一般, 建议你将 logger.level 设置为 debug 级别.

但根据我的测试来看，似乎也支持info级别。
是不是这样呢？
还有没有其它log level，例如trace ？

多谢。

**Comment by ideawu** [comment]
支持的都列出来的. 不支持 trace.

**Comment by stillicel** [comment]
了解。
多谢快速回复。
