### ISSUE TITLE
The Questions on SSDB Binlog

### ISSUE THREAD

**Issue by stillicel** [ideawu/ssdb#827]
关于SSDB的binlog，有几个问题想问一下：

1. 配置项目replication.binlog设置为yes的状况下，binlog文件会存放在何处(假定SSDB放置在/data/ssdb/下，而work_dir = /data/ssdb/var)？或者SSDB的binlog只存在于内存里吗？

2. 从下述启动日志来看, binlog capcity被设置为20,000,000。请问这个设定值是固定的吗？或者在Server启动过程中动态决定的？ (我希望对SSDB运行过程中内存和磁盘的大小做一个大致的估算)

> 2015-11-27 00:50:43.145 [INFO ] ssdb-server.cpp(46): ssdb-server 1.9.2
> 2015-11-27 00:50:43.145 [INFO ] ssdb-server.cpp(47): conf_file        : /data/ssdb/ssdb.conf
> ...
> 2015-11-27 00:50:43.145 [INFO ] ssdb-server.cpp(60): binlog           : yes
> 2015-11-27 00:50:43.145 [INFO ] ssdb-server.cpp(61): sync_speed       : -1 MB/s
> 2015-11-27 00:50:43.152 [INFO ] binlog.cpp(175): binlogs capacity: 20000000, min: 1, max: 3,
> ...

**Comment by ideawu** [comment]
1. 对于 `work_dir = /data/ssdb/var`, 数据放在该目录下的 data, meta 两个文件夹里. binlog 和数据一起, 在 data 文件夹里.

2. 你可以修改 binlog.capacity 然后重启生效. 建议你用默认的即可.

**Comment by stillicel** [comment]
Hi,

明白了。
多谢回复！
