### ISSUE TITLE
ssdb keys时间复杂度

### ISSUE THREAD

**Issue by qixiaobo** [ideawu/ssdb#836]
1.对于ttl不支持非kv类型，因此想要ttl必须使用kv。
从redis迁移（原set）切换成k-v。
名称采用a_xxxx等作为key。
获取set使用keys "a_" "a_\xff" 100000 
该命令不会阻塞整个操作么？
原来redis中基本上不允许执行keys命令
2.如果磁盘一直写满了怎么办？
   自动触发lru？没有使用过leveldb，不太清楚原来的机制

**Comment by ideawu** [comment]
1. 不会阻塞其它操作
2. 操作系统的磁盘应该由运维人员来保证不会满, 否则后果不可预期. leveldb 是持久化存储, 不会使用lru机制删除任何有用数据.
