### ISSUE TITLE
ssdb server not starting on Centos

### ISSUE THREAD

**Issue by Ceyword** [ideawu/ssdb#839]
Hi @ideawu,
I did :
$ ./ssdb-server ssdb.conf
and got back :
ssdb-server 1.9.2
Copyright (c)  2012-2015 ssdb.io
error opening log file:log.txt 
The server will not start. What could be the problem here?
Thank you

**Comment by ideawu** [comment]
It is file/directory permission thing. Use root user to start ssdb if you really don't what's that about:

```
sudo ./ssdb-server ssdb.conf
```

**Comment by Ceyword** [comment]
Yes, changing to root user fixed this. Thank you.
