### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by aigninja** [ideawu/ssdb#849]
Can we use ssdb for production use? 

In issues, most of tickets are logged in chinese language. Will you provide similar support in english?

**Comment by ideawu** [comment]
Hi, ssdb is ready for production use, ssdb is widely used by large companies and small companies, see ssdb user list in: http://ssdb.io/docs/users.html

Feel free to post GitHub issues in English here, most project watchers of this project understand English.

**Comment by aigninja** [comment]
Thanks for quick answer. I am starting to use ssdb to replace redis ( want
to persist data)

**Comment by yehosef** [comment]
this should be closed..
