### ISSUE TITLE
rockdb升级问题

### ISSUE THREAD

**Issue by MichaelXucf** [ideawu/ssdb#853]
你好，我下载了rockdb版的ssdb,发现使用的ssdb版本还是1.6.8.8. 现在使用leveldb的ssdb版本已经到了1.9.2.  我如果要升级rockdb版的ssdb，需要做哪些更改呢？是否只要按照http://www.ideawu.net/blog/archives/799.html  里写的做就可以呢？

**Comment by ideawu** [comment]
你自己尝试下, 毕竟你既然有这个需求, 说明你已经有了大致的能力.

**Comment by MichaelXucf** [comment]
好的，谢谢，那我先自己试下。
由于redis容量的原因，我们目前是打算用ssdb来替换现在使用的redis。 所以ssdb还是刚开始使用，从您的博客上了解到目前ssdb是支持两种存储引擎：leveldb和rocksdb. 目前还是在选型，两种ssdb我都安装好了，用ssdb-bench跑了几个测试，还是leveldb更快一点。
leveldb版的ssdb一直是有官方在升级的。考虑到如果使用rocksdb版的ssdb, 有个升级维护的问题，所以跟您请教下哈

**Comment by ideawu** [comment]
如果你是生产使用, 推荐使用 leveldb 版, 因为这个版本更流行, 经过了非常广泛的实践检验.
