### ISSUE TITLE
Big O Notation for hsize, zsize and qsize

### ISSUE THREAD

**Issue by Lockhead** [ideawu/ssdb#854]
Can somebody provide information about these functions, are they O(1), O(linear) or O(log)?
---
My use case: I have about 400 million hashmaps and there are 2 types of data in them. I want to know how much hashmaps belong to which type. It's easy for me to simply add them on creation to an additional hash or set, but if the *size functions are O(n) or harder then I need to implement another solution...

**Comment by ideawu** [comment]
Hi, hsize, zsize, qsize is O(1), at the aspect of leveldb.
