### ISSUE TITLE
ssdb服务器的硬盘和内存配置疑问

### ISSUE THREAD

**Issue by safecat** [ideawu/ssdb#856]
根据ssdb文档，如果cache_size设为500M，write_buffer_size为64（默认），则内存占用的峰值=cache_size + write_buffer_size \* 66 + 32=4756M。这是不是说，我要上一台6g内存左右的机器来跑这个ssdb？如果是这样，感觉挺浪费的。。毕竟这台SSDB的日常占用根本没有那么高。这中间有没有个换算公式或者常见的配置方式呢。

另外，因为文档中没有写ssdb如何管理硬盘存储，所以硬盘配置也没法计算。比如现在redis里有10G的数据，想要转到ssdb中，可能我现在测下来发现ssdb里这个数据可能要占20G（没测过，只是打个比方），但是读写过程中这20G有没有可能会膨胀到某个很大的数值，比如100G。

麻烦ideawu大神解答一下，非常感谢！

**Comment by ideawu** [comment]
1. 内存占用是最极端的情况, 根据经验, 你上一台2g内存机器即可.
2. 请做合理的推测, 不要做不靠谱的推测. 或者, 如果不知道自己在做或者说什么, 就不要做推测.

**Comment by safecat** [comment]
问题是文档中没有写明，小数据量中发现是会膨胀的很厉害。
既然内存峰值是存在的，那么推测也是合理的。
模拟线上数据量很简单，但是访问情况很难，先问个标准答案不好么。
