### ISSUE TITLE
SSDB Logger folder

### ISSUE THREAD

**Issue by mersed** [ideawu/ssdb#857]
Is it possible to change folder for logs to something like "/var/log/ssdb/" using just configuration setup?

**Comment by ideawu** [comment]
Yes, you are able to set absolute path for `logger.output`, like `/var/log/ssdb.log`, I will update the docs soon.

**Comment by mersed** [comment]
Thanks for your reply. So basically, i can store all logs within one file (without specifying rotate property within configuration) and in folder which i want, and then afterwards use logrotate to rotate/remove logs older then specific time. 

I can see (based on documentation) that ssdb supports rotation but it does not support removing logs, so there is more sense to use logrotate for rotation and removal, instead of built in ssdb rotation and then write custom cron job to remove older logs. 

Do you see any kind of issues with approach i described above?

**Comment by ideawu** [comment]
You cannot use logrotated for log rotation of log.txt, because ssdb never expect this, the result will be unexpected.

Let ssdb rotate the log file, then use crontab to remove or compress old log files.

**Comment by mersed** [comment]
Actually it seems that this works just fine. You need to create your own "/var/log/ssdb/" folder with proper permissions of course.


Logrotate:
/var/log/ssdb/ssdb.log {
    missingok
    notifempty
    compress
    copytruncate
    daily
    rotate 35
    create 0750 user usergrp
}


Ssdb conf logrotate part:
logger:
        level: debug
        output: /var/log/ssdb/ssdb.log

It is tested over the weekend. Logs are rotated and compressed properly.
From my perspective usage for logrotate (instead of writing own cron script) is much easier (even cronscript is simple as well), because it require a usage of well known tool on unix distributions wich allows you to simply specify parameters for rotation/compress you want.
Additionally if you are writing a script for installation of more then one third party software it simplify situation a little bit.

**Comment by ideawu** [comment]
Hi, you should change

```
/var/log/ssdb/ssdb.log {
```
to
```
/var/log/ssdb/ssdb.log.* {
```
because `ssdb.log` is the file being used. only apply lograte.d routine on log files that are already rotated(file name in the format like `log.file.name.20160105-104356`).
