### ISSUE TITLE
TAB真的不好输入，有点烦恼

### ISSUE THREAD

**Issue by wonderbeyond** [ideawu/ssdb#858]
TAB按键早都被大家伙的主流编辑器配置给灭了，按TAB就是四个空格，真要让我输入tab，我还得找个地方复制，但是有的编辑器一粘贴进来又是空格。

另外我个人的主要编辑器已经不是Vim了（vim可以非常方便的针对单个文件配置编辑选项），现在我主要用Atom，但是Atom暂时还不知道如何仅针对单个文件修改Tab配置。

我觉得用tab还是空格这点小事儿，没必要限制死了图增烦恼。

**Comment by wonderbeyond** [comment]
我现在会临时只用vim修改 ssdb.conf，但我不能确保哪天不小心用其它编辑器把配置文件搞乱了（tab被替换成空格）。

**Comment by ideawu** [comment]
正如文档中明确提到的:

> SSDB 的配置文件使用一个 TAB 来表示一级缩进, 不要使用空格来缩进, 无论你用2个, 3个, 4个, 8个, 或者无数个空格都不行! 

我从来不对键盘做映射, 输入a就是a, 不会把a映射成b, 所以也不会把TAB字符映射成其它字符.
