### ISSUE TITLE
这个前缀查询如何理解？

### ISSUE THREAD

**Issue by Longjianghu** [ideawu/ssdb#870]
ssdb 127.0.0.1:8888> hscan h 'a*' '' 10
key             value
-------------------------
  a1              : 1
  a11             : 11
  a12             : 12
  a2              : 2
  a3              : 3
  b               : 2
  b1              : 1
  b2              : 2
  b3              : 3
  c               : 3
我还以为有点类似于正则，但是发现好像没什么用。如何理解这个前缀查询？

**Comment by qixiaobo** [comment]
表示以 a为前缀最多后面10个hash

在 2016年02月03日 16:04, Longjianghu 写道:

**Comment by ideawu** [comment]
http://ssdb.io/docs/zh_cn/faq.html
__注意, 这些命令都要求你省略 * 号!__
