### ISSUE TITLE
out of box redis-benchmark not working but redis-client works

### ISSUE THREAD

**Issue by chalianwar** [ideawu/ssdb#879]
Hi,

First, I would like to thank you for open sourcing this project. It's very well written and easy to understand.

I have question regarding redis client support in ssdb. I tried to find if there already exists a similar issue but as some of the issues are reported in Chinese so I do not know if what I am asking is a duplicate or not.

I am able to use redis-client which comes with redis by default but redis-benchmark is not working. I tried redis 2.6.0 and redis 3.0.7. Should I have to write my own benchmark or do you know any benchmark which can just work out of box?

Thanks in advance.

**Comment by ideawu** [comment]
Hi, the problem is that redis-benchmark execute a `PING` request which follows the older Redis 1.0 protocol, not the newer Redis 2.0 protocol. Other commands, such as `GET, SET` follows the newer protocol, so you have to specify the commands to benchmark, like:

```
./redis-benchmark -p 8888 -t set,get
```

**Comment by chalianwar** [comment]
Thanks, it solved the problem.
