### ISSUE TITLE
kv expire机制咨询

### ISSUE THREAD

**Issue by liuhualh** [ideawu/ssdb#885]
我在测试kv的expire机制时，ssdb-cli输入如下序列

set k1 100
get k1               # 获取k1的值为100
expire k1 100   #设置过期时间: 100s
del k1               #删除k1，**同时期望删除k1对应的ttl**
get k1               #获取k1，不存在，返回not_found
ttl k1                 #获取k1的生存时间，期望是找到不，但实际上仍可获得k1的ttl

set k1 200        #设置k1新的值
**原来没有删除的k1 ttl会将新值也删除**

请问这是bug吗？ 还是我有些地方理解不对

谢谢~

**Comment by ideawu** [comment]
请问你用的是什么版本. 我在最新的版本并没有这个问题.

**Comment by liuhualh** [comment]
刚刚用master分支上的最新(30bec9c51eeec162ef7b6e424a778b25146b131a)试了下还是相同现象

![image](https://cloud.githubusercontent.com/assets/3794741/13421309/8e43cd58-dfc8-11e5-8cb5-8dbabcd6a71d.png)

￼

**Comment by ideawu** [comment]
重现步骤:

1. 启动一个全新的空db
2. 执行下面的操作

```
setx a 1 100
del a
get a
ttl a
```

**Comment by liuhualh** [comment]
已验证通过，谢谢

**Comment by ideawu** [comment]
@liuhualh  谢谢你的参与!
