### ISSUE TITLE
硬盘扩容后问题

### ISSUE THREAD

**Issue by 6api** [ideawu/ssdb#889]
当硬盘写满后，扩容了硬盘，持续写入占用空间却不再增加，固定在了未扩容前的固定大小了，这是为什么，然后看SSDB的IO基本是几十MB/s
未扩容前写入一直持续增加空间占用
我所有的K都有过期时间，不过都很长，几个月，都还没有过期
会不会跟这个有关系？

**Comment by 6api** [comment]
version
	1.9.2
links
	8
total_calls
	715552
dbsize
	85999331976
binlogs
	    capacity : 20000000
	    min_seq  : 0
	    max_seq  : 0
serv_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
data_key_range
	    kv  : "0000004de3b22f5747bf88b3c60cb3f2" - "fffffebb9142fb06e0d06cfbd3fcac02"
	    hash: "" - ""
	    zset: "\xff\xff\xff\xff\xff|EXPIRE_LIST|KV" - ""
	    list: "" - ""
leveldb.stats
	                               Compactions
	Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
	--------------------------------------------------
	  0        0        0        29        0      1124
	  1        1       22        38     1444      1440
	  2       70     1596       341     9519      9507
	  3      537    16013      3034    82846     82670
	  4     2081    64384     12078   322155    321815
	
17 result(s) (0.001 sec)

**Comment by ideawu** [comment]
在你的总数据库有80+G的情况下, 少量增删数据是很难明显影响到操作系统的硬盘空间占用的. 你可以放心使用.

**Comment by 6api** [comment]
我也很奇怪，每天的写入量都有5至20G，原来是100G，硬盘满了之后，SSDB没有挂，还持续服务着，剩余空间基本为0
扩容以后，今天写入量大概也有10G，空间占用没怎么变化，还是刚好100G
看IO占用，应该一直在COMPACT，IO高了一天降下来了，可能SSDB压缩后空间减少抵扣了新增量，我再观察看看

ssdb-server 1.9.2

ssdb 127.0.0.1:8888> info
version
	1.9.2
links
	2
total_calls
	1887511
dbsize
	87890554346
binlogs
	    capacity : 20000000
	    min_seq  : 0
	    max_seq  : 0
serv_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
data_key_range
	    kv  : "0000004de3b22f5747bf88b3c60cb3f2" - "fffffebb9142fb06e0d06cfbd3fcac02"
	    hash: "" - ""
	    zset: "\xff\xff\xff\xff\xff|EXPIRE_LIST|KV" - ""
	    list: "" - ""
leveldb.stats
	                               Compactions
	Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
	--------------------------------------------------
	  0        0        0        54        0      3252
	  1        6      130        96     4039      4031
	  2       63     1562       850    24887     24866
	  3      556    16000      7198   200768    200504
	  4     2126    66127     31075   821320    820756
	
17 result(s) (0.001 sec)
