### ISSUE TITLE
设置了expire的key，没达到超时时间就被删除的问题

### ISSUE THREAD

**Issue by smartian1** [ideawu/ssdb#891]
@ideawu ，测试时发现一个问题：
1. 双主模式，A和B
2.A和B中已经插入了大量的数据，且这些数据设置了expire时间，info信息如下
![qq 20160308153848](https://cloud.githubusercontent.com/assets/12165971/13595128/e2513810-e543-11e5-8cd3-39eb8a007247.png)

3.此时用ssdb-cli，插入一个带有expire时间的key，但是发现没到过期时间，这个key就被删除了
![qq 20160308154042](https://cloud.githubusercontent.com/assets/12165971/13595171/26a82d2a-e544-11e5-8e14-5e035847cd17.png)

上图中的每个命令之间都是大概间隔一秒，所以我设置的那个300秒的过期时间，是还没有到的

**Comment by ideawu** [comment]
你把log.txt打开成debug, 仔细观察log.

**Comment by ideawu** [comment]
这个问题很可能是你的两台服务器时间相差太多.

**Comment by smartian1** [comment]
@ideawu ，嗯，确实是因为服务器时间相差太多导致

请教一下，双主模式下，某个设置了过期时间的key从A同步到了B，当达到过期时间时，ssdb内的删除机制是怎样的呀？为何服务器时间相差太多的情况下，就会出现上面说的那个情况呀？

能大概讲讲其中的机制么，谢谢大神啦：）
