### ISSUE TITLE
key 的长度为什么限制在 200 字节？

### ISSUE THREAD

**Issue by yiding-he** [ideawu/ssdb#896]
这个是 LevelDB 的限制吗？能否通过修改源代码中的某个常量来调整这个限制？我这边的业务可能需要 key 长度达到400~500 字节的样子，不知道 SSDB 能否有某种方法来满足。

我测试了一下，发现这个所谓 key 最大长度是用来限制 hset 的，对一般的 key 没有这样的限制。

**Comment by ideawu** [comment]
这个是历史原因, 因为拼装key时, 用一个字节进行编码表示长度.

对于你的业务, 只能存储key的md5值.
