### ISSUE TITLE
客户端能否使用异步？

### ISSUE THREAD

**Issue by sukui** [ideawu/ssdb#900]
我用php写了一个异步的客户端，但是读取服务器返回操作的时候没办法确定是哪个操作。

所以我想咨询一下是否支持传入一个自定义参数，服务器返回操作结果跟用户自定的参数.

**Comment by sukui** [comment]
这个可能需要服务端修改一下协议部分。不怎么懂C++,所以问问作者有没有支持这种的可能？

**Comment by ideawu** [comment]
一般地, 我们说的"异步"是一种思维方式和语法糖, 和服务端没有任何关系. 如果你要使用异步, 需要认真了解你所使用的语言, 看看这种语法糖是怎么回事.

**Comment by sukui** [comment]
嗯. 因为我用的都是同一个 sokect 发送数据. 所以才想要自定义参数.
