### ISSUE TITLE
我的一个业务场景发生变化，不再适合ssdb，请问有没有迁移回redis的办法？

### ISSUE THREAD

**Issue by Hisoka-J** [ideawu/ssdb#901]
这个业务的读取量增长的太大，读取达到了1秒90万，而我们目前的ssd硬盘无法支撑了，需要迁移回Redis集群。数据结构都是hash和set类型。

**Comment by ideawu** [comment]
你需要自己写脚本遍历ssdb, 然后把数据写回redis. 遍历ssdb的代码你可以参考 ssdb-cli 或者 phpssdbadmin, 具体就是对不同的数据结构调用 *scan 类命令, 分页遍历.

**Comment by Hisoka-J** [comment]
谢谢，我去试试
