### ISSUE TITLE
SSDB 是否适用于存放大量小文件？

### ISSUE THREAD

**Issue by yiding-he** [ideawu/ssdb#902]
我有大量小文件（10-200KB）需要保存，根据 SSDB 的 API，我无法存放 byte 数组，不过可以将文件内容转为 Base64 字符串（大小增加 33% 左右）。所以我想确认 SSDB 有没有什么其他限制，以至于不适合存放大量小文件？

**Comment by ideawu** [comment]
没有这方便的限制. 请问, 你说的"无法存放byte数组"是因为什么原因? 对于ssdb来说, 二进制就是字符串, 字符串就是二进制.
