### ISSUE TITLE
Still have peer disconnect trouble

### ISSUE THREAD

**Issue by tchncs** [ideawu/ssdb#906]
Hi, we are using this awesome ssdb for our minetest server.
Sadly our players have trouble with: 
```
ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=227 disconnecting peer!
```

````
 ~ % ulimit -Sn
999999
 ~ % ulimit -Hn
999999
~ % cat /proc/sys/fs/file-max                                                                             :(
100000
````

...its a Debian 8.3

I really dont know where i have to ask, so i ask you here and hope thats welcome.

**Comment by ideawu** [comment]
Hi, `ERROR[Server]: Server::ProcessData(): Canceling: No player for peer_id=227 disconnecting peer!` is most probably something not related to the DB system. I know little about minetest server, so I can't help. I think you will get much help if yout ask the minetest server developers.

**Comment by tchncs** [comment]
Hi, thanks for your answer.
I did a /clearobjects to remove all objects and mobs on the map - and magically it didnt happened again. :)
I just asked here because its a very similar error as in the warning of your docs.
Thank you for ssdb, we love it!
