### ISSUE TITLE
请问lrange 这个指令支持吗？

### ISSUE THREAD

**Issue by mineralres** [ideawu/ssdb#907]
我用redis-cli.exe 连接到ssdb， 测试了lpush , lpop, llen这些指令都正常， 测试到lrange的时候就提示(error) ERR Unkown Command: lrange

**Comment by ideawu** [comment]
由于你提供的信息比较少, 所以我猜测你在使用一个非常老的不支持 lrange 的版本. 解决方法是升级到最新的版本.
