### ISSUE TITLE
ssdb-cli 问题

### ISSUE THREAD

**Issue by lixiaominggit** [ideawu/ssdb#909]
ssdb-cli可以与redis-cli一样在后台运行么？也就是有个后台运行的脚本使用ssdb-cli

**Comment by ideawu** [comment]
如果你指的是 echo "get a" | /usr/local/ssdb/ssdb-cli 类似的用法, 这是可行的. 例如, 你在后台运行的脚本中这么写:

```
echo "get a" | /usr/local/ssdb/ssdb-cli > a.txt 2>/dev/null
```

那么 a.txt 中将得到 key 为 a 的值.
