### ISSUE TITLE
ssdb双主恢复时 cpu 100%

### ISSUE THREAD

**Issue by level077** [ideawu/ssdb#911]
根据之前issues中提到的数据迁移方法，将现有ssdb的data目录拷贝到新的节点做双主。
现有A,B两个节点，双主配置。A节点data有50G的数据大小（开启压缩），A的binlogs.max_seq为900000000+，B节点无数据，两节点均无meta目录。启动两个节点后，两个节点均进入COPY状态，但此时A节点无法做set操作，get可以。CPU显示一个核为100%，perf top看到CPU主要是在操作leveldb::InternalKeyComparator。
如果AB改为主从模式，正常。
这个双主情况下出现的问题，不知如何解决？

**Comment by ideawu** [comment]
A节点有data, 而B节点无data, 设为双主启动后, A应该立即变为sync状态, 而B处于copy状态. 你所描述的是两个节点同时处于copy状态, 并且一直保持copy状态, 这不是预期的状况.

请检查一下配置文件是否配置错误?

**Comment by ideawu** [comment]
另外, 歌词加入qq群: 170983373

**Comment by level077** [comment]
配置就是简单的mirror，meta目录都是删掉的。
无数据启动，或者是少量数据时，启动后双方很快就到了sync状态。
本意味等B节点复制完后，双方就会进入sync，但是因为数据太多，所以这个就无法验证了。
A节点处于copy时，有一个CPU 100%，其他核都是空闲的。但是数据无法set，get是可以的。

**Comment by NineF** [comment]
我这边也出现这个问题,请问怎么解决的,谢谢
