### ISSUE TITLE
hincrbyfloat

### ISSUE THREAD

**Issue by colorgmi** [ideawu/ssdb#912]
请问，我想要redis中的hincrbyfloat这个命令，该怎么做？
能不改源码吗？

**Comment by ideawu** [comment]
不支持浮点数, 改源码不太现实. 我提供一种解决方案, 你可以参考:

把你要存储的数值扩大1000倍(3位小数精度), 转成整数后存储, 当想累加 0.001 时, 就 hincr a 1000.

**Comment by colorgmi** [comment]
谢谢建议。
但是我们这个应用，需要支持任意的浮点数，我还是尝试改下源码方便用些；好像就是加下外围的代码。
