### ISSUE TITLE
version bump on jemalloc

### ISSUE THREAD

**Issue by zhouyuan** [ideawu/ssdb#913]
Hi,

Jemalloc 3.3.1 is quite old(March 6, 2013). According to the [changelog](https://github.com/jemalloc/jemalloc/blob/dev/ChangeLog), there're number of bug fixes and optimizations merged since then. Some of them may reduce the allocation overhead. Is it possible to do an upgrade on the jemalloc code?

I did a simple test with jemalloc-4.4.1 here, looks like it's working.

thanks, -yuan

**Comment by ideawu** [comment]
Thank you for your advice, I have upgraded jemalloc to 4.1.0 on dev branch.

**Comment by bwzhang2011** [comment]
@ideawu, 可否考虑升级jemalloc到4.2.1
