### ISSUE TITLE
阶段性高IO导致性能下降

### ISSUE THREAD

**Issue by larryzhao** [ideawu/ssdb#914]
您好，

我在我们生产服务器上发现这样一个情况，大概每隔20-60分钟，磁盘就会有一次峰值 Load，下图是一个示例:

<img width="436" alt="screen shot 2016-04-14 at 11 12 28 am" src="https://cloud.githubusercontent.com/assets/442278/14516074/0799ee7c-0232-11e6-9bc4-bca284f32d38.png">

这时候同时系统 Load 会上升， SSDB 响应时间会上升的蛮厉害的。我们这台 server 现在 `ssdb/data` 在磁盘上占用大小是 84G，参数配置如下:

![1 pic](https://cloud.githubusercontent.com/assets/442278/14516170/e0b4c6d2-0232-11e6-96e8-86d8cad8ba96.jpg)

SSDB Info 命令反馈如下:

```
version
	1.9.0
links
	491
total_calls
	383906737
dbsize
	88179350688
binlogs
	    capacity : 10000000
	    min_seq  : 824330588
	    max_seq  : 834911226
serv_key_range
	    kv  : "" - ""
	    hash: "" - ""
	    zset: "" - ""
	    list: "" - ""
leveldb.stats
	                               Compactions
	Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
	--------------------------------------------------
	  0        0        0       241        0      8905
	  1        1        9       388    17035     13360
	  2       63     1572     11649   437404    436327
	  3      536    15974     72090  2181723   2181144
	  4     2172    67062     29232   950885    949936
```

这台 server 不是 ssd 磁盘，是云服务 vps, 总内存是 16G.

想请教一下，这样的情况应该往哪个方向去尝试调优，来让 server 响应时间尽量降低和平滑

非常感谢。

**Comment by ideawu** [comment]
看起来你们的服务应该是写频繁型, 是吧? 阶段性的load上升, 是因为ssdb在做compaction操作. compaction会涉及到硬盘读->CPU高强度计算-硬盘写这样的操作, 如果硬盘性能比较高的话, 硬盘读写会非常快速, 整个过程在数秒或者数十秒就可以完成. 如果硬盘性能不高且数据较多时, compaction就会非常耗时且影响正常的响应.

根据你的情况, 你可以尝试做下面的优化:

```
	write_buffer_size: 32
	compaction_speed: 500
```

write_buffer_size 减少后, 可将原来累积的compaction操作分散开来. compaction_speed减少后, 可让compaction进行得更柔和一些(当然会持续更长时间). 注意, compaction_speed 不能过小, 建议不小于200.

**Comment by larryzhao** [comment]
@ideawu 对的，会有很多大文本写入。十分感谢，我找时间调节一下参数。

另外还有个小问题，主动执行 `compact` 命令和您这里提到 `ssdb在做compaction操作` 其实是一回事吧。那 ssdb 已经再阶段性的做 compaction 的话，是不是其实没有必要来主动执行 `compact` 命令？

**Comment by ideawu** [comment]
手动执行也有用处, 但一般不需要. 注意, 手动执行 compact 要选在空闲时间(如凌晨).

你现在的cache_size也算合适, 你可以加到8000.

**Comment by larryzhao** [comment]
@ideawu 再次感谢 :+1:

**Comment by larryzhao** [comment]
@ideawu 非常感谢，我来简单汇报一下。我周五凌晨修改了参数为

```
cache_size: 8192
write_buffer_size: 32
compaction_speed: 500
```

然后观察了两天，基本上 IO 峰值 load 下降了一半，基本不会出现读写同时在 35-40MB/s 的情况，基本都是同时在 20MB/s 左右。这样应用的响应时间也保持在平稳的 100-200ms 不会阶段性的由于ssdb 响应慢而出现 400-500ms 的情况了。同时我也在准备迁移到 ssd 上面去了。

**Comment by ideawu** [comment]
@larryzhao 大赞! 非常高兴你的问题得到解决.
