### ISSUE TITLE
双主下模式自动flushdb问题 

### ISSUE THREAD

**Issue by MichaelXucf** [ideawu/ssdb#915]
Hi,ideawu
     我们在使用ssdb的过程中遇到一个很严重的问题，两个ssdb实例做了双主同步配置，数据写入过程中其中一个实例上突然自动开始执行flushsb操作，导致该实例上的数据被清空，flushdb期间客户端连接超时，links数量飙升。
    请问在什么情况下ssdb会自动做flushdb。同步过程中自动flushdb的原因是什么，谢谢
   我们使用的ssdb版本：1.9.2
   ssdb 双主配置：
![vj 00i 9 8 88uwtt 378 r](https://cloud.githubusercontent.com/assets/16697434/14636217/bb1c7b76-065c-11e6-9de5-d54e258a4902.png)
![idetyazl xeyd24vxv822ap](https://cloud.githubusercontent.com/assets/16697434/14636223/c03a1bc2-065c-11e6-91a2-b27e46b7c7fd.png)

这是做flushdb的机器（qs-ssdb1）是当时的日志，一开始是还是做copy的，突然就开始做flushdb了
![z1hd 7w1 zcr 2vb dk](https://cloud.githubusercontent.com/assets/16697434/14636636/357439de-065f-11e6-8069-95296ca9285c.png)

这是跟qs-ssdb1互为主从的机器（qs-ssdb2）的日志
![bka 8pt zj 4 ohbxr 7](https://cloud.githubusercontent.com/assets/16697434/14636679/76ab6cec-065f-11e6-9d68-ab554f9f00bf.png)

**Comment by ideawu** [comment]
你好, 无论是主从还是双主, 如果作为"从"的一方因网络故障或者自身原因, 导致binlog落后主太多(多于1千万条), 那么作为"主"的一方, 会向从发一个flushdb指令, 然后重新dump一份完整的数据.

你查下log.tx, 看看当时是否有 `OUT_OF_SYNC` 关键字?

**Comment by ideawu** [comment]
在一般情况下, 主从同步是不太可能落后1千万条binlog的. 除非是网络长时间故障, 或者主突然大量导入离线数据.

**Comment by MichaelXucf** [comment]
客户端用的是Jedis的ShardedJedisPool。
客户端在2016-04-19 16:14 出现java.net.SocketTimeoutException: Read timed out. 写入存在问题,连不上服务器。
ssdb服务器qs-ssdb2 上面在2016-04-19 16:46:35.588 有一条OUT_OF_SYNC.
 然后qs-ssdb1在2016-04-19 16:46:50.240 执行了flushdb。 
客户端写入的并发量是很大，每秒请求量在3~4 万。
我们用的是双主模式，如果一台master一直无法写入，另一台master数据还是持续写入，写入速度大于同步速度的话，应该会出现主从同步落后太多的情况。现在还不确定是什么原因引起的java.net.SocketTimeoutException: Read timed out

**Comment by MichaelXucf** [comment]
我们目前已经去掉双主模式，采用两个单独的ssdb实例。发现另一个问题是写入的wait时间很长，经常要等2ms~10ms，多的时候要等20~30ms，甚至超过100ms的。 写入的时候是2个应用，每个应用50个线程去写，写入量每秒：1w~3w。
![2bdh 5 l61 k6plnyn dva](https://cloud.githubusercontent.com/assets/16697434/14735599/52440e26-08a4-11e6-95fa-dfd4f80edca6.png)
请问下wu大，对于这个写入等待时间长有什么好的优化方式吗

ssdb里面的leveldb的配置：
leveldb:
        # in MB
        cache_size: 1000
        # in KB
        block_size: 32
        # in MB
        write_buffer_size: 64
        # in MB
        compaction_speed: 1000
        # yes|no
        compression: yes

**Comment by bandaotiehewen** [comment]
博主，你是qs-ssdb1在自身执行了flushdb后，两个实例数据都被清空了吗？
