### ISSUE TITLE
线程停止运行

### ISSUE THREAD

**Issue by wangchenghku** [ideawu/ssdb#916]
您好，我是ssdb的一位用户，我遇到的问题是这样的：
我劫持了ssdb的源代码的__libc_start_main函数，让ssdb在调用main函数之前先做一些我想让它做的工作。这里，我在__libc_start_main里面pthread_create了一个线程，这个线程会做一个简单的while(1)循环。然后其他就没有任何改动了，pthread_create之后就没有多余的操作了。
但是我发现当ssdb启动起来，我的这个线程while(1)循环线程就被杀掉了，没有在运行了。
请问这会是什么情况呢？

**Comment by ideawu** [comment]
我估计是因为ssdb在会main里fork, 而你在fork之前启动了线程.

由于ssdb是开放源码的, 所以建议你直接修改源码, 而不是使用调试技术或者勾子技术.
