### ISSUE TITLE
[求助]我采用双主模式部署的SSDB不断出现ttl=-1的数据，而且无法设定新的ttl

### ISSUE THREAD

**Issue by wonderbeyond** [ideawu/ssdb#918]
我在应用里面都明确设置了存活时间，但发现SSDB里面不断出现 `ttl=-1` 的数据，而且尝试重新给它们设定ttl无效（通过expire设定ttl返回0值，再次查看ttl仍为-1）。而且这些数据都可以通过keys扫描到，而且能正常get出来。

实在困惑到不行，大量数据搞成永久存活的了，导致应用缓存失控，无法控制其更新。

我还专门通过脚本把用keys扫描出来的并且 `ttl=-1` 的数据全部删掉，过了一会儿又出现大量这样的数据，实在无解了。求助！

- ssdb-server: 1.9.2
- 客户端：[lua-resty-redis](https://github.com/openresty/lua-resty-redis)(读) 和 [redis2-nginx-module](https://github.com/openresty/redis2-nginx-module) (写)

备注：用 redis2 写数据的时候我只用了 `setx` 一种指令。

**Comment by wonderbeyond** [comment]
不断出现`ttl=-1`的数据，我临时用下面的脚本清理：

```python
import pyssdb
c = pyssdb.Client(host='x.x.x.x', port=8888)
for key in c.keys('', '', 200):
    ttl = c.ttl(key)
    if str(ttl) == '-1':
        print key
        getattr(c, 'del')(key)
```

**Comment by ideawu** [comment]
Hi, 是否是 key 太长了?

**Comment by wonderbeyond** [comment]
啊！我后来才注意到key长度限制，恍然觉得可能有关系，然后一查果然发现出问题的key长度都在200以上。

后来改成md5存储以控制key长度，没有出现这样的问题了。

另外，key如果超长能否直接拒绝呢？目前是能存进去，但是表现怪异，以至于像我这样摸不着头脑（当然也怪我事先没注意到key长度限制才踩了雷）。

**Comment by ideawu** [comment]
好的, 这一块会在错误处理上更完善一些.

**Comment by wonderbeyond** [comment]
Hello! 我把key改成md5以限制长度之后，观察了一段时间确实没有再发现问题。
可是5天后（今天），又出现了2例`ttl=-1`的数据，最近五天我没有作任何程序和机制上的调整。

说明还有其它问题存在，但我实在没有更多的线索，请问该如何分析呢？求助！

我查了ssdb的日志，`tail -n1000000 /var/log/ssdb/ssdb.log | grep ERROR` 打印错来的错误消息都是5天前报的（key too long）。现在已经没有`key too long`的情况了。

**Comment by ideawu** [comment]
你好, 根据你找出来`ttl=-1`且仍然存在的key(也就是有问题的key), 在 log.txt 里 grep 一下.

另外, 如果没有设置过ttl的key, 执行 `ttl $key` 会返回 -1, 表示永远不过期, 你需要确认是否属于此种情况.

**Comment by wonderbeyond** [comment]
@ideawu 从昨天到现在都没有再次出现了, 我继续观察.

**Comment by wonderbeyond** [comment]
从上次出问题到现在，已经经过了5天的正常运行。

根据我的猜测，最后一次出的问题，原因应该还是跟最开始的 `key to long` 导致数据库状态异常相关，删除之后其它正常的K/V数据复用了原来的空间还会不正常。之所以这么猜测，是因为5天前我清理了一次数据存储目录，从头开始的。
