### ISSUE TITLE
python插入的队列用keys命令查不出来

### ISSUE THREAD

**Issue by howardyan93** [ideawu/ssdb#925]
redis-cli工具登录，在命令行里创建的东西，用keys '' '' 10能看到。
但是用python的ssdb库创建的东西，用lrange指定名字是可以查看，同时python也能取出来。但是在命令行用keys命令行显示就是空表。 
难道我用的姿势不对？

**Comment by ideawu** [comment]
ssdb 和 redis 最大的不同是, 不同的数据类型处在不同的名字空间. 所以 keys 只能遍历 KV 类型, 你说的 lrange 操作是针对 queue/list 类型, 所以不能用 keys 查看, 只能用 qlist.
