### ISSUE TITLE
Please add 'type' command 

### ISSUE THREAD

**Issue by shunanya** [ideawu/ssdb#927]
SSDB in contrast of Redis doesn't contain 'type' command. 
I don't think it will hard to implement especially taking into account you have already the command 'flushdb [type]' that gets parameter 'type'.
This command is really needed.

**Comment by ideawu** [comment]
SSDB is much different to Redis at this point. Different type of data can have the same name. So you can have a key named 'my' of type KV, and a same named key 'key' of type HASH.

So, there is no type command for SSDB.
