### ISSUE TITLE
ssdb 兼容redis select command

### ISSUE THREAD

**Issue by jtunggit** [ideawu/ssdb#934]
使用redis连接的类库时,切换到ssdb时候,出现select command错误,一两年前都是靠人肉解决这个兼容问题,现在ssdb现在还没有解决这个问题吗?

**Comment by ideawu** [comment]
Hi, ssdb不支持select命令, 所以, 你需要在你的代码里忽略对 select() 的调用.

注意: 你的业务逻辑不能依赖于 select!

**Comment by jtunggit** [comment]
好吧，理解了。
