### ISSUE TITLE
Is there a way to issue flushdb from system command line?

### ISSUE THREAD

**Issue by larryzhao** [ideawu/ssdb#937]
Hi, 

Is there a way to issue `flushdb` command from system command line or anyway that I could issue it from my program? It would be very helpful to cleanup the database during our auto unit test.

Thank you very much.

**Comment by ideawu** [comment]
Use this command:

```
printf "7\nflushdb\n\n4\nping\n\n" | nc 127.0.0.1 8888 -i 1
```

**Comment by larryzhao** [comment]
I tried it in my bash console, but I got this:

```
→ printf "7\nflushdb\n\n4\nping\n\n" | nc 127.0.0.1 8888 -i 1
12
client_error
24
Unknown Command: flushdb

2
ok
```

**Comment by ideawu** [comment]
Please upgrade your ssdb-server.

**Comment by larryzhao** [comment]
Hi, the script `printf "7\nflushdb\n\n4\nping\n\n" | nc 127.0.0.1 8888 -i 1` works fine earlier but seems it's not working with SSDB 1.9.4. Is there anything changed?
