### ISSUE TITLE
ssdb c++客户端api有bug

### ISSUE THREAD

**Issue by hljyunxi** [ideawu/ssdb#940]
c++客户端api的link->response并不能保证结果全部返回，会导致下一次请求读到上次返回的数据，线上遇到了这种情况，导致数据不一致

我会调用hgetall, hclear, set, get这几个命令，阻塞模式。
线上发下get命令会读到hgetall的数据。

**Comment by hljyunxi** [comment]
线上我会调用hgetall,hclear,get,set这4个命令，看详细是由于hgetall并没有全部返回，导致后续的操作读到了hgetall的返回结果

**Comment by ideawu** [comment]
你好, 客户端使用的link和ssdb-server是同一套代码, 因为服务器端从来没有报个类似的bug, 所以不太可能是代码bug.

你那边能提供可重现的代码, 或者你对link代码的分析吗? 另外, 你们是否使用了客户端多线程, 问题是多线程导致的? 而且, 麻烦你详细解释下"会导致下一次请求读到上次返回的数据".

**Comment by hljyunxi** [comment]
对连接的封装：
23	bool CSSDBConn::Init()
24	{
25	    if (m_pClient) 
26	    {
27	        return true;
28	    }
29	
30	    m_pClient = ssdb::Client::connect(m_strIp, m_iPort);
31	    if (!m_pClient) 
32	    {
33	        LOG_DBG("connect ssdb ip:%s, port:%d", m_strIp.c_str(), m_iPort);
34	        return false;
35	    }
36	
37	    return true;
38	}

270	ssdb::Status CSSDBConn::HGetAll(const string & strName, std::vector<std::string> & vecRet)
271	{
272	    if (!Init()) 
273	    {
274	        LOG_DBG("ssdb not init");
275	        return ssdb::Status("not_connect");
276	    }
277	
278	    ssdb::Status stStatus = m_pClient->hgetall(strName, &vecRet);
279	    if(stStatus.error() && !stStatus.not_found())
280	    {
281	        LOG_ERR("stStatus:%s", stStatus.code().c_str());
282	        delete m_pClient;
283	        m_pClient = NULL;
284	    }
285	
286	    return stStatus;
287	}

40	ssdb::Status CSSDBConn::Get(const string & strKey, string * pVal)
41	{
42	    if (!Init()) 
43	    {
44	        return ssdb::Status("not_connect");
45	    }
46	    
47	    ssdb::Status stStatus = m_pClient->get(strKey, pVal);
48	    
49	    if(stStatus.error() && !stStatus.not_found())
50	    {
51	        LOG_ERR("stStatus:%s", stStatus.code().c_str());
52	        delete m_pClient;
53	        m_pClient = NULL;
54	    }
55	
56	    return stStatus;
57	}

业务逻辑:

49	int CSSDBOperate::QueryFace(uint64_t ullKey, string & strFace)
50	{
51	    uint32_t ulDbIndex = m_dbConn.GetDbIndex(ullKey);
52	    static __thread char acKey[40];
53	    snprintf(acKey, sizeof(acKey), "%llu", (unsigned long long int)ullUin);
54	    string strKey(acKey);
55	    int iRet = m_dbConn.Get(ulDbIndex, strKey, &strFace);
56	
57	    //解密图片
58	    if(iRet == 0)
59	    {
60	        __thread static char acDecryptBuf[MAX_PKG_LEN] = {0};
61	        memset(acDecryptBuf, 0, sizeof(acDecryptBuf));
62	        int iDecryptLen = sizeof(acDecryptBuf);
63	        if(Decrypt(strFace.c_str(), strFace.size(), \
64	                    g_acKeyPart2, acDecryptBuf, iDecryptLen))
65	        {
68	            iRet = -1;
69	            strFace.clear();
70	            return iRet;
71	        }
72	
73	        strFace = string(acDecryptBuf, iDecryptLen);
74	    }
75	
76	    return iRet;
77	}
78	

82	int CSSDBOperate::QueryFaceInfo(uint64_t ullKey, std::vector<std::string> & vecRet)
83	{
84	    uint32_t ulDbIndex = m_dbConn.GetDbIndex(ullKey);
85	    static __thread char acKey[40];
86	
87	    snprintf(acKey, sizeof(acKey), "%llu", (unsigned long long int)ullKey);
88	    string strKey(acKey);
89	
90	    int iRet = m_dbConn.HGetAll(ulDbIndex, strKey, vecRet);
91	
92	    return iRet;
93	}


Get操作读取的是图片一般30K左右，hgetall读取的是元数据信息（正常的返回是一个长度为6的vector，里面存了key1, key2, key3）

线上日志发现断断续续的有读取照片解密失败的现象发生，把照片打印出来发现，照片的内容是key1（hgetall的返回）
