### ISSUE TITLE
ssdb可否考虑与lmdb的集成

### ISSUE THREAD

**Issue by bwzhang2011** [ideawu/ssdb#945]
@ideawu, 可否考虑集成lmdb的支持。

**Comment by ideawu** [comment]
你好, 没有这个考虑. 因为不同的引擎的数据结构是不一样, 无法做到平滑切换, 而其它的引擎相比leveldb并没有明显的优势, 所以没有必要支持. 如果你比较感兴趣, 可以自己试试.
