### ISSUE TITLE
ssdb fast import

### ISSUE THREAD

**Issue by nick2012** [ideawu/ssdb#947]
Can I do something like this with SSDB also?

**redis_cmd.txt | redis-cli --pipe**

redis_cmd.txt has 800MB of commands.

**Comment by ideawu** [comment]
Yes, here is examples:

```
echo "get a" | /usr/local/ssdb/ssdb-cli 2>/dev/null
cat a.txt | /usr/local/ssdb/ssdb-cli 2>/dev/null
```

**Comment by nick2012** [comment]
Thank you!
