### ISSUE TITLE
进程的max open files已经设置到了1020000，日志中max_open_files还是500

### ISSUE THREAD

**Issue by oldcai** [ideawu/ssdb#954]
找到设置项了，是
```
leveldb:
        max_open_files: 1020000
```
但是文档中没有相关说明，只能从源码中找线索。

解决了问题后，写了一篇关于[SSDB在CentOS 7.2中打开文件数的文档](http://www.oldcai.com/archives/1123)，希望能对SSDB社区有所帮助。

**Comment by oldcai** [comment]
感谢回复。

了解了，那日志中或许应该明确一点，目前可能会误以为是ssdb读取到的进程限制之类的。

**Comment by ideawu** [comment]
谢谢你的建议.
