### ISSUE TITLE
非daemon模式启动仍然创建PID文件

### ISSUE THREAD

**Issue by wonderbeyond** [ideawu/ssdb#955]
`/etc/ssdb/ssdb.conf` 配置片段:

```
...
work_dir = /var/lib/ssdb
pidfile = /var/run/ssdb.pid
...
```

按常理，`pidfile`的配置项应该只在 daemon 模式下才有效，但我采用非 daemon 模式启动后仍然创建了PID文件，当我利用 supervisor/systemd 做进程管理时遇到了不大不小的麻烦。

希望能够提供不创建PID文件的选项，谢谢！

**Comment by ideawu** [comment]
你好, pid文件会造成什么问题?

**Comment by wonderbeyond** [comment]
是这样，用了进程管理系统后，daemon模式是没有必要的，PID文件更是没有意义的。特别当进程异常崩溃后再去启动的时候还要额外删除PID文件才能启动，用supervisor我需要额外包装个脚本，里面实现为启动ssdb的时候强制删除PID文件。

**Comment by ideawu** [comment]
会在下一个版本进行更改.

**Comment by ideawu** [comment]
dev 分支已经更改了.

**Comment by wonderbeyond** [comment]
Good job
