### ISSUE TITLE
OUT_OF_SYNC状态怎么破?

### ISSUE THREAD

**Issue by wonderbeyond** [ideawu/ssdb#956]
很抱歉，我在一个节点改了对端的节点ID，还清空过数据，目前出现 `OUT_OF_SYNC` 问题，求助要怎么恢复同步状态。
很抱歉我很难描述目前具体的状态，我是准备从`双主`过渡到`多主`模式的，结果半途出现故障，目前的中间状态我很难描述清楚，我看文档对 `OUT_OF_SYNC` 的描述太简单了，我没看懂，有没有具体点的解释呢？还有，遇到 `OUT_OF_SYNC` 要怎么着手解决呢，麻烦提供点信息，谢谢！

**Comment by wonderbeyond** [comment]
正在准备把3个节点的两个节点停止服务，并清空数据。然后把三个节点的ID全改成新的，然后重启仅剩下的节点，然后再依次启动另外两个节点。

隐隐感觉改节点ID会有副作用，所以我干脆改成全新的重头来了。

**Comment by wonderbeyond** [comment]
按照上面的操作使得3主成功保持互相为`SYNC`的状态后，我只重启了一下节点，结果又出现了一个节点状态为`OUT_OF_SYNC`的情况。。。好无助。。。

**Comment by wonderbeyond** [comment]
我准备把丢失同步的节点（从自身看状态是`INIT`，从对方看状态是`OUT_OF_SYNC`）清空数据重新来了，不知进入了什么错乱状态。

**Comment by wonderbeyond** [comment]
算了，我先保持现场，不操作了。反正3个节点有两个时能互相`SYNC`的，某个节点与另一个节点的同步进入了`INIT`和`OUT_OF_SYNC`状态，暂时至少还是“双主”的。

**Comment by wonderbeyond** [comment]
下周我会把目前的状态描述清楚，希望能提供援助！

**Comment by wonderbeyond** [comment]
https://github.com/ideawu/ssdb/issues/784
跟这个issue有相似的地方。

**Comment by ideawu** [comment]
你好:

1. 建议不要使用多主, 因为多主的复杂度比双主要高很多数量级.
2. 如果主从能满足你的需求, 用主从即可.
3. 找出一个节点, 这个节点的数据就是你想要的. 然后把其它节点的数据备份后删除并作为从.

**Comment by wonderbeyond** [comment]
确实有点难以驾驭，搞得我很紧张。

我刚才看到了这个issue https://github.com/ideawu/ssdb/issues/800，受到启发，我把三个节点全部停止（这会导致我的缓存层短暂失效），然后删除所有的meta目录，然后依次重启。
经过几分钟紧张的等待，三个节点终于进入了两两保持sync的状态。

我观察一段时间吧，不好玩的话，我继续用着双主模式吧。

**Comment by wonderbeyond** [comment]
Today I've got back to the regular double-master deployment mode.

**Comment by ideawu** [comment]
从 1.9.3 版本开始, 可能在配置文件里配置

```
replication:
	binlog: yes
		capacity: 100000000
```
来避免 OUT_OF_SYNC.
