### ISSUE TITLE
Logging levels

### ISSUE THREAD

**Issue by felixsanz** [ideawu/ssdb#957]
The docs says:

> The log levels are: debug, warn, error, fatal.

But when i run ssdb-server i get this:

> 2016-07-22 17:41:54.273 [INFO ] binlog.cpp(183): binlogs capacity: 20000000, min: 0, max: 0,
> 2016-07-22 17:41:54.280 [INFO ] server.cpp(171): server listen on 127.0.0.1:8888
> 2016-07-22 17:41:54.280 [INFO ] server.cpp(181): auth: off
> 2016-07-22 17:41:54.280 [DEBUG] cluster.cpp(13): Cluster init

Why INFO ?

**Comment by ideawu** [comment]
OK, I will update the docs.
