### ISSUE TITLE
使用redis客户端操作ssdb队列，数据不一致

### ISSUE THREAD

**Issue by chenshangwei** [ideawu/ssdb#959]
ssdb版本：ssdb-server 1.9.0
php-redis客户端：phpredis-2.2.4

php操作：
    $redis->lPush('test_xx', 'zzzz')   #仅执行一次
进入ssdb命令行：
   ssdb 127.0.0.1:9999> qsize test_xx
   结果出来的数字是 2

想请问作者，是不是redis原生客户端支持不好？或者这是个bug?
本人想在业务中使用ssdb+keepalived搭建高可用的队列服务器，
为了降低迁移成本，打算让phper使用原生的redis客户端。

**Comment by ideawu** [comment]
并没有这个问题, 我怀疑你犯了一个低级的错误, 测试脚本执行了两次, 谢谢!

**Comment by chenshangwei** [comment]
问题确认 是因为php测试  var_dump(写队列操作) 会执行2次
