### ISSUE TITLE
对于主从同步方式的疑问

### ISSUE THREAD

**Issue by majiahui** [ideawu/ssdb#960]
请教一个关于master-slave同步方式的问题：
master用multi_hset写入数据，从slave的日志看ssdb是基于数据一条一条同步的，在大量的批量写入操作下主从同步延时严重，甚至会导致OUT_OF_SYNC。
请问采用这种单条数据同步方式而非记录整个multi指令到slave执行，基于哪些考量？

**Comment by ideawu** [comment]
从 1.9.3 版本开始, 可能在配置文件里配置

```
replication:
	binlog: yes
		capacity: 100000000
```
来避免 OUT_OF_SYNC.
