### ISSUE TITLE
尝试基于up主的ssdb重构部分模块,迭代出基于seastar的服务器框架，求up主意见

### ISSUE THREAD

**Issue by xiyanxiyan10** [ideawu/ssdb#966]
- 最终目地是探索dpdk整合一套服务器框架
 - 选定切入点为制作文件服务器，用具体业务进行框架迭代
 - 目前看好的是seastar，其为易于dpdk开发的服务器框架
 - 打算使用seastar的网络层替换ssdb的网络层来切入（重构网络层，自定义协议栈），重构出文件服务器
 - 后续再尝试切入硬核绑定等dpdk支持的东西进行融合和迭代。
 - 求up主关于融性和注意的建议。

**Comment by ideawu** [comment]
请问你的母语不是中文吗? 如果是这样, 你可以使用英文来提交 issue, 谢谢. If your first language is not Chinese, you can also post your issue in English.

**Comment by Androidsuzhen** [comment]
### 有意思
