### ISSUE TITLE
src/util/bytes.cpp - Buffer

### ISSUE THREAD

**Issue by westarest** [ideawu/ssdb#978]
hi:

src/util/bytes.cpp 
是否应该增加两行代码？
Buffer::read_record(Byte* s){
85行：this->size_ -= head_len + body_len + 1;
add: this->data_ += head_len + body_len +2;
91行: this->size_ -=head_len + body_len +1;
add: this->data_ +=head_len + body_len+2;
否则连续调用read_record会出错

**Comment by ideawu** [comment]
谢谢你的反馈, 已经在 dev 分支上 fixed 了. 由于这个方法没有在项目中被使用, 只做调试时使用, 所以对 ssdb 项目的正常使用没有影响.
