### ISSUE TITLE
New python client for SSDB on Cython

### ISSUE THREAD

**Issue by deslum** [ideawu/ssdb#979]
Hello, please add link on my python client for SSDB.
https://github.com/deslum/cssdbpy
Thank you.

**Comment by ideawu** [comment]
Added to http://ssdb.io/docs/clients.html#python

**Comment by deslum** [comment]
Thank you

**Comment by deslum** [comment]
And the end. Your blog has the ability to publish articles from any users? http://www.ideawu.com/blog/post/category/python

**Comment by ideawu** [comment]
I have heard several people said you send them emails to advertise you project, that brought confusion to them, and they were really annoyed. So I decided to remove link of you project from ssdb api clients list.

**Comment by deslum** [comment]
Sorry.I did not want anything bad. I thought that my client will be useful for your observers. Sorry

**Comment by deslum** [comment]
I have many letters of thanks from users. I think that my project is useful for you.
