### ISSUE TITLE
关于worker->pop传参的疑问

### ISSUE THREAD

**Issue by rainingmaster** [ideawu/ssdb#980]
hello，ideawu :
    我对这个地方[worker->pop](https://github.com/ideawu/ssdb/blob/master/src/net/server.cpp#L247)传参有点疑问。[这里](https://github.com/ideawu/ssdb/blob/master/src/util/thread.h#L333)使用的参数应该是一个 \*job，而不是 \*\*job 吧？是不是我对理解不对？

**Comment by ideawu** [comment]
你理解错了, 你需要再仔细理解指针.

**Comment by rainingmaster** [comment]
明白了。不好意思，在pop（JOB）处的 JOB 是一个 \*job，而 \*JOB 则是 \*\*job 啊。十分抱歉:(
