### ISSUE TITLE
ssdb deps依赖升级

### ISSUE THREAD

**Issue by bwzhang2011** [ideawu/ssdb#982]
@ideawu, leveldb前不久释放了1.19版本，然后jemalloc的稳定版是4.2.1， snappy是1.1.3。是否有计划将ssdb的一些依赖升级到当前的稳定版本中。

**Comment by cau991** [comment]
同问！

**Comment by ideawu** [comment]
这些 deps 的新版本并没有明显的改进, 所以 ssdb 不会采用激进跟进的方式升级.

**Comment by bwzhang2011** [comment]
@ideawu, leveldb的更新可参看https://github.com/google/leveldb/releases 还是解决了许多问题，其中也合并了你以前提交的ISSUE。我个人参看你在deps中做的修改，然后做了升级，也很顺利进行了测试，但不清楚能否百分百兼容。
