### ISSUE TITLE
在docker环境下无法安装！使用官方dockerhub的Dockerfile 也不可以什么情况？？

### ISSUE THREAD

**Issue by zxf668899** [ideawu/ssdb#983]
ERROR! autoconf required! install autoconf first

Makefile:4: build_config.mk: No such file or directory
make: *** No rule to make target `build_config.mk'.  Stop.
在docker下 总是报这个错误，使用docker hub上的Dockerfile 也不行，但是使用虚拟机环境就可以！
而且 autoconf 已经安装过了！直接使用下载来的镜像可以运行！但是自己构建 就报错！
怎么解决？？？

**Comment by ideawu** [comment]
估计你需要在 docker 里安装  autoconf

**Comment by zxf668899** [comment]
已经安装了autoconf ，但是还是不行，虚拟机安装就没有问题，好奇怪。。。而且dockerfile 也是官方出的 但是依旧不行

**Comment by ideawu** [comment]
确定是 build.sh 用到了不兼容的语法, 已经fix https://github.com/ideawu/ssdb/commit/b4e4fe25a2289f6ae44f43cc6ed51405e6c9cc64

**Comment by zxf668899** [comment]
我再次试了下，和 if 语法没有关系，这里：` which autoconf > /dev/null 2>&1`  由于官方镜像并没有安装which 这个命令，所以导致此处判断错误，进而无法编译！ 我用的是CentOS7.2官方镜像！在Dockerfile构建的时候添加安装 which autoconf 就可以了！
