### ISSUE TITLE
使用docker安装ssdb时,volume 访问有问题。导致访问无法启动

### ISSUE THREAD

**Issue by xjcloudy** [ideawu/ssdb#985]
您好。
我本地是windows 环境。使用docker for windows。
dockerfile 基本与你提供的一致。
在run container 时发现出错。
`docker run`命令是这样的 ：`docker run -d --name="ssdb" -p 8888:8888 -v ${pwd}:/var/lib/ssdb ssdb`
通过`docker inspect` 得到的信息mounts部分为:

``` javascript
 "Mounts": [
            {
                "Source": "/D/work/workspaces/product/docker-images/images/ssdb",
                "Destination": "/var/lib/ssdb",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],

```

通过`docker logs ssdb` 得到的信息为

```
ssdb-server 1.9.4
Copyright (c) 2012-2015 ssdb.io

could not open data db: /var/lib/ssdb/data
```

但是在本地文件夹下发现。data 文件已经创建。并且有数据文件生成。就是说container中访问host的文件系统是没有问题的。
![image](https://cloud.githubusercontent.com/assets/2074921/18614618/614af48a-7dc4-11e6-902c-b3caaa3b4317.png)
![image](https://cloud.githubusercontent.com/assets/2074921/18614622/72d859cc-7dc4-11e6-9dd5-c0302f7a1dba.png)

那么问题出在哪里就很奇怪了？
可能还是 docker 自身对windows 的兼容性不好。如果您有兴趣的话，可以对这个问题跟踪一下。

**Comment by ideawu** [comment]
你好, 我对 docker 不熟悉, 你可能需要把这个问题也发到专门讨论 docker 的地方, 可能有人能快速帮助解决.

另外, 你可以看看 ssdb 生成的 log.txt, 看看是否有线索.

**Comment by xjcloudy** [comment]
不好意思。来晚了。谢谢你的回复。我后面又尝试了一下对比测试。在mac os 和 linux 环境下。运行了一下。都正常。后续有空我会继续和运维同学跟进。如果有其他用户发现解决方案，请add comment。
再次感谢 @ideawu

**Comment by zyuyou** [comment]
@xjcloudy 有找到解决方法吗? Docker for windows 我这边也遇到这个问题

**Comment by zyuyou** [comment]
最新的 Docker for windows 2.2 已经解决了这个问题, 可以关掉了issue了

**Comment by xjcloudy** [comment]
谢谢提醒

> 最新的 Docker for windows 2.2 已经解决了这个问题, 可以关掉了issue了
