### ISSUE TITLE
SSDB in read-only partition

### ISSUE THREAD

**Issue by ignaciovazquez** [ideawu/ssdb#989]
Is SSDB able to operate using only read commands in a read-only disk?

**Comment by ideawu** [comment]
Hi, SSDB does not support read-only mode, it is the clients' responsibility to operate only read commands to a read-only node.

**Comment by ignaciovazquez** [comment]
Yes, I understand that.

But will SSDB run correctly if the data files live in a read-only filesystem?

**Comment by ideawu** [comment]
Hi, the anwser is NO.

Because SSDB will write logs to file, re-arrange data files, etc... If the OS and disk does not allow writing file(create new files, rename existed files, update files, remove files, ...), the whole service will fail.

**Comment by ideawu** [comment]
Hi, now SSDB support readonly mode through client side. That means, if the ssdb server is working in readonly mode(configuration file configured), clients will not be able to execute write operations such as `set, del`, etc.

**Comment by ignaciovazquez** [comment]
Thanks man,

Just one comment, is it possible to run SSDB in a read-only partition? I'd like to mount a SSDB data directory in many machines at the same time. 

No one will be writing to SSDB, but I want to make sure no process in the server wants to run a compaction or other housekeeping processes on the read only disk.
