### ISSUE TITLE
Missing 1.9.2 tag

### ISSUE THREAD

**Issue by dunn** [ideawu/ssdb#995]
There used to be a tag for 1.9.2; Homebrew used it in our formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ssdb.rb

It's no longer available.  Was it reverted, or was it removed by accident?

Thanks!

**Comment by ideawu** [comment]
Hi, the tag `1.9.2` was removed. I just added tag `1.9.2`, based on master.

**Comment by ideawu** [comment]
But I would recommend always using the master.

**Comment by dunn** [comment]
Thanks!

> But I would recommend always using the master.

In Homebrew we require stable releases; should the tags not be considered stable?

**Comment by ideawu** [comment]
The master is always the latest stable release.

**Comment by dunn** [comment]
OK, thanks!
