### ISSUE TITLE
ssdb可否加入针对basho/leveldb的支持

### ISSUE THREAD

**Issue by bwzhang2011** [ideawu/ssdb#996]
@ideawu, basho的leveldb是比较活跃的分支，注意到 http://www.ideawu.net/blog/guestbook?cp=4#comments 中曾也有网友问过类似的问题，根据你在留言的提示，我下载了basho leveldb的最近释放的版本（2.0.29）然后做了编译，但无法通过，提示如下：
g++ -DNDEBUG -D__STDC_FORMAT_MACROS -Wall -O2 -Wno-sign-compare  -I "/usr/local/software/ssdb_test/ssdb-master/deps/leveldb-2.0.29/include" -I "/usr/local/software/ssdb_test/ssdb-master/deps/jemalloc-4.1.0/include" -c ssdb_impl.cpp
In file included from /usr/local/software/ssdb_test/ssdb-master/deps/leveldb-2.0.29/include/leveldb/options.h:59:0,
                 from /usr/local/software/ssdb_test/ssdb-master/deps/leveldb-2.0.29/include/leveldb/iterator.h:20,
                 from /usr/local/software/ssdb_test/ssdb-master/deps/leveldb-2.0.29/include/leveldb/db.h:10,
                 from ssdb_impl.h:9,
                 from ssdb_impl.cpp:6:
/usr/local/software/ssdb_test/ssdb-master/deps/leveldb-2.0.29/include/leveldb/expiry.h:28:33: fatal error: util/refobject_base.h: No such file or directory
 #include "util/refobject_base.h"

提示是无法找到util/refobject_base.h这样的文件或目录，但是在相关的目录下是有的——不知道为什么编译不通过，能否指点一二。

**Comment by ideawu** [comment]
Hi, 从你提供的信息来看, 应该是 basho/leveldb 自己的问题, 你可以先确认其是否可以正常编译, 然后再整合进 ssdb 中.

**Comment by bwzhang2011** [comment]
@ideawu, 编译的问题已经解决了。需要将util目录拷贝到leveldb-2.0.29的include目录下，然后执行安装。
经过测试，我发现basho/leveldb比原生带的1.18的性能要差一些（不知道原因），后续我会跟进这个问题。

**Comment by bwzhang2011** [comment]
@ideawu, basho leveldb已经发布了，我测试了一下这个版本，发现性能还不错，CPU的占用率也较低。
